<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script type="text/javascript">
function getInterests(officetype_id,path) {
	if(officetype_id) {
		targeturl=path+"/officedefault/index/suboffice?officetype_id="+officetype_id;
		$.ajax({ url: targeturl, success: function(data){ $("#statediv").html(data) }});
	}
}
</script>

<fieldset>
    <legend><?php echo $this->translate('NewOffice'); ?></legend>
        <div class="register">
            <div class="profile_tab">
                <form action="<?php  echo $this->baseUrl();?>/officedefault/index/officeedit/id/<?php echo $this->id ?>" method="POST" name="joe" id="signupForm" class="cmxform">

                    <div class="btnhouse">
<div class="rtbtns">
    <td><a href="<?php echo $this->baseUrl();?>/officedefault/index/deleteoffice/id/<?php echo $this->id; ?>/sub_id/<?php echo $this->sub_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
	</div>
</div>

                    <table style="float:left">  
                        <tr>
                            <td><?php echo $this->translate('Office type'); ?></td><td><?php  echo $this->form->officetype_id;?></td>    
                        </tr>
                        <tr>
                           <td><?php echo $this->translate('Parent office'); ?></td> <td><div id="statediv"><?php echo $this->form->parentoffice_id; ?></div></td>    
                        </tr>
		        <tr><td><?php echo $this->translate('Office name'); ?></td>
			<td><?php  echo $this->form->name;?></td>
		        </tr>
		        <tr><td><?php echo $this->translate('Office short name'); ?></td>
			<td><?php  echo $this->form->short_name; echo $this->form->createdby; echo $this->form->createddate; ?></td>
		        </tr>
        		<tr>
			<td><input name="Submit" id="Submit" type="submit" class="officebutton" value="<?php echo $this->translate('Submit'); ?>"></td>
		        <td><a href=<?php echo $this->baseUrl();?>/office/index>
                        <input name="submit" type="submit" class="officebutton" value="<?php echo $this->translate('cancel'); ?>"></a></td>
	           	</tr>
                        <tr>
			<td></td>
			<td><B style='color:red'><?php echo $this->error; ?></B></td>
		        </tr>
	         </table>
	   </form>
	</div>
    </div>
</fieldset>
