<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset style="width:759px;float:left">

<div style="width:480px;float:left"> 

    <TABLE id="hor-minimalist-b">
        <tr><Th>Delete category</Th><th></th><th></th><th><th></th></tr>
        <?php foreach($this->categorydetails as $category) {  ?>

				<TR>
					<TD>Category Name</TD>
					<TD></TD>
					<TD></TD>
					<TD><?php echo $category['name'];?></TD>
					<TD></TD>
				</TR>
				<TR>
					<TD>Category Description</TD>
					<TD></TD>
					<TD></TD>
					<TD><?php echo $category['description'];?></TD>
					<TD></TD>
				</TR>
				<tr>
                                <TD></TD><TD></TD>
					<TD></TD>
					<TD></TD>
					<TD></TD></tr>
			</TABLE>
<TABLE id="hor-minimalist-b">
<tr><Th>Confirm Delete</th></tr>
<?php } ?>
	
			<div class="cont-rgt-data">
				<form action="<?php echo $this->baseUrl();?>/category/index/categorydelete/id/<?php echo $this->id; ?>" method="POST" name="joe" id="signupForm" class="cmxform">
				<table id="hor-minimalist-b" summary="Employee Pay Sheet">
					<TR>
						<TD  width="35%" align="right" ><label>Remarks<span class="reqMark">*</span></label></TD>
						<TD  width="65%"  align="left" ><?php echo $this->deleteform->remarks;?></TD>
									</table>
					</tr>
							<td><input type="submit" name="Delete" id="Submit" value="Delete"></td>			

						
					<TD><a href="<?php echo $this->baseUrl(); ?>/category">
					<input name="submit" type="submit" class="No" value="No"></a></TD>
					<TD></TD>
					<TD></TD>
					<TD></TD>
					<TD></TD>
				</TR></TD>
					</TR>
				</form>
			
</fieldset>
</div>
