<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
   <legend>Delete interest rates</legend>
       <div class="register">
           <div class="profile_tab">

               <form action="<?php echo $this->baseUrl();?>/interestrates/index/interestratesdelete/interest_id/<?php echo $this->interest_id;?>" method="POST"  name= "myform">
                   <table id="hor-minimalist-b">

                       <TR>
                           <TD><font color="red">Are you sure you want to delete</font><font color="green"> <?php  ?></font><span class="reqMark">*</span></TD>
                           <TD><?php echo $this->deleteForm->remarks;?></TD>
                       </TR>
                       <tr>
			<TD><input type="Submit" name="Delete" value="Delete"></TD>
			<td><a href="<?php echo $this->baseUrl(); ?>/interestrates/index/interestratesedit/interest_id/<?php echo $this->interest_id; ?>">
			<input type="button" value="Back" />
                                           </a></td>
                       </TR>
               </table>
           </form>
       </div>
   </div>
</fieldset>