<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<BODY onload="toggleField();"></BODY> 
<div>
    <div style="width:350px;float:left">

    <table id="hor-minimalist-bjinu" summary="Employee Pay Sheet"> 
            <?php if ($this->groupname) { ?>
            <TR class="tdbrown">
                    <TD width="20%">Name</TD>
                    <TD width="20"><?php echo $this->groupname;?></TD>
            </TR>
            <? }?>
            <?php if ($this->memberfirstname ) { ?>
            <TR class="tdbrown">
                    <TD width="20%">Name</TD>
                    <TD width="20"><?php echo $this->memberfirstname;?></TD>
            <? }?>
            <?php foreach($this->recurringAccountDetails as $productRecurringDetails) : ?>
            <TR>
                    <td width="40%"><b class="star">Producttype:</b></td>
                    <TD width="60%"><?php echo $this->escape($productRecurringDetails['productname']);?></TD>
            </TR>
            <TR>
                    <td width="40%"><b class="star">Productname:</b></td>
                    <TD width="60%"><?php echo $this->escape($productRecurringDetails['offerproductname']);?></TD>
            </TR>
            <TR>
                    <td width="40%" ><b class="star">Begin date:</b></td>
                    <TD width="60%"><?php echo $this->escape($productRecurringDetails['begin_date']);?></TD>
            </TR>
            <TR>
                    <td width="40%" ><b class="star">Mature date:</b></td>
                    <TD width="60%"><?php echo $this->escape($productRecurringDetails['mature_date']);?></TD>
            </TR>
            <TR>
                    <td width="40%"><b class="star">Amount:</b></td>
                    <TD width="60%"><?php echo $this->escape($productRecurringDetails['recurring_amount']);?></TD>
            </TR>
            <?php endforeach;?>
            <tr>
                    <td width="40%"><B style="color:red">Capital amount:</b></td>
                    <TD width="60%"><B style="color:red"><?php echo $this->paidAmount;?></B></TD>
            </TR>
            <TR>
                    <td width="50%"><B style="color:red">Gross interest:</b></td>
                    <TD width="50%"><B style="color:red"><?php echo $this->simpleInterest;?></B></TD>
            </TR>
            <TR>
                    <td width="50%"><B style="color:red">Gross amount:</b></td>
                    <TD width="50%"><B style="color:red"><?php echo $this->matureAmount;?></B></TD>
            </TR>
    </table>
    </div>
</div>

<DIV style="float:left;width:50%">
<?php If($this->membertypr_id==3) { ?>
<a href="#" id="open">groupMembers</a>
<div class="box">
<div id="content1">
        <fieldset>
                <legend>Members in account</legend>
                <div class="cont-rgt-data">
        <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                <tr class="tdbrownheading">
                        <td width="30%">Name</td>
                        <td width="50%">code</td>
                </tr>
        <?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
                        <tr class="tdbrown">
                                <TD width="30%"><?php echo $arrayroles1['memberfirstname'];?></TD>
                                <TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
                        </tr>
        <?php }?>
                </table>
</div></fieldset>
<p><a href="#" id="close">hide</a></p>
</div>
</div>
<?php }	?>
<table width="100%"><TR><TD></TD></TR></table>
</DIV>

<div style="float:left;width:50%">

        <div class="cont-rgt-data">
            <table id="hor-minimalist-bjinu" summary="Employee Pay Sheet" border="1">
                <TR>
                    <td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/recurringtransaction/index/recurrings/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/manualRepayment/no">Deposit</a></TD>
                </TR>
                <TR>
                    <td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/recurringtransaction/index/newaccount/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>">accountRenewal</a></TD>
                </TR>
                <tr>
                    <td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/recurringtransaction/index/status/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>">status</a></TD>
                </TR>
                <tr>
                    <td width="100%"><a href="<?php echo $this->baseUrl(); ?>/recurringtransaction/index/transfer/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/matured/<?php echo base64_encode($this->paidAmount);?>">accountCloseAndTransferFunds</a></TD>
                </TR>
            </table>
        </div>

</div>

<?php If($this->groupname) { ?>
    <fieldset>
        <legend>Type of format</legend>
        <div class="cont-rgt-data">
            <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                <tr>
                    <td><a href="<?php echo $this->baseUrl(); ?>/recurringtransaction/index/recurrings/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/manualRepayment/no">Automatic Reccuring payment</a></td>
                </tr>
                <tr>
                    <td><a href="<?php echo $this->baseUrl(); ?>/recurringtransaction/index/recurrings/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/manualRepayment/yes">Manual recurring payment</a></td>
                </tr>
            </table>
        </div>
    </fieldset>
<?php } ?>

<div style="float:left;width:770px">
    <?php if(!$this->Submit) { ?>
        <fieldset>
        <legend>Deposit1</legend>
            <div class="cont-rgt-data">
                <form name="form1" action="<?php echo $this->baseUrl();?>/recurringtransaction/index/deposit/manualRepayment/<?php echo $this->manualRepayment;?>" method="POST" >
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <TR class="tdbrown">
                        <TD width="40%">Date<span class="reqMark">(yyyy-mm-dd)*</span></TD>
                        <TD width="60%"><?php echo $this->recurringForm->accountId;?><?php echo $this->recurringForm->productId;?><?php echo $this->recurringForm->recurringDate;?></TD>
                    </TR>
                </table>
                <?php if($this->manualRepayment=='yes' && $this->groupname) { ?>
                <tr>
                    <TD>
                        <fieldset>
                        <legend> Enter Individual member amount  </legend>
                            <div class="cont-rgt-data">
                                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                                    <tr class="tdbrownheading">
                                        <td width="39%">Name</td>
                                        <td>Amount</td>
                                    </tr>
                                    <?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
                                        <tr class="tdbrown">
                                            <TD width="39%"><?php echo $arrayroles1['memberfirstname'];?></TD>
                                            <td><?php $a='amount'.$arrayroles1['member_id'];echo $this->recurringForm->$a; ?></TD>
                                        </tr>
                                    <?php }?>
                                </table>
                            </div>
                        </fieldset>
                    </TD>
                </tr>
                <?php }	?>
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <TR class="tdbrown">
                            <TD width="40%">Amount<span class="reqMark">*</span></TD>
                            <TD width="60%"><?php echo $this->recurringForm->amount;?></TD>
                    </TR>
                    <TR class="tdbrown1">
                            <td width="20%">Transaction mode<span class="reqMark">*</span></td>
                            <TD><?php echo $this->recurringForm->transactionMode; ?>
                            <?php echo $this->recurringForm->paymenttype_details;?>
                            <h id="details" style="display:none">voucher/cheque/draft number</h></td>
                    </TR>
<!--						<tr>
                                                        <td ><description</td>
                                                        <td ><?php echo $this->form1->transactiondescription;?></td>
                                                        <td ></td>
                                                </tr>-->
                <?php if($this->recurringForm->fine) { ?>
                <tr class="tdbrown1">
                        <td width="20%">Fine R$</td>
                        <TD><?php echo $this->recurringForm->fine; ?></TD>
                </TR>
                <?php } ?>
            </table>
            <table>
                <tr>
                    <td></td>
                    <td ></td>
                    <td><span class="reqMark">* Markedfieldsaremandatory</span></td>
                </tr>
                <TR>
                    <TD><?php echo $this->recurringForm->Confirm;?></TD>
                    <td><a href="<?php echo $this->baseUrl();?>">
                    <input name="submit" type="submit"  value="back" tabindex="25"></a></td>
                </TR>
            </table>
            </form>
        </div>
    </fieldset>
<?php } ?>

        <?php if($this->Submit) { ?>
                <fieldset>
                <legend>Deposit</legend>
                    <div class="cont-rgt-data">
                        <form name="form1" action="<?php echo $this->baseUrl();?>/recurringtransaction/index/deposit/manualRepayment/<?php echo $this->manualRepayment;?>" method="POST" >
                            <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                            <TR class="tdbrown">
                                <TD width="40%">Date<span class="reqMark">(yyyy-mm-dd)*</span></TD>
                                <TD width="60%"><?php echo $this->recurringForm->accountId;?><?php echo $this->recurringForm->productId;?>
                                <?php echo $this->recurringForm->recurringDate1;?>
                                <?php echo $this->recurringForm->amounts1;?>
                                <?php echo $this->recurringForm->transactionMode1;?>
                                <?php echo $this->recurringForm->paymenttype_details1;?>
                                <?php echo $this->recurringForm->fine1;?>
                                <?php echo $this->recurringDate;?></TD>
                            </TR>
                            </table>
                            <?php if($this->manualRepayment=='yes' && $this->groupname) { ?>
                            <tr>
                            <TD>
                                <fieldset>
                                <legend> Enter individual member amount  </legend>
                                    <div class="cont-rgt-data">
                                        <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                                            <tr class="tdbrownheading">
                                                <td width="39%">Name</td>
                                                <td>Amount</td>
                                            </tr>
                                            <?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
                                            <tr class="tdbrown">
                                                <TD width="39%"><?php echo $arrayroles1['memberfirstname'];?></TD>
                                                <td><?php $a='amount'.$arrayroles1['member_id'];echo $this->recurringForm->$a; ?></TD>
                                            </tr>
                                            <?php }?>
                                        </table>
                                    </div>
                                </fieldset>
                            </TD>
                            </tr>
                            <?php } ?>
                            <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                                    <TR class="tdbrown">
                                        <TD width="40%">Amount<span class="reqMark">*</span></TD>
                                        <TD width="60%"><?php echo $this->depositamount;?></TD>
                                    </TR>
                                    <TR class="tdbrown1">
                                        <td width="20%">Transaction mode<span class="reqMark">*</span></td>
                                        <TD><?php echo $this->transactionModetype; ?></td>
                                    </TR>
                                    <?php if ($this->transactionMode!=1) { ?>
                                    <TR class="tdbrown1">
                                        <td width="20%">voucher/cheque/draft number<span class="reqMark">*</span></td>
                                        <TD><?php echo $this->paymenttype_details;?></td>
                                    </TR>
                                    <?php } ?>
<!--						<tr>
                                                        <td ><description</td>
                                                        <td ><?php echo $this->form1->transactiondescription;?></td>
                                                        <td ></td>
                                                </tr>-->
                                    <?php if($this->recurringForm->fine) { ?>
                                    <tr class="tdbrown1">
                                        <td width="20%">Fine R$</td>
                                        <TD><?php echo $this->fine; ?></TD>
                                    </TR>
                                    <?php } ?>
                            </table>
                                <table>
                                    <TR>
                                        <TD><?php echo $this->recurringForm->Submit;?></TD>
                                        <td><a href="<?php echo $this->baseUrl();?>">
                                        <input name="submit" type="submit"  value="back" tabindex="25"></a></TD>
                                    </TR>
                                </table>
                        </form>
                    </div>
                </fieldset>
        <?php } ?>
</div>
        