<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->




     <fieldset>
            <legend>Existing Sub Ledger</legend>
                <table id = "hor-minimalist-b">
                        <tr >
	                   <td width="40%"><b class="star">Ledger Sub Code</b></td>
	                   <td width="160%" colspan = "8"><b class="star">Gl Sub Code Header</b></td>
                        </tr>
			<?php foreach ($this->product as $product) { ?>
                        <tr class="tdbrown">
                            <td width="40%"> <?php echo $product["glsubcode"];?></a></td>
                            <td width="160%" colspan = "8"> <?php echo $product["subheader"];?></td>
                        </tr>
			<?php } ?>
               </table>
	    </fieldset>