
<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->  
<div id="searchDiv">
<fieldset>
    <legend><?php echo $this->translate('Search'); ?></td></legend>
            <form action="<?php echo $this->baseUrl();?>/sectors/index" method="POST">
                <table class="fieldsets"> 
                    <?php echo $this->form;?>
                </table>

                <div class="btnhouse">
                    <div class="ltbtns">
                        <input type = "Submit" name = "Search" id="Search" value = "Search"/>
                    </div>
                </div>
            </form>
</fieldset>
</div>
<?php  if((count($this->paginator) ==0) && ($this->search == true))  { ?>
<font color='RED'><?php echo $this->translate('Record not found try again'); ?>.</font>
<?php } ?>
 <?php if (count($this->paginator)!=0){ ?>
    <table id="hor-minimalist-b" summary="">
        <tr class="tdbrownheading">
            <th>Sector name</th>
            <th>Description</th>
            <th>Active</th>
        </tr>
            <?php foreach ($this->paginator as $product ){ ?>
    <tr>
 	  <td>
    <a href="<?php echo $this->baseUrl()."/sectors/index/sectorview/id/".$product['id']; ?>"><?php echo $this->escape($product['name']);?></a></td>
   
    <td><?php echo $this->escape($product['description']);?></td>
    <td><?php if($product['status'] == 1) echo "Yes"; else echo "No";?></div></td>

        <?php } ?></tr>
       

    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                    '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>

</table>
<?php } ?>
   

