 <!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!--> 
<table id="hor-minimalist-b">
    <tr>
        <th class = "firsttd"><?php echo $this->translate('Sector information'); ?></th>
        <th class = "secondtd"></th>
	<?php foreach($this->sector as $act) { }?>
	<th class="thirdtd"><a href="<?php echo $this->baseUrl()."/sectors/index/sectoredit/id/".$this->id; ?>">
			<img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th> 
    </tr>

        <?php foreach($this->sector as $act) {  ?>
	<tr>
            <td class = "firsttd"><?php echo $this->translate('Sector name'); ?></td>
            <td class = "secondtd"><?php echo $act['name']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
	<tr>
            <td class = "firsttd"><?php echo $this->translate('Description'); ?></td>
            <td class = "secondtd"><?php echo $act['description']; ?></td>
            <td class = "thirdtd"></td>
	</tr>
	<tr>
            <td class = "firsttd"><?php echo $this->translate('Active'); ?></td>
            <td class = "secondtd"><?php if($act['status']==1) echo "Yes"; else echo "No";?></td>
            <td class = "thirdtd"></td>
	</tr>
        <?php } ?>
       
	<tr>
            <td class = "firsttd"><a href="<?php echo $this->baseUrl(); ?>/sectors/index/">
                            <?php echo $this->form->Back;?></a></td>
            <td class = "secondtd"></td>
            <td class = "thirdtd"></td>
	</tr>
 </table>
   




