<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<?php if($this->savings) { ?><h5 align="right">From <?php echo "<font color='#039'>".$this->field1."</font>"; ?> </h5><h5 align="right"> To <?php echo "<font color='#039'>".$this->field2."</font>"; ?></h5>  <br>
<h5 style="text-align:right">* Amount in <font color="red">Rs</font></h5><div style="float:left;width:400px">
<fieldset>
    <legend>Receipt</legend>
            <?php 
              $amountCredit = 0.00;
              $amountDebit = 0.00;
              $openingamountCredit = 0.00;
              $openingamountDebit = 0.00;
              $i = 0;
              $j = 0;
              $countvalue1 =count($this->savingsCredit);
              $countvalue2 =count($this->savingsDebit);
              $count = $countvalue1>$countvalue2?$countvalue1:$countvalue2; 
            ?>
    <table id="hor-minimalist-b">
        <TR>
            <TH >Particulars</TH>
            <TH class = "label">Amount</TH>
        </TR>
        <?php foreach($this->savingsCredit as $savingsCredit) { $i++;?>
        <TR>

            <TD ><?php echo $savingsCredit->offerproductname ?></TD>
            <TD align = "right"><?php echo $savingsCredit->savingcredit; 
            $amountCredit = $amountCredit + $savingsCredit->savingcredit; ?></TD>
        </TR>
        <?php } ?>
        <!-- opening Balance  -->
        <?php
	for($j=$i;$j<=$count;$j++){ 
	if($j==$count){ ?>

            <?php foreach($this->openingsavingsCredit as $openingsavingsCredit) { ?>
            <TR>
                <TD ><B>Opening Balance</B></TD>
                <TD align = "right"><B><?php echo $openingsavingsCredit->openingBalance;
                $openingamountCredit = $openingamountCredit + $openingsavingsCredit->openingBalance; ?></B></TD>
            </TR>
            <?php } ?>
            <TR>
                <TD ><B>Total</B></TD>
                <?php if($openingamountCredit + $amountCredit != "0") { ?>
                <TD align = "right" ><B><?php echo sprintf("%4.2f", $openingamountCredit + $amountCredit); ?></B></TD>
                <?php } else { ?>
                <TD align = "right" ><B>----</B></TD>
                <?php } ?>
            </TR>
        <?php  } else {?>
	<tr>
		<td><?php echo "----";?></td>
		<td align = "right"><?php echo "----";?></td>
	</tr>
	<?php } }   $i=0;$j=0;?>

    </table>
</fieldset>
</div>
<div style="float:left;width:400px">
<fieldset>
    <legend>Payment</legend>
    <table id="hor-minimalist-b">
        <TR>
            <TH >Payment</TH>
            <TH class = "label">Amount</TH>
        </TR>
        <?php foreach($this->savingsDebit as $savingsDebit) { $i++; ?>
        <TR>

            <TD ><?php echo $savingsDebit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $savingsDebit->savingdebit; 
            $amountDebit = $amountDebit + $savingsDebit->savingdebit; ?></TD>
        </TR>
        <?php } ?>
        <!-- Closing Balance -->
		<?php
			for($j=$i;$j<=$count;$j++){ 
			 if($j==$count){ ?>
        <?php foreach($this->openingsavingsDebit as $openingsavingsDebit) { ?>
        <TR>
            <TD ><B>Closing Balance</B></TD>
            <TD align = "right"><B><?php echo $openingamountDebit = ($openingamountCredit + $amountCredit - $amountDebit); 
            //$openingamountDebit = $openingamountDebit + $openingsavingsDebit->closingBalance; ?></B></TD>
        </TR>
        <?php } ?>
        <TR>
             <TD ><b>Total</TD></TD>
             <?php if($openingamountDebit + $amountDebit != "0") { ?>
             <TD align = "right" ><B><?php echo sprintf("%4.2f", $openingamountDebit + $amountDebit); ?></B></TD>
             <?php } else { ?>
             <TD align = "right" ><B>----</B></TD>
             <?php } ?>
        </TR>
        			<?php  } else {?>
				<tr>
					<td><?php echo "----";?></td>
					<td align = "right"><?php echo "----";?></td>
				</tr>
		
			<?php } }  ?>
    </table>
</div>
</fieldset>
<form action="<?php echo $this->baseUrl();?>/reports/receiptspayments/pdftransaction" method="POST"
onClick="window.open('/ourbank/public/reports/receiptspayments/reportdisplay/file/ReceiptsPayments.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <input type="hidden" name="field1" value="<?php echo $this->field1; ?>">
            <input type="hidden" name="field2" value="<?php echo $this->field2;?>">
            <input type="submit" value="PDF" id="submit">
</form>
<?php } else {?>

<fieldset>
    <legend> search </legend>
        <div class="cont-rgt-data">
            <table id="hor-minimalist-b">
                <form action="<?php echo $this->baseUrl();?>/receiptpayment" method="POST">
                    <TR>
                            <TD >Date From</TD>
                            <TD ><?php echo $this->form->date1;?></TD>
                            <TD >Date To</TD>
                            <TD ><?php echo $this->form->date2;?></TD>
                    </TR>
                   

            </table>

				<input type="submit" name="Search" id="Submit" value="Search">			
                </form>

        </div>
</fieldset>


<?php } ?>

