<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


    <fieldset>
        <legend>Loan activitywise</legend>
	<table id="hor-minimalist-b">
		<th  width="40%">Member Name</th><th width="40%">No.of Loan A/c</th><th width="40%">Activity</th>
			<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $loandetails ): ?>
		<tr>
		<td><?php echo $this->escape($loandetails['member_name']); ?></td>
		<td><?php echo $this->escape($loandetails['Acc']);?></td>
		<td><?php echo $this->escape($loandetails['activity_name']);?></td>
			<?php endforeach; ?>
			<?php endif; ?>
		
		<tr>
			<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
						'/partials/my_pagination_control.phtml'); ?></div></td>
		</tr>
		</tr>
	</table>
<br>
   
</fieldset>
