<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div class="register">
	<div class="profile_tab"> 
<fieldset>
<legend>Grace Period VIEW</legend>
	<form action="<?php echo $this->baseUrl();?>/graceperiod/index/graceperiodadd" method="POST">
		<?php foreach($this->viewgracedetails as $viewgracedetails) { ?>
				<table style="float:left">
					<tr>
						<td colspan="5" class="td_border">Grace Period</td>
					</tr>
					<TR >
						<TD class="label" align="right" width="40%">Name<span class="reqMark">*</span></TD>
						<TD ><?php echo $viewgracedetails['graceperiod_name'];?><SPAN style="color:red"></SPAN></TD>
					</TR>
					<TR >
						<TD class="label" align="right" width="40%">Days<span class="reqMark">*</span></TD>
						<TD ><?php echo $viewgracedetails['days'];?><SPAN style="color:red"></SPAN></TD>
					</TR>
					<TR >
						<TD class="label" align="right" width="40%">Creditline Name<span class="reqMark">*</span></TD>
						<TD ><?php echo $viewgracedetails['creditline_name'];?><SPAN style="color:red"></SPAN></TD>
					</TR>
					<TR >
						<TD class="label" align="right" width="40%">Status<span class="reqMark">*</span></TD>
						<TD ><?php if($viewgracedetails['status']) echo "Active"; else echo "In Active";?><SPAN style="color:red"></SPAN></TD>
					</TR>
					<TR >
						<TD class="label" align="right" width="40%"></TD>
						<TD ><a href="<?php echo $this->baseUrl();?>/graceperiod/index"><input type="button" Value="Back"></TD>
					</TR>
				</table>
		<?php } ?>
	</form>
</fieldset>
