<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div style="width:480px;float:left"> 

<fieldset>
	<legend>Delete Category</legend>
	<div class="cont-rgt-data">
			<TABLE id="hor-minimalist-b">
        <?php foreach($this->productdetails as $category) {  ?>

				<TR>
					<TD>product name</TD>
					<TD></TD>
					<TD></TD>
					<TD><?php echo $category['name'];?></TD>
					<TD></TD>
				</TR>
				<TR>
					<TD>short name</TD>
					<TD></TD>
					<TD></TD>
					<TD><?php echo $category['shortname'];?></TD>
					<TD></TD>
				</TR>
<TR>
					<TD>product description</TD>
					<TD></TD>
					<TD></TD>
					<TD><?php echo $category['description'];?></TD>
					<TD></TD>
				</TR>
				<TR>
					<TD><a href="<?php echo $this->baseUrl(); ?>/management/category">
					<TD></TD>
					<TD></TD>
					<TD></TD>
					<TD></TD>
				</TR>
			</TABLE>
<?php } ?>

</fieldset>


<fieldset>
	<legend>confirm Delete</legend>
			<div class="cont-rgt-data">
				<form action="<?php echo $this->baseUrl();?>/product/index/productdelete/id/<?php echo $this->id; ?>" method="POST" name="joe" id="signupForm" class="cmxform">
				<table id="hor-minimalist-b" summary="Employee Pay Sheet">
					<TR>
						<TD  width="35%" align="right" ><label>Remarks<span class="reqMark">*</span></label></TD>
						<TD  width="65%"  align="left" ><?php echo $this->deleteform->remarks;?></TD>
					</TR>
				</table>

													<input type="submit" name="DELETE" id="Submit" value="DELETE">			

						<input name="submit" type="submit"  value="No" ></a></TD>
				</form>
			
</fieldset>
		</div>