<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script>
	function getXMLHTTP() {
		var xmlhttp=false;	
		try{
			xmlhttp=new XMLHttpRequest();
		}
		catch(e)	{		
			try{			
				xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
			}
			catch(e){
				try{
				xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
				}
				catch(e1){
					xmlhttp=false;
				}
			}
		}
		return xmlhttp;
	}

	function getGroups(bank_id,path) {	
		
		var strURL=path+"/meetingreport/index/fetchgroups?bank_id="+bank_id;
		//alert(strURL);
		var req = getXMLHTTP();
		
			req.onreadystatechange = function() {
				if (req.readyState == 4) {
					// only if "OK"
					if (req.status == 200) {
						document.getElementById('groupDiv').innerHTML=req.responseText;
					}
					 else {
						alert("There was a problem while using XMLHTTP:\n" + req.statusText);
					}
				}				
			}			
			req.open("GET", strURL, true);
			req.send(null);
		}
		
</script>
 




<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate("Search"); ?></legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/meetingreport/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label"><?php echo $this->translate("Bank name:"); ?></td>
                                    <td ><?php echo $this->form->field1;?></td>
                                    <td class="label"><?php echo $this->translate("Group name:"); ?></td>
                                    <td ><div id="groupDiv"><?php echo $this->form->field2;?></div></td>
                                </tr>

                                <tr>
                                    <td class="label"><?php echo $this->translate("Meeting day:"); ?></td>
                                    <td ><?php echo $this->form->field3;?></td>

                                </tr>
                                <tr>
                                    <td colspan="4" align="center"><?php echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 


<fieldset>
        <legend><?php echo $this->translate("Holiday"); ?></legend>
<table id="hor-minimalist-b">
    <tr>
        <th><?php echo $this->translate("Bank Name"); ?></th>
	<th><?php echo $this->translate("Group Name"); ?></th>
        <th><?php echo $this->translate("Meeting Name"); ?></th>
	<th><?php echo $this->translate("Meeting Day"); ?></th>
	<th><?php echo $this->translate("Meeting Time"); ?></th>
	<th><?php echo $this->translate("Meeting Place"); ?></th>
       
    </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $meeting): ?>
    <tr>
        
	<td><?php echo $this->escape($meeting['bankname']); ?></td>
	<td><?php echo $this->escape($meeting['meetingname']);?></td> 
	<td><?php echo $this->escape($meeting['name']);?></td>
	<td><?php echo $this->escape($meeting['day']);?></td>
	<td><?php echo $this->escape($meeting['time']);?></td>
	<td><?php echo $this->escape($meeting['place']);?></td>
	
                <?php endforeach; ?>
                <?php endif; ?>
    </tr>
    <tr>
		<td colspan="6" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
						'/partials/my_pagination_control.phtml'); ?></div></td>
		</tr>
</table>

</fieldset>


</form>
<form action="<?php echo $this->baseUrl();?>/meetingreport/index/pdfgeneration/field1/<?php echo $this->institute_bank_id;?>/field2/<?php echo $this->group_id;?>/field3/<?php echo $this->fromDate;?>/field4/<?php echo $this->toDate;?>" method="POST"
onClick="window.open('<?php echo $this->baseUrl();?>/meetingreport/index/reportdisplay/file/meeting<?php echo date('Y-m-d');?>.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">

           <BR> <input type="submit" value="<?php echo $this->translate('PDF'); ?>" id="submit">
</form>
