<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


            <div id="container-1">
             <fieldset>
	           <legend><?php echo $this->translate("Add Individual Information"); ?></legend>
                   <div class="register">
	               <div class="profile_tab">
                       <table id="hor-minimalist-b">

                          <tr><td><?php echo $this->translate("Member Details :"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/membername/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                	 <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='middlename') {
                            if($selectplugin['staus']==1) {
                            ?>
                           <tr><td><?php echo $this->translate("Middle and Last Name:"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/middlename/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
			   <?php }}} ?>

                        <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='address') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Member address:"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/address/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			 <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='contact') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Family Information:"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/contactdetails/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			  <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='website') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Website and Email:"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/email/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

                         <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='personal') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Member Personal Information"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/personal/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			  <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='photo') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Add Photograph"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/photo/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			 <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='asset') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Asset Details"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/asset/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			 <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='asset') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Family Details"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/familydetails/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			 <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='asset') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Family Health Details"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/asset/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			 <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='asset') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Family Economic details"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/asset/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			 <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='asset') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td><?php echo $this->translate("Family Education details"); ?></td>
                         <TD class="label" align="right"><?php echo $this->translate("Click to Add :"); ?></TD>
				<TD><a href="<?php echo $this->baseUrl();?>/asset/index"><?php echo $this->translate("ADD"); ?></a></TD>
                        </tr>
                         <?php }}} ?>

			<tr>
				<TD><a href="<?php echo $this->baseUrl();?>/membership/individual"><input type="submit" name="back" value="Back"></a></TD>
			</tr>
                         </table>
                   </div>
	         </div>
            </fieldset>
        </div>

 
