<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script type="text/javascript" language="JavaScript1.3" >
function getXMLHTTP() {
    var xmlhttp=false;	
        try{
            xmlhttp=new XMLHttpRequest();
        }
        catch(e) {
            try {	
                xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
            }
            catch(e){
                try {
                    xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
                }
                catch(e1){
                    xmlhttp=false;
                }
            }
        }
        return xmlhttp;
    }
function getInterests(countryId) {
    var productId = eval(document.form1.productId.value);
    var strURL="/ourbank/public/accounting/accounting/interests?country="+countryId+"&productId="+productId;
    var req = getXMLHTTP();
        if (req) {
            req.onreadystatechange = function() {
            if (req.readyState == 4) {
                if (req.status == 200) {
                    document.getElementById('statediv').innerHTML=req.responseText;
                } else {
                    alert("There was a problem while using XMLHTTP:\n" + req.statusText);
                  }
            }
        }
        req.open("GET", strURL, true);
        req.send(null);
        }
        var perioddescription=$('#perioddescription').val();
        if(perioddescription!='') {
            $('#errorspan').show();
        } else {
            $('#errorspan').hide();
          }
}
function calculateTotalAmount() {
    var amount = eval(document.form1.amount.value);
    var feeTotal = eval(document.form1.feeTotal.value);
    var tAmount =  (amount + feeTotal);
    document.form1.tAmount.value = tAmount;

}
function calculateMatureAmount() {
    var numb1 = document.form1.amount.value;
    var interest = (document.form1.amount.value * document.form1.period.value* document.form1.interest.value) / (100 * 12);
    var tAmount =  eval(numb1) + eval(interest);
    document.form1.matureamount.value = tAmount;
}
</script>
<body>
<?php if(!$this->Submit) { ?>
<div style="float:right;width:350px">
    <fieldset>
        <legend>New Fixed Account</legend>
            <form name="form1" action="<?php echo $this->baseUrl();?>/accounting/accounting/fixed" method="POST">
                <table id="hor-minimalist-b">
                    <TR>
                        <TD>Date<B style="color:red"> yyyy-mm-dd</B></TD>
                        <TD><?php echo $this->fixedForm->date1;?></TD>
                        <td><?php echo $this->fixedForm->memberTypeIdv;?></td>
                    </TR>
                    <TR>
                        <TD>Period</TD>
                        <TD><?php echo $this->fixedForm->period;?></TD>
                    </TR>
                    <TR>
                        <TD>Interest</TD>
                        <TD><div id="statediv"><?php echo $this->fixedForm->interest;?></TD>
                    </TR>
                    <TR>
                        <TD>Fixed Amount</TD>
                        <TD><?php echo $this->fixedForm->amount;echo $this->fixedForm->productId;
                                  echo $this->fixedForm->memberId;echo $this->fixedForm->typeId;?></TD>
                    </TR>
                    <?php if($this->Savingfee) { ?>
                    <TR>
                        <TD>Fee</TD>
                        <TD><?php foreach($this->Savingfee as $fee ) { ?> 
                        <input type = text name = "fee2" value = "<?php echo $fee->feevalue;?>" 
                               readonly = "true" class="txt_put">
                        <? $this->feeTotal = $this->feeTotal +  $fee->feevalue; ?>
                        <?php } ?>
                        <input type = "hidden" name = "feeTotal" id = "feeTotal" 
                               value = "<?php echo $this->feeTotal;?>" readonly = "" class="txt_put"></TD>
                        <td></td>
                    </TR>
                    <input type = "hidden" name= "mindeposit" value="<?php echo $this->minimumDepositAmount;?>">
                    <TR>
                        <TD>Paying Amount </TD>
                         <td><?php echo $this->fixedForm->tAmount;?></td>
                        <td></td>
                    </TR>
                    <TR>
                        <TD>Mature Amount </TD>
                        <TD ><?php echo $this->fixedForm->matureamount;?></TD>
                        <td></td>
                    </TR>
                    <?php } ?>
                   <?php if ($this->membertype_ID == 3 ) { ?>
                    <TR>
                        <TD>Members</TD>
                        <TD><?php echo $this->recuringForm->memberfirstname;?><br>
                            <?php echo $this->error1; ?></TD>
                    </TR><? } ?>
                </table>
                <br>
                <table>
                    <TR>
                        <td><?php echo $this->fixedForm->Submit; ?></td>
                        <td></td>
                        <td></td>
                        <TD><a href="<?php echo $this->baseUrl();?>/accounting/accounting/member/memberId/<?php echo $this->memberId;?>/Type/<?php echo $this->Type ?>">
                        <?php echo $this->fixedForm->Back;?></a></TD>
                </TR>
        </table>
    </form>
</fieldset>
</div>
<?php } ?>

<?php if($this->Submit) { ?>
<div style="float:right;width:350px">
    <fieldset>
        <legend>New Fixed Account</legend>
            <form name="form1" action="<?php echo $this->baseUrl();?>/accounting/accounting/fixed" method="POST">
                <table id="hor-minimalist-b">
                    <TR>
                        <TD>Date<B style="color:red"> yyyy-mm-dd</B></TD>
                        <TD><?php echo $this->date1;?>
                        <input type = 'hidden' name = 'date1' value = '<?php echo $this->date1;?>'></TD>
                        <td><?php echo $this->fixedForm->memberTypeIdv;?></td>
                    </TR>
                    <TR>
                        <TD>Period</TD>
                        <TD><?php echo $this->period;?>
                            <input type = 'hidden' name = 'period' value = '<?php echo $this->period;?>'></TD>
                    </TR>
                    <TR>
                        <TD>Interest</TD>
                        <TD><?php echo $this->interest;?>
                        <input type = 'hidden' name = 'interest' value = '<?php echo $this->interest;?>'></TD>
                    </TR>
                    <TR>
                        <TD>Fixed Amount</TD>
                        <TD><?php echo $this->amount;
                                  echo $this->fixedForm->productId;
                                  echo $this->fixedForm->memberId;
                                  echo $this->fixedForm->typeId;?>
                            <input type = 'hidden' name = 'amount' value = '<?php echo $this->amount;?>'></TD>
                    </TR>
                    <?php if($this->Savingfee) { ?>
                    <TR>
                        <TD> Fee </TD>
                        <TD><?php foreach($this->Savingfee as $fee ) { ?> 
                        <input type = text name = "fee2" value = "<?php echo $fee->feevalue;?>" 
                               readonly = "true" class="txt_put">
                        <? $this->feeTotal = $this->feeTotal +  $fee->feevalue; ?>
                        <?php } ?>
                        <input type = "hidden" name = "feeTotal" id = "feeTotal" 
                               value = "<?php echo $this->feeTotal;?>" readonly = "" class="txt_put"></TD>
                        <td></td>
                    </TR>
                    <input type = "hidden" name= "mindeposit" value="<?php echo $this->minimumDepositAmount;?>">
                    <TR>
                        <TD>Paying Amount </TD>
                         <td><?php echo $this->tAmount;?>
                             <input type = 'hidden' name = 'tAmount' value = '<?php echo $this->tAmount;?>'></td>
                        <td></td>
                    </TR>
                    <TR>
                        <TD>Mature Amount </TD>
                        <TD><?php echo $this->matureamount;?>
                             <input type = 'hidden' name = 'matureamount' value = '<?php echo $this->matureamount;?>'></TD>
                        <td></td>
                    </TR>
                    <?php } ?>


                   <?php if ($this->membertype_ID == 3 ) { ?>
                    <TR>
                        <TD>Members</TD>
                        <?php foreach($this->memberfirstname as $memberfirstname) { ?>
                        <TD><?php echo $memberfirstname;?><br>
                        <input type = 'hidden' name = 'memberfirstname[]' value= '<?php echo $memberfirstname;?>'>
                            <?php } ?>
                            <?php echo $this->error1; ?></TD>
                    </TR><? } ?>
                </table>
                <br>
                <table>
                    <TR>
                        <td><?php echo $this->fixedForm->Yes; ?></td>
                        <td></td>
                        <td></td>
                        <TD><a href="<?php echo $this->baseUrl();?>/accounting/accounting/fixed/memberId/<?php echo $this->memberId;?>/productId/<?php echo $this->productId;?>">
                            <?php echo $this->fixedForm->Back;?></a></TD>
</TR>
</table>
</form>
</fieldset>
</div>
<?php } ?>
</body>