<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<form action="<?php echo $this->baseUrl();?>/reports/generalledger/pdfdisplay" method="POST"
onClick="window.open('/ourbank/public/reports/generalledger/reportdisplay/file/GL.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
           

            <input type="submit" value="PDF" id="submit">

</form>