<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>groupSearch</legend>
            <div class="search">
                <table width="100%">
                    <form action="<?php echo $this->baseUrl();?>/membership/group" method="POST">
                    <TR>
                        <td class="label">Group Code</td>
                        <td><?php  echo $this->form->field2;?></td>
                        <td class="label">Group Name</td>
                        <td><?php  echo $this->form->field3;?></td>
                   </TR>
                   <TR>
                       <td class="label">Group Branch</td>
                       <td><?php  echo $this->form->field1;?></td>
                       <td class="label">Group Location</td>
                       <td><?php  echo $this->form->field4;?></td>
                  </TR>
                  <TR>
                       <td></td>
                       <td></td>
                       <td align="center"><? echo $this->form->Search;?></td>
                       <td></td>
                 </TR>
                     </form>
                </table>
             </div>
    </fieldset>
</div>
<br>

<fieldset>
    <legend>group</legend>

    <table id="hor-minimalist-b">
                <TR>
	                <TH width="20%">Group</TH>
                        <TH width="20%">Group Name</TH>
                        <TH width="20%">Group Branch</TH>
                        <TH width="20%">Group Location</TH>
                        <TH width="7%">Edit</TH>
                        <TH width="7%">Delete</TH>
               </TR>

               <?php foreach($this->paginator as $member) : ?>
                <TR class="tdbrown">
                        <td><a href="<?php echo $this->baseUrl(); ?>/membership/group/viewgroup/groupname_id/<?php echo $member['groupname_id'];?>">
                                    <?php echo $this->escape($member['membercode']);?></a></td>
                        <td><?php echo $this->escape($member['groupname']);?></td>
                        <td><?php echo $this->escape($member['bankname']);?></td>
                        <td><?php echo $this->escape($member['groupaddress_location']);?></td>
                        <td><a href="<?php echo $this->baseUrl(); ?>/membership/group/editgroup/groupname_id/<?php echo $member['groupname_id'];?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></td>
        
                        <td width="5%"><a href="<?php echo $this->baseUrl();?>/membership/group/deletegroup/groupname_id/<?php echo $member['groupname_id'];?>">
                                                <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
                 
                        <?php endforeach; ?>
                
        
                </TR>
		<TR>
     		            <tr>
                <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                            '/partials/my_pagination_control.phtml'); ?></div></td>
            </tr>
	</TABLE>
<br>			
	<TABLE width="100%">
                

		<TR>
                     <TD height="30"> <a href="<?php echo $this->baseUrl(); ?>/membership/group/addgroup">
			<input name="submit" type="submit" class="NormalBtn" value= "New Group"></a></TD>   
                        
                </TR>
        </TABLE>

</fieldset>
