<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

 
<?php if($this->savings) {

 $totalCashCredit=0;$totalCashDebit=0;	$totalTrnsferCashcredit=0;$totalTrnsferCashDebit=0; ?>

<h5 style="text-align:right;"><? echo $this->resultshow; ?></h5>
<h5 style="text-align:right"> <font color="red">*</font> Amount in <font color="red">Rs</font></h5>
<div style="float: left; width: 370px">
    <h5>Credit</h5>
            <table id="hor-minimalist-s" border=2>
            <TR>
            <TH align="center"><?php echo $this->translate("Particulars"); ?></TH>
            <TH align="center"><?php echo $this->translate("Gl No."); ?></TH>
            <TH class="label"><?php echo $this->translate("Cash"); ?></TH>
            <TH class="label"><?php echo $this->translate("Transfer"); ?></TH>
            <TH class="label"><?php echo $this->translate("Total"); ?></TH>
                </TR>
            <? $transferFlagCr = 0; $matchedProductsCr=array();$unmatchedProductsCr=array();
            if($this->savingsCredit) {
            foreach($this->savingsCredit as $savingsCredit) { ?>
                <TR>
                <TD><? echo $savingsCredit['name']; ?></TD>
                <TD><? echo $savingsCredit['glcode']; ?></TD>
                <TD class="label"><?php echo sprintf("%4.2f", $savingsCredit['amount_to_bank'])?></TD>
                <? if($this->TransfersavingsCredit) { $transferFlagCr=1;$flag1=0;

                    foreach($this->TransfersavingsCredit as $tsc) {
                        if($savingsCredit['name']==$tsc['name']) {
                            echo "<TD class=label>".sprintf("%4.2f", $tsc['amount_to_bank'])."</TD><td class=label>".sprintf("%4.2f", ($savingsCredit['amount_to_bank']+$tsc['amount_to_bank']))."</td></TR>";$flag1=1;
                            $totalTrnsferCashcredit+= $tsc['amount_to_bank'];
                            $matchedProductsCr[]=$tsc['name'];
                        }
                        else{
                                $unmatchedProductsCr[]=$tsc['name'];
                        }
                    }
                    if($flag1==0) {
                        echo "<TD class=label>0.00</TD><TD class=label>".sprintf("%4.2f", $savingsCredit['amount_to_bank'])."</TD></TR>";	
                    }

                }
                else {
                        echo "<TD class=label>0.00</TD><TD class=label>".sprintf("%4.2f", $savingsCredit['amount_to_bank'])."</TD></TR>";
                }
                ?>
                <? $totalCashCredit+=$savingsCredit['amount_to_bank'];
            }
            }
            $unmatchedProductsCr=array_diff($unmatchedProductsCr,$matchedProductsCr);
            $unmatchedProductsCr=array_values($unmatchedProductsCr);
            $unmatchedProductsCr = array_unique($unmatchedProductsCr);

            if(count($this->TransfersavingsCredit)) {
                    for($k=0;$k<count($this->TransfersavingsCredit);$k++) {
                            if($k>count($matchedProductsCr)-1) {
                                    $matchedProductsCr[$k]='a';
                            }
                            if($k>count($unmatchedProductsCr)-1) {
                                    $unmatchedProductsCr[$k]='a';
                            }
                    }
            }

            if($transferFlagCr==0) {
            foreach($this->TransfersavingsCredit as $tsc) { ?>
                    <TR><TD><? echo $tsc['name']; ?></TD>
                    <TD><? echo $tsc['glcode']; ?></TD>
                    <TD></TD>
                    <TD class="label"><? echo sprintf("%4.2f", $tsc['amount_to_bank']);
                        $totalTrnsferCashcredit+= $tsc['amount_to_bank'];?></TD>
                    <TD class="label"><? echo sprintf("%4.2f", $tsc['amount_to_bank']); ?></TD>	
                    </TR>
                            <?
                    }
            } else {
                foreach($this->TransfersavingsCredit as $tsc) {
                    if($unmatchedProductsCr){
                        for($j=0;$j<count($this->TransfersavingsCredit);$j++) {
                            if($tsc['name']==$unmatchedProductsCr[$j] && $unmatchedProductsCr[$j]!=$matchedProductsCr[$j]) {  ?>
                                <TR>
                                    <TD><? echo $tsc['name']; ?></TD>
                                    <TD><? echo $tsc['glcode']; ?></TD>
                                    <TD></TD>
                                    <TD class="label"><? echo sprintf("%4.2f", $tsc['amount_to_bank']); 
                                    $totalTrnsferCashcredit+= $tsc['amount_to_bank'];?></TD>	<td class="label"><? echo sprintf("%4.2f", $tsc['amount_to_bank']);?></td>
                                </TR>
                            <? }
                        }
                    }
                }
            }
            ?>
            
        <TR><TD></TD><TD><b><?php echo $this->translate("Total"); ?></b></TD><TD class="label"><b><? echo sprintf("%4.2f", $totalCashCredit); ?></b></TD><TD></TD><td></td></TR>
        <TR><TD></TD><TD><?php echo $this->translate("Opening balance"); ?></TD><TD class="label"><b><? if($this->openingbalance) echo sprintf("%4.2f", $this->openingbalance); else echo "0.00"; ?></b></TD><TD></TD><td></td></TR>
        <TR><TD></TD><TD><b><?php echo $this->translate("Total"); ?></b></TD><TD class="label"><b><?  $CreditTotal=$totalCashCredit+$this->openingbalance;echo sprintf("%4.2f", $CreditTotal); ?> </b></TD><TD class="label"> <b><? echo sprintf("%4.2f", $totalTrnsferCashcredit);?></b></TD><TD class="label"> <b><? echo sprintf("%4.2f", $totalTrnsferCashcredit);?></b></TD></TR>

        </table>

    </div>

    <div style="float: right; width: 370px">
        <h5>Debit</h5>
        <table  id="hor-minimalist-s">
            <TH align="center"><?php echo $this->translate("Particulars"); ?></TH>
            <TH align="center"><?php echo $this->translate("Gl No."); ?></TH>
            <TH class="label"><?php echo $this->translate("Cash"); ?></TH>
            <TH class="label"><?php echo $this->translate("Transfer"); ?></TH>
            <TH class="label"><?php echo $this->translate("Total"); ?></TH>

        </TR>
        <? $transferFlagDr = 0; $matchedProductsDr=array(); $unmatchedProductsDr=array();if($this->savingsDebit) {
        foreach($this->savingsDebit as $savingsDebit) { ?>
            <TR>
            <TD><? echo $savingsDebit['name']; ?></TD>
            <TD><? echo $savingsDebit['glcode']; ?></TD>
            <TD class="label"><? echo $savingsDebit['amount_from_bank']; ?></TD>
            <? if($this->TransfersavingsDebit) { $transferFlagDr=1;$flag2=0;
                foreach($this->TransfersavingsDebit as $tsd) {
                    if($savingsDebit['name']==$tsd['name']) {
                        echo "<TD class=label>".$tsd['amount_from_bank']."</TD><td class=label>".sprintf("%4.2f", ($savingsDebit['amount_from_bank']+$tsd['amount_from_bank']))."</td></TR>";$flag2=1;
                        $totalTrnsferCashDebit+=$tsd['amount_from_bank'];
                        $matchedProductsDr[]=$tsd['name'];
                    } else{
                        $unmatchedProductsDr[]=$tsd['name'];
                    }
                }
            if($flag2==0){
                    echo "<TD class=label>0.00</TD><TD class=label>".sprintf("%4.2f", $savingsDebit['amount_from_bank'])."</TD></TR>";
            }
            } else {
                    echo "<TD class=label>0.00</TD><TD class=label>".sprintf("%4.2f", $savingsDebit['amount_from_bank'])."</TD></TR>";
            }
            ?>
            <? $totalCashDebit+=$savingsDebit['amount_from_bank'];
        }
    }
    $unmatchedProductsDr=array_diff($unmatchedProductsDr,$matchedProductsDr);
    $unmatchedProductsDr=array_values($unmatchedProductsDr);
    $unmatchedProductsDr = array_unique($unmatchedProductsDr);

        if(count($this->TransfersavingsDebit))
        {
            for($l=0;$l<count($this->TransfersavingsDebit);$l++) {
                if($l>(count($matchedProductsDr)-1)) {
                        $matchedProductsDr[$l]='a';
                }
                if($l>(count($unmatchedProductsDr)-1)) {
                        $unmatchedProductsDr[$l]='a';
                }
            }
        }

        if($transferFlagDr==0){
            foreach($this->TransfersavingsDebit as $tsd) { ?>
                <TR><TD><? echo $tsd['name']; ?></TD>
                <TD><? echo $tsd['glcode']; ?></TD>
                <TD></TD>
                <TD class="label"><? echo $tsd['amount_from_bank']; 
                        $totalTrnsferCashDebit+=$tsd['amount_from_bank'];?></TD>	
                <td><? echo $tsd['amount_from_bank']; ?></td>
                </TR>
            <? }
        } else { $i=0;
            foreach($this->TransfersavingsDebit as $tsd) {
                if($unmatchedProductsDr){
                    if($tsd['name']==$unmatchedProductsDr[$i] && $unmatchedProductsDr[$i]!=$matchedProductsDr[$i]) {  ?>
                        <TR>
                        <TD><? echo $tsd['name']; ?></TD>
                        <TD><? echo $tsd['glcode']; ?></TD>
                        <TD></TD>
                        <TD class="label"><? echo $tsd['amount_from_bank']; 
                                $totalTrnsferCashDebit+= $tsd['amount_from_bank'];?></TD>	
                        <td class="label"><? echo $tsd['amount_from_bank']; ?></td>
                        </TR>
                    <?  }
                }$i++;
            }
        }

        ?>
            <TR> <TD></TD> <TD><b><?php echo $this->translate("Total"); ?></b></TD> <TD class="label"><b><? echo sprintf("%4.2f", $totalCashDebit); ?> </b></TD> <TD></TD><TD></TD></TR>
            <TR> <TD></TD> <TD><?php echo $this->translate("Closing balance"); ?></TD> <TD class="label"><b><?  $closingbalance=$CreditTotal-$totalCashDebit; echo sprintf("%4.2f", $closingbalance); ?></b></TD> <TD></TD> <TD></TD></TR>
            <TR> <TD></TD> <TD><b><?php echo $this->translate("Total"); ?></b></TD> <TD class="label"><b><?  $TotalDebit=$closingbalance+$totalCashDebit; echo sprintf("%4.2f", $TotalDebit);?> </b></TD> <TD class="label"><b><? echo sprintf("%4.2f", $totalTrnsferCashDebit); ?></b></TD> <TD class="label"><b><? echo sprintf("%4.2f", $totalTrnsferCashDebit); ?></b></TD></TR>
        </table>
    </div>
<div style="float: left; width: 800px">
    <form action="<?php echo $this->baseUrl();?>/daybook/index/pdftransaction/field1/<?php echo $this->fromdate;?>" method="POST" onClick="window.open('<?php echo $this->baseUrl();?>/daybook/index/reportdisplay/file/daybook-<? echo date('Y-m-d');?>.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
           <BR> <input type="submit" value="PDF" id="submit">
    </form>
</div>

<?php  } else { ?>

    <fieldset>
    <legend> Search </legend>
        <div class="cont-rgt-data">
            <table id="hor-minimalist-b">
                <form action="<?php echo $this->baseUrl();?>/daybook/index" method="POST">
                <TR>
                    <TD ><?php echo $this->translate('As of date'); ?></td>
                    <TD ><?php echo $this->form->datefrom;?></TD>
                    <TD ><input type="submit" name="Search" value="Search"/></TD>
                </TR>
                </form>
            </table>
        <? echo $this->errormsg; ?>
        </div>
    </fieldset>
<?php } ?>
