<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div class="register">
	<div class="profile_tab"> 
<fieldset>
<legend>Website And Email Details</legend>
		<table style="float:left">
			<TR >
				<TD class="label" align="right" width="40%">Website:</TD>
				<TD ><?php echo $this->form->website;?></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Email</TD>
				<TD ><?php echo $this->form->email;?></TD>
			</TR>
			
			<TR >
				<TD class="label" align="right" width="40%"><a href="<?php echo $this->baseUrl();?>/individualcommon/index"><?php echo $this->form->Back;?></a></TD>
				<TD ><?php echo $this->form->Submit;?></TD>
			</TR>
		</table>
</fieldset>
