<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
	<legend>Creditlines edit</legend>
	<div class="register">
		<div class="profile_tab">
			<form action="<?php echo $this->baseUrl();?>/management/creditline/creditlineedit" method="POST" name="joe" id="signupForm" class="cmxform">
				<div style="display:none">
					<?php echo $this->form->creditline_id;?>
					<?php echo $this->form->institution_id;?>
				</div>
				<table style="float:left">
					<TR >
						<TD class="txt_rgt" align="right">Institution Name<span class="reqMark">*</span></TD>
						<TD ><?php echo $this->form->institutionnames;?></TD>
					</TR>
					<TR >
						<TD class="txt_rgt" align="right">Institution Amount R$</TD>
						<TD ><?php echo $this->form->instituteamount;?></TD>
					</TR>
					<TR >
						<TD class="txt_rgt" align="right">Maximum creditline Amount R$</TD>
						<TD ><?php echo $this->form->maxcreditlinelimit;?></TD>
					</TR>
					<TR >
						<TD class="txt_rgt" align="right">creditline Name<span class="reqMark">*</span></TD>
						<TD ><?php echo $this->form->creditlinename;?></TD>
					</TR> 

					<TR >
						<TD class="txt_rgt" align="right">creditline ShortName<span class="reqMark">*</span></TD>
						<TD><?php echo $this->form->creditline_shortname;?></TD>
					</TR>
					<TR >
						<TD class="txt_rgt" align="right">creditline amount R$:<span class="reqMark">*</span></TD>
						<TD ><?php echo $this->form->creditlineamount;?></TD>
					</TR>
					<TR >
						<TD class="txt_rgt" align="right">creditline interest %<span class="reqMark">*</span></TD>
						<TD><?php echo $this->form->creditlineinterest;?></TD>
					</TR>
					<TR >
						<TD class="txt_rgt" align="right">creditline from<span class="reqMark">*</span></TD>
						<TD><?php echo $this->form->creditline_beginingdate;?></TD>
					</TR>
					<TR >
						<TD class="txt_rgt" align="right">creditline to<span class="reqMark">*</span></TD>
						<TD><?php echo $this->form->creditline_closingdate;?></TD>
					</TR>
					<tr>
						<td align="right"><?php echo $this->form->Submit;?></td>
						<td align="right"><a href="<?php echo $this->baseUrl(); ?>/management/creditline"><input name="submit" type="submit" class="officebutton" value="Back"></a></td>



					</tr>
					<CENTER style="color:red"><?php echo $this->updateerror; ?></CENTER>
					<CENTER style="color:red"><?php echo $this->institution; ?></CENTER>
					<CENTER style="color:red"><?php echo $this->totalremaininginstitutionamount; ?></CENTER>
				</table>
			</form>
		</div>
	</div>
</fieldset>

