<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

    <fieldset>
        <legend>Search account</legend>
        <form action="<?php echo $this->baseUrl();?>/loandisbursment/index" method="POST">
            <table class="fieldsets">
                <tr>
                    <td><label for="fld1" class="mand">Account number/Name</label></td>
                    <td><?php echo $this->form->member_id;?></td>
                </tr>
            </table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Search;?>
                </div>
            </div>
        </form>
    </fieldset>

<?php if($this->accounts) { ?>
	<table id="hor-minimalist-b">
		<tr>
			<Th>Account number</Th>
			<Th>Name/Group name</th>
			<Th>Activity name</th>
			<Th>Type</th>
			<Th></th>
		</tr>
		<?php foreach($this->accounts as $account) : ?>
		<tr>
			<td><a href="<?php echo $this->baseUrl();?>/loandisbursment/index/disbursment/accountNumber/<?php echo $account['account_number'];?>"><?php echo $account['account_number'];?></a></td>
			<td><?php  echo $account['Name'];?></td>
			<td><?php  echo $account['activity_name'];?></td>
			<td><?php if ($account['member_type']==4) { 
				    echo $account['membertype']; 
			         } else {
				    echo "-"; 
			         } ?>
			</td>
			<td><?php if($account['member_type']==3) { 
				 echo $account['membertype']; 
				} else {
				    echo "-";
				}?>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
<?php }?>