<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/category/index/categoryedit/id/<?php echo $this->id; ?>" method="POST">
 	<div id="container-1">
		<div class="profile_tab">

			<fieldset>
				<legend>edit category Information</legend>
					<table class="fieldsets">	
						<TR>
							<TD colspan="2" align="right"><a href="<?php echo $this->baseUrl();?>/category/index/categorydelete/id/<?php echo $this->id; ?>" method="POST"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></TD>
						</TR>
						<?php echo $this->form;?>


 					</table>
						<div class="btnhouse">
							<div class="ltbtns">
 								<input type="submit" name="Update" id="Submit" value="Update">                 
							</div>
								<div class="rtbtns">
								<a href="<?php echo $this->baseUrl();?>/fee"><?php echo $this->form->Back;?></a>
								</div>
						</div>
			</fieldset>
		</div>
	</div>
</form>