<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/outstanding" method="POST">  
	<fieldset>
		<legend><?php echo $this->translate("Search"); ?></legend>

			<TABLE width="100%">
				<tr>
					  <Td class="label"><?php echo $this->translate("Branch :"); ?></td>
                                        <td><?php  echo $this->form->bank;?></td>
                                       
					<td class="label"><?php echo $this->translate("Activity :"); ?></td>
					<td><?php  echo $this->form->activity;?></td>
				</tr>
				<tr>
					  <Td class="label"><?php echo $this->translate("Credit line :"); ?></td>
                                        <td><?php  echo $this->form->creditline;?></td>
					<td class="label"><?php echo $this->translate("Month and year:"); ?></td>
					<td><?php  echo $this->form->month." -"; echo $this->form->year; ?></td>
				</tr>	
                                <tr>
					<td colspan="4" align="center"><? echo $this->form->Search;?></td>

				</tr>
                                <tr><div><?php 
                                               echo $this->dateerr;
                                         ?></div></tr>
			</form>
   			</TABLE>
		
 	</fieldset> 
</form>
<?php if($this->clientView){ ?>
	    <table id="hor-minimalist-b" >
		<tr><td><?php echo $this->translate("Bank Name:"); ?></td><?php if(!$this->bankname) { ?><td>All Banks</td> <? } else { ?><td><?php echo $this->bankname; } ?></td></tr>
		<tr><td><?php echo $this->translate("Activity Name:"); ?></td><?php if(!$this->activityname) { ?><td>All Activity</td> <? } else { ?><td><?php echo $this->activityname; } ?></td></tr>
		<tr><td><?php echo $this->translate("Credit line  Name:"); ?></td><?php if(!$this->creditid) { ?><td>All Credit line</td> <? } else { ?><td><?php echo $this->creditname; } ?></td></tr>
                <tr><td>Month and year</td><td><?php echo $this->month."-".$this->year; ?></td></tr>
            	</table>
            <TABLE id="hor-minimalist-b" >
		<tr>
	            <td id="reportth"><?php echo $this->translate("Name"); ?></td>
                    <td id="reportth"><?php echo $this->translate("Account Number"); ?></td>
                    <td align="right" id="reportth"><?php echo $this->translate("Loan Amount-R$"); ?></td>
	            <td align="right" id="reportth"><?php echo $this->translate("Outstanding Balance-R$"); ?></td>
	        </tr>
<?php
$outstandingtotal = "0";
$loantotal = "0";
 foreach($this->clientView as $outstanding) {
$outstandingtotal += $outstanding['SUM(e.accountinstallment_amount)'];
$loantotal += $outstanding['loan_amount'];
?>
		<tr>
	            <td><?php echo $outstanding['member_name']; ?></td>
                    <td><?php echo $outstanding['account_number']; ?></td>
		    <td align="right"><?php echo $outstanding['loan_amount']; ?></td>
		    <td align="right"><?php echo $outstanding['SUM(e.accountinstallment_amount)']; ?></td>
                </tr>
<?php } 
?>
		<tr>
		<td>Total</td>
		<td></td>
		<td align="right"><?php echo sprintf("%4.2f",$loantotal); ?></td>
		<td align="right"><?php echo sprintf("%4.2f",$outstandingtotal); ?></td>
		</tr>
</TABLE>
	<form action="<?php echo $this->baseUrl();?>/outstanding/index/pdftransaction" onClick="window.open('<?php echo $this->baseUrl(); ?>/outstanding/index/reportdisplay/file/outstanding.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')"
 method="POST">
		<div class="reportdiv">
                               
                                    <input type="submit" value="PDF"  id="reportbutton">
                               
                       </div>
		<TABLE>     <tr>

			<input type="Hidden" name="bankname" value="<?php echo $this->bank; ?>">
			<input type="Hidden" name="activity" value="<?php echo $this->activity;?>">
			<input type="Hidden" name="creditline" value="<?php echo $this->creditid;?>">
			<input type="Hidden" name="month" value="<?php echo $this->month;?>">
			<input type="Hidden" name="year" value="<?php echo $this->year;?>">
			</td>
			</tr></TABLE>
	
	</form>
	
<?php } ?>
