<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


                    <h2><p align=""> <font color="black" size="2">Welcome To  </font>
            <font color="#ff6600" size="4"><strong>"OUR</strong></font>
            <font color="black" size="4"><strokng> BANK"</strokng></font></p></h2>              
<div class="cont-rgt-data">
<p align="LEFT"><font color="Black" size="3">Contact us</font></p>
<br>
<div class="vision">
<pre>    
Mahiti Infotech Pvt. Ltd.,
# 583, Vyalikaval HBCS layout,
Nagawara, 
Veerannapalya,
Bangalore - 560045
Karnataka - INDIA

Phone : +91-80-4284-4444
Web   : hhtp://wwww.mahiti.org
</pre>
</div>
</div>

