<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


                    <h2><p align=""> <font color="black" size="2">Welcome To  </font>
            <font color="#ff6600" size="4"><strong>"OUR</strong></font>
            <font color="black" size="4"><strokng> BANK"</strokng></font></p></h2>

               
<div class="cont-rgt-data">
       
             
            <p align="LEFT"><font color="Black" size="3">Vision</font></p>
<br>
            <div class="vision">
            <p align="left"> <font face="" size="2">The vision of Ourbank is to stimulate local development by offering small and medium sized micro financial institutions (MFIs) a true free and open source software solution, based on community-driven software development, named OurBank.</font></p>
            <br>
            <p align="LEFT"><font color="Black" size="3">Features </font></p>
            <br>
<p align="left"><font size="2">OurBank provides MFIs with a tool to store and process all its information, ranging from financial to social data. Ourbank specifically aims at the staff and managers of MFIs, for auditors in the field, and for other actors engaged in the sector. As a result MFIs will broaden the scope of their social impact.
</font></p>
<br>
<p align="left"><font size="2">Once details of a MFI are entered in the system, clients are registered and accounts are created based on bank products (loans, savings, insurance) and product details such as interest rates and repayment times. Once all the data is stored in the system, client and MFI specific data is easily manageable and reported along with graphics. By offering a true free and open source software to manage operational data and track social performance, Ourbank enables MFIs to concentrate in their core mission of giving out loans.</font></p>
<br>

            <p align="left"><font face=""> <font face="" color="black" size="3">OurBank is:</font></font></p>
<p align="left"><font size="2">
            <ul><li>Free of charge</li>
            <li>User Friendly</li>
            <li>Scalable</li>
            <li>Owned by the MFI community</li>
            <li>Built within the FOSS philosophy</li>
            <li>A collective product of experts in the field</li>
            <li>Easily adaptable to the changing environment</li>
            <li>Inherent capacity of localisation</li>
            <li>Transparent</li>
            <li>Secure</li></ul>
            </font>
            </p>
</div>
</div>
<?php 

?>
