<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/address/index/edit/id/<?php echo $this->id; ?>/subId/<?php echo $this->subId; ?>/modId/<?php echo $this->modId; ?>" method="POST"> 
    <fieldset>
    <legend><?php echo $this->translate("Address details"); ?></legend>
        <table class="fieldsets">
        <?php echo $this->form; ?>
        </table>
    <div class="btnhouse">
        <div class="ltbtns">
                <input type="submit" name="Update" id="Update" value="<?php echo $this->translate("Update"); ?>">
        </div>
        <div class="rtbtns">
                <a href="<?php echo $this->baseUrl();?>/<?php echo $this->path1; ?>/index/commonview/id/<?php echo $this->id; ?>"><input type="submit" name="back" id="back" value="<?php echo $this->translate("Back"); ?>"></a>
        </div>
    </div>
    </fieldset>
</form>
