    <fieldset>
        <legend>Search account</legend>
        <form action="<?php echo $this->baseUrl();?>/savingswithdrawal/index/withdrawal" method="POST">
            <table class="fieldsets">
                <tr>
                    <td><label for="fld1" class="mand">Account number</label></td>
                    <td><?php echo $this->form->accNum;?></td>
                </tr>
            </table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Search;?>
                </div>
            </div>
        </form>
    </fieldset>