<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
<legend>View Holiday</legend>
<div class="cont-rgt-data">
<?php foreach($this->holiday as $holiday) {  ?>
<TABLE width="100%" id="hor-minimalist-b">
<TR class="tdbrown">
<TD width="20%">Holiday Name</TD>
<TD width="20"><?php echo $holiday['holidayname'];?></TD>
<td></td>
<TD width="20%"></TD>
<TD></TD>
</TR>

<TR class="tdbrown">
<TD width="20%">Office id</TD>
<TD width="40%"><?php echo $holiday['office_id'];?></TD>
<TD></TD>
<TD width="20%"></TD>
<TD></TD>
</TR>

<TR class="tdbrown">
<TD width="20%">Holiday From</TD>
<TD width="20"><?php echo $holiday['holidayfrom'];?></TD>
<TD></TD>
<TD width="20%"></TD>
<TD></TD>
</TR>

<TR class="tdbrown">
<TD width="20%">Holiday UpTo</TD>
<TD width="20%"><?php echo $holiday['holidayupto'];?></TD>
<TD></TD>
<TD width="20%"></TD>
<TD></TD>
</TR>

<TR class="tdbrown">
<TD width="20">Repayment</TD>
<TD width="20"><?php echo $holiday['repayment_date'];?></TD>
<TD width="20"></TD>
<TD width="20"></TD>
<TD width="20"></TD>

</TR>
    
<TR>
<TD><a href="<?php echo $this->baseUrl(); ?>/management/holiday">
<input name="submit" type="submit" class="officebutton" value="Back"></a></TD>
<TD width="20"></TD>
<TD width="20"></TD>
<TD width="20"></TD>
<TD width="20"></TD>
</TR>
</TABLE>
<?php } ?>
</div>
</fieldset>




<?php if($this->recordstatus_id == 1) { ?>
<table id="hor-minimalist-b" summary="Employee Pay Sheet">
<?php foreach($this->holiday as $holiday) {  ?>
<tr>
<Th align="center"><p><B style="color:red">No you cannot delete since the product exists for </b>&nbsp;&nbsp;<B style="color:red">'<?php echo $holiday['holidayname'];?>' holidays</b></Th>
</tr>
<?php } ?>
</table>
<?php } else { ?>
<?php foreach($this->holiday as $holiday) {  ?>
<table id="hor-minimalist-b" summary="Employee Pay Sheet">
<tr>
<th><B style="color:red">Are you sure you want to delete Holiday</b>&nbsp;&nbsp;<B style="color:red">"<?php echo $holiday['holidayname'];?>" ?*</b></th>
<tr>
</table>
<?php } ?>
<fieldset>
<legend>Delete Holiday</legend>
<div class="cont-rgt-data">
<form action="<?php echo $this->baseUrl();?>/management/holiday/holidaydelete/id/<?php echo $this->holidayupdate_id; ?>" method="POST" name="joe" id="signupForm" class="cmxform">
<table id="hor-minimalist-b" summary="Employee Pay Sheet">
<TR>
<TD  width="35%" align="right" ><label>Remarks<span class="reqMark">*</span></label></TD>
<TD  width="65%"  align="left" ><?php echo $this->deleteform->remarks;?></TD>
</TR>
<TR>
<TD width="35%" align="right"><?php echo $this->deleteform->Yes;?></td>
<TD width="65%"><a href="<?php echo $this->baseUrl();?>/management/holiday">
<input name="submit" type="submit"  value="No" ></a></TD>
</TR>
</table>
</form>
</div>
</div>
</fieldset>
<?php } ?>