<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div>
	<div style="width:350px;float:left">
		<fieldset>
			<legend>Details</legend>
			<table id="hor-minimalist-b" summary="Employee Pay Sheet"> 
				<?php if ($this->groupname) { ?>
				<TR class="tdbrown">
					<TD width="20%">Name</TD>
					<TD width="20"><?php echo $this->groupname;?></TD>
				</TR>
				<?php }?>
				<?php if ($this->memberfirstname ) { ?>
				<TR class="tdbrown">
					<TD width="20%">Name</TD>
					<TD width="20"><?php echo $this->memberfirstname;?></TD>
				<?php }?>
				<?php foreach($this->recurringAccountDetails as $productRecurringDetails) : ?>
				<TR>
					<td width="40%"><b class="star">Producttype:</b></td>
					<TD width="60%"><?php echo $this->escape($productRecurringDetails['productname']);?></TD>
				</TR>
				<TR>
					<td width="40%"><b class="star">Productname:</b></td>
					<TD width="60%"><?php echo $this->escape($productRecurringDetails['offerproductname']);?></TD>
				</TR>
				<TR>
					<td width="40%" ><b class="star">beginDate:</b></td>
					<TD width="60%"><?php echo $this->escape($productRecurringDetails['begin_date']);?></TD>
				</TR>
				<TR>
					<td width="40%" ><b class="star">matureDate:</b></td>
					<TD width="60%"><?php echo $this->escape($productRecurringDetails['mature_date']);?></TD>
				</TR>
				<TR>
					<td width="40%"><b class="star">amount:</b></td>
					<TD width="60%"><?php echo $this->escape($productRecurringDetails['recurring_amount']);?></TD>
				</TR>
				<?php endforeach;?>
				<tr>
					<td width="40%"><B style="color:red">capitalAmount:</b></td>
					<TD width="60%"><B style="color:red"><?php echo $this->paidAmount;?></B></TD>
				</TR>
				<TR>
					<td width="50%"><B style="color:red">grossInterest:</b></td>
					<TD width="50%"><B style="color:red"><?php echo $this->simpleInterest;?></B></TD>
				</TR>
				<TR>
					<td width="50%"><B style="color:red">grossAmount:</b></td>
					<TD width="50%"><B style="color:red"><?php echo $this->matureAmount;?></B></TD>
				</TR>
			</table>
		</fieldset>
	</div>
</div>

<DIV style="float:left;width:50%">
<?php If($this->membertypr_id==3) { ?>
<a href="#" id="open">groupMembers</a>
<div class="box">
<div id="content1">
	<fieldset>
		<legend>Members in account</legend>
		<div class="cont-rgt-data">
	<table id="hor-minimalist-b" summary="Employee Pay Sheet">
		<tr class="tdbrownheading">
			<td width="30%">Name</td>
			<td width="50%">code</td>
		</tr>
	<?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
			<tr class="tdbrown">
				<TD width="30%"><?php echo $arrayroles1['memberfirstname'];?></TD>
				<TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
			</tr>
	<?php }?>
		</table>
</div></fieldset>
<p><a href="#" id="close">hide</a></p>
</div>
</div>
<?php }	?>
<table width="100%"><TR><TD><HR></HR></TD></TR></table>
</DIV>

<div style="float:left;width:50%">
	<fieldset>
		<legend>transactionType</legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet" border="1">
				<TR>
					<td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/transaction/recurring/recurrings/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/manualRepayment/no">Deposit</a></TD>
				</TR>
				<TR>
					<td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/transaction/recurring/newaccount/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>">accountRenewal</a></TD>
				</TR>
				<tr>
					<td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/transaction/recurring/status/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>">status</a></TD>
				</TR>
				<tr>
					<td width="100%"><a href="<?php echo $this->baseUrl(); ?>/transaction/recurring/transfer/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/matured/<?php echo base64_encode($this->paidAmount);?>">accountCloseAndTransferFunds</a></TD>
				</TR>
			</table>
		</div>
	</fieldset>
</div>
