<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
    <legend>Fee for</legend>
	<div class="cont-rgt-data">
                <TABLE id="hor-minimalist-b">
                    <TR>
                        <TD>Fee for</TD>
                        <TD><?php echo $this->form->feefor;?></TD>   

                    </TR>
    
                   
    
                   <tr>
    <TD><a href="<?php echo $this->baseUrl(); ?>/management/fee">
				<input name="submit" type="submit" class="officebutton" value="submit"></a></TD>
                   </tr>
            </TABLE>
    </div>
</fieldset>