<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<!--show the individual member details and edit option !-->
<table id="hor-minimalist-b">
    <tr>
        <th class="firsttd"><?php echo $this->translate("Member information"); ?></th>
        <th class = "secondtd"></th>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/individualdefault/index/editmembername/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th>
    </tr>

    <?php 
    $convertdate = new Creditline_Model_dateConvertor();
    foreach($this->membername as $member_view){ ?>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Office:"); ?></td>
        <td class = "secondtd"><?php echo $member_view['name']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Name:"); ?></td>
        <td class = "secondtd"><?php echo $member_view['membername']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Gender:"); ?></td>
        <td class = "secondtd"><?php echo $member_view['sex']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Date of birth:"); ?></td>
        <td class = "secondtd"><?php echo $startdate=$convertdate->phpnormalformat($member_view['dateofbirth']); ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Mobile:"); ?></td>
        <td class = "secondtd"><?php echo $member_view['mobile']; ?></td>
        <td class="thirdtd"></td>
    </tr>

    <?php } ?>
</table> 
<br/>

<!--show the individual address details and edit option !-->
<table id="hor-minimalist-b">
    <tr>
        <th class="firsttd"><?php echo $this->translate("Address information"); ?></th>
        <th class="secondtd"></th>
        <?php if(count($this->address)!=0) {
        foreach($this->address as $edit_id) { ?>	
        <th><a href="<?php echo $this->baseUrl();?>/address/index/edit/id/<?php echo $this->memberid; ?>/subId/<?php echo $this->sub_id;  ?>/modId/<?php echo $this->mod_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th>
        <?php }} else { ?>
        <th><a href="<?php echo $this->baseUrl();?>/address/index/add/id/<?php echo $this->memberid; ?>/subId/<?php echo $this->sub_id;  ?>/modId/<?php echo $this->mod_id;  ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"></a></th>
        <?php } ?>
    </tr>

    <?php foreach($this->address as $address_view){ ?>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Address line1:"); ?></td>
        <td class = "secondtd"><?php echo $address_view['address1']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Address line2:"); ?></td>
        <td class = "secondtd"><?php echo $address_view['address2']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Address line3:"); ?></td>
        <td class = "secondtd"><?php echo $address_view['address3']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("City:"); ?></td>
        <td class = "secondtd"><?php echo $address_view['city']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("State:"); ?></td>
        <td class = "secondtd"><?php echo $address_view['state']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Country:"); ?></td>
        <td class = "secondtd"><?php echo $address_view['country']; ?></td >
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Pin code:"); ?></td>
        <td class = "secondtd"><?php echo $address_view['zipcode']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <?php } ?>
</table>
<br/>

<!--show the family member details and edit option !-->
<table id="hor-minimalist-b">

    <tr>
        <th class="firsttd"><?php echo $this->translate("Family member details"); ?></th>
        <th class = "secondtd"></th>
        <?php if(($this->familydetails)!=NULL) { ?>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/familydetails/index/edit/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th>
        <?php } else { ?>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/familydetails/index/add/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"></a></th>
        <?php } ?>
    </tr>
</table>
<?php if($this->familydetails){ ?>
<table id="hor-minimalist-b">
    <tr>
        <th><?php echo $this->translate("Family member name"); ?></th>
        <th><?php echo $this->translate("Gender"); ?></th>
        <th><?php echo $this->translate("Age"); ?></th>
        <th><?php echo $this->translate("Relationship"); ?></th>
        <th><?php echo $this->translate("Physical status"); ?></th>
        <th><?php echo $this->translate("Marital status"); ?></th>
    </tr>
    <?php foreach($this->familydetails as $family_details){ ?>
    <tr>
        <td><?php echo $family_details['name']; ?></td>
        <td><?php echo $family_details['sex']; ?></td>
        <td><?php echo $family_details['age']; ?></td>
        <td><?php echo $family_details['relationship']; ?></td>
        <td><?php echo $family_details['physicalstatus']; ?></td>
        <td><?php echo $family_details['maritalstatus']; ?></td>
    </tr>
    <?php } ?>
</table>
<?php } ?>
<br/>

<!--show the family health details and edit option !-->
<table id="hor-minimalist-b">
    <tr>
        <th class="firsttd"><?php echo $this->translate("Family health details"); ?></th>
        <th class = "secondtd"></th>
        <?php if(($this->healthdetails)!=NULL) { ?>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/health/index/edit/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th>
        <?php } else { ?>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/health/index/add/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"></a></th>
        <?php } ?>
    </tr>
</table>
<?php if($this->healthdetails){ ?>
<table id="hor-minimalist-b">
    <tr>
        <th><?php echo $this->translate("Family member name"); ?></th>
        <th><?php echo $this->translate("Health Problem"); ?></th>
        <th><?php echo $this->translate("Under Treatment"); ?></th>
        <th><?php echo $this->translate("Clinical Accessibility"); ?></th>
    </tr>
    <?php foreach($this->healthdetails as $healthdetails){   ?>
    <tr>
        <td><?php echo $healthdetails['name']; ?></td>
        <td><?php echo $healthdetails['health_problem']; ?></td>
        <td><?php if($healthdetails['under_treatment']==1){echo "Yes";} else { echo "No";} ?></td>
        <td><?php if($healthdetails['clinical_accessability']==1){echo "Yes";} else { echo "No";} ?></td>
    </tr>
    <?php } ?>
</table>
<?php } ?>
<br/>	

<!--show the family economic details and edit option !-->
<table id="hor-minimalist-b">
    <tr>
        <th class="firsttd"><?php echo $this->translate("Family economic details"); ?></th>
        <th class = "secondtd"></th>
        <?php if(($this->economicdetails)!=NULL) { ?>
        <th  class="thirdtd"><a href="<?php echo $this->baseUrl();?>/economic/index/edit/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th>
        <?php } else { ?>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/economic/index/add/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"></a></th>
        <?php } ?>
    </tr>
</table>
<?php if($this->economicdetails){ ?>
<table id="hor-minimalist-b">
<tr> 
    <th><?php echo $this->translate("Family member Name"); ?></th>
    <th><?php echo $this->translate("Occupation"); ?></th>
    <th><?php echo $this->translate("Earnings"); ?></th>
    <th><?php echo $this->translate("Benefits"); ?></th>
</tr>
    <?php foreach($this->economicdetails as $economicdetails){   ?>
    <tr>
        <td><?php echo $economicdetails['name']; ?></td>
        <td><?php echo $economicdetails['profession']; ?></td>
        <td><?php if($economicdetails['earnings']==1){echo "Yes";} else { echo "No";} ?></td>
        <td><?php if($economicdetails['benefits']==1){echo "Yes";} else { echo "No";} ?></td>
    </tr>
    <?php } ?>
</table>
<?php } ?>
<br/>

<!--show the family education details and edit option !-->
<table id="hor-minimalist-b">
    <tr>
        <th  class="firsttd"><?php echo $this->translate("Family Education details"); ?></th>
        <th class = "secondtd"></th>
        <?php if(($this->educationdetails)!=NULL) { ?>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/education/index/edit/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></th>
        <?php } else { ?>
        <th class="thirdtd"><a href="<?php echo $this->baseUrl();?>/education/index/add/id/<?php echo $this->memberid; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"></a></th>
        <?php } ?>
    </tr>
</table>
<?php if($this->educationdetails){ ?>
<table id="hor-minimalist-b">
    <tr>
    <th width="27%"><?php echo $this->translate("Family member Name"); ?></th>
    <th width="12%"><?php echo $this->translate("Qualification"); ?></th>
    <th width="10%"><?php echo $this->translate("School Location"); ?></th>
    <th width="17%"><?php echo $this->translate("Transportation"); ?></th>
    </tr>
    <?php foreach($this->educationdetails as $educationdetails){   ?>
    <tr>
        <td><?php echo $educationdetails['name']; ?></td>
        <td><?php echo $educationdetails['qualification']; ?></td>
        <td><?php if($educationdetails['school_location']==1){echo "Far";} else { echo "Near";} ?></td>
        <td><?php if($educationdetails['transportation']==1){echo "Available";} else if ($educationdetails['transportation']==2)  { echo "Not available";} else { echo "Rearly available";} ?></td>
    </tr>
    <?php } ?>
</table>
<?php } ?>
<br/>	
				
<!--show the contact details and edit option !-->
<table id="hor-minimalist-b">
    <tr>
        <th class="firsttd"><?php echo $this->translate("Contact information"); ?></th>
        <th class = "secondtd"></th>
        <?php if((count($this->contact))!=0) {
        foreach($this->contact as $edit_id) { ?>
        <th><a href="<?php echo $this->baseUrl();?>/contactdetails/index/editcontact/id/<?php echo $this->memberid; ?>/subId/<?php echo $this->sub_id;  ?>/modId/<?php echo $this->mod_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th>
        <?php }} else { ?>
        <th><a href="<?php echo $this->baseUrl();?>/contactdetails/index/addcontact/id/<?php echo $this->memberid; ?>/subId/<?php echo $this->sub_id;  ?>/modId/<?php echo $this->mod_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="20" height="20"></a></th>
        <?php } ?>
    </tr>

    <?php foreach($this->contact as $contact){ ?>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Contact person:"); ?></td>
        <td class = "secondtd"><?php echo $contact['contact_person']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Telephone number:"); ?></td>
        <td class = "secondtd"><?php echo $contact['telephone']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Mobile number"); ?></td>
        <td class = "secondtd"><?php echo $contact['mobile']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate("Email ID:"); ?></td>
        <td class = "secondtd"><?php echo $contact['email']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <?php } ?>
</table> 
 <div class="btnhouse">
    <div class="rtbtns">
        <a href="<?php echo $this->baseUrl(); ?>/individualm"><input type="button" name="back" value="<?php echo $this->translate("Back"); ?>"></a>
    </div>
 </div>
