<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<!--
 *  add view of funder details 
-->
<form action="<?php echo $this->baseUrl();?>/funderdetails/index/addfunder" method="POST">
<div class="register">
	<div class="profile_tab"> 
<fieldset>
	<!--to change language -->
<legend><?php echo $this->translate("Funder details"); ?></legend>
		<table class="fieldsets">	
		<?php echo $this->form; ?>	
		</table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <input type="submit" name="Submit" id="Submit" value="<?php echo $this->translate('Submit'); ?>">
                 </div>
                <div class="rtbtns">
                   <a href="<?php echo $this->baseUrl();?>/funder"><input type="submit" name="back" id="back" value="<?php echo $this->translate('Back'); ?>"></a>
                </div>
            </div>
</fieldset>
</div>
</div>
</form>
