<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
 *  delete view of funder details 
--> 

<form action="<?php echo $this->baseUrl();?>/funderdetails/index/delete/id/<?php echo $this->funderid; ?>/modId/<?php echo $this->mod_id; ?>/subId/<?php echo $this->sub_id; ?>" method="POST">
<div class="register">
	<div class="profile_tab"> 
		<table id="hor-minimalist-b">
	<!--to change language -->
                          <tr><th class="firsttd"><?php echo $this->translate("Funder Information"); ?></th></tr>

			<tr><td><font color="red"><?php echo $this->translate("Do you want to delete"); ?></font><?php echo $this->delete; ?></tr> 
			<tr><td><a href="<?php echo $this->baseUrl();?>/fundercommonview/index/commonview/id/<?php echo $this->funderid ?>"><input type="button" name="no" value="<?php echo $this->translate('Cancel'); ?>"></a></td></tr>
			
		</table>

</div>
</div>
</form>
