<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
 *  delete view of funder details 
--> 


<fieldset>
	<legend>Funder Details</legend>
			<div class="cont-rgt-data">
				<form action="<?php echo $this->baseUrl();?>/funderdetails/index/delete/id/<?php echo $this->funderid; ?>/modId/<?php echo $this->mod_id; ?>/subId/<?php echo $this->sub_id; ?>" method="POST" name="joe" id="signupForm" class="cmxform">
				<table id="hor-minimalist-b">
					<TR>
						<TD  width="35%" align="right">Remarks<span>*</span></TD>
						<TD width="65%"  align="left" ><?php echo $this->delete1->remarks;?></TD>
                                                </TR>
                                        <tr><td><font color="red">Do you want to Delete</font></td></tr>
					
				</table>
						<TR><TD><input type="submit" name="Delete" id="Delete" value="Delete">			
						<input name="submit" type="submit"  value="No" ></a></TD></TR>
				</form>
			
</fieldset>

</form>
