<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div class="register">
	<div class="profile_tab"> 
<fieldset>
<legend>Credit Line EDIT</legend>
	<form action="<?php echo $this->baseUrl();?>/creditline/index/creditlineedit/creditline_id/<?php echo $this->creditid;?>" method="POST">
		<table style="float:left">
			<tr>
				<td colspan="5" class="td_border">Credit Line</td>
			</tr>
			<TR >
				<TD class="label" align="right" width="40%">Name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->creditlineform->creditlinename;?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Protfolio Value<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->creditlineform->portfoliovalue;?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Start Date<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->creditlineform->creditline_beginingdate;?><SPAN style="color:red"><?php echo $this->startMsg;?></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">End Date<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->creditlineform->creditline_closingdate;?><SPAN style="color:red"><?php echo $this->endMsg;?></SPAN></TD>
			</TR>
			<TR >
				
				<TD class="label" align="right" width="40%">Active<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->creditlineform->status;?></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%"></TD>
				<TD ><?php echo $this->creditlineform->Submit;?><SPAN style="color:red"></SPAN></TD>
			</TR>
		</table>
	</form>
</fieldset>
</div>
</div>