<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->




<div class="register">
	<div class="profile_tab"> 
<fieldset>
<legend>Meeting ADD</legend>
	<form action="<?php echo $this->baseUrl();?>/meeting/index/meetingadd" method="POST">
		<table style="float:left">
			<tr>
				<td colspan="5" class="td_border">Meeting Add</td>
			</tr>
			<TR >
				<TD class="label" align="right" width="40%">Meeting Name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->meetingForm->meeting_name;?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Office Type<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->meetingForm->office_type;?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Group Name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->meetingForm->group_name;?><SPAN style="color:red"><?php echo $this->startMsg;?></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Group Head<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->meetingForm->group_head;?><SPAN style="color:red"><?php echo $this->endMsg;?></SPAN></TD>
			</TR>
			<TR >
				
				<TD class="label" align="right" width="40%">Meeting Place<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->meetingForm->meeting_place;?></TD>
			</TR>
			<TR >
				
				<TD class="label" align="right" width="40%">Meeting Time<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->meetingForm->meeting_time;?></TD>
			</TR>
			<TR >
				
				<TD class="label" align="right" width="40%">Meeting Day<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->meetingForm->meeting_day;?></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%"></TD>
				<TD ><?php echo $this->meetingForm->Submit;?><SPAN style="color:red"></SPAN></TD>
			</TR>
		</table>
	</form>
</fieldset>
