<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/membership/sample/index" method="POST" name= "myform">


	          
                   <div class="register">
	               <div class="profile_tab">
                       <table id="hor-minimalist-b">
                            <tr>
                                <td align="center" class="txt_rgt">Frist NAme</td>
                                <td colspan="8"><?php  echo $this->form->memberfirstname;?><span class="reqMark">*</span></td>
			
                            </tr>

                       </table>
                       
                                    <table>
                                        <TR>
						<TD><?php echo $this->form->Submit;?>
						      <a href="<?php echo $this->baseUrl(array('controller'=>'index',
						        'action'=>'index')); ?>"></a></TD>
                                                <td><input name="Back" type="submit" class="officebutton" value="Back"></TD>
					</TR>
                                    </table>


              </fieldset>
        </div>
    </div>
</form>

 