<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script>
function getXMLHTTP() {
    var xmlhttp=false;	
    try{
        xmlhttp=new XMLHttpRequest();
    }
    catch(e){
        try{
            xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
        }
        catch(e){
            try{
                xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
            }
            catch(e1){
                xmlhttp=false;
            }
        }
    }
    return xmlhttp;
    }

function getState(subOfficeId) {
    var strURL="<?PHP echo $this->baseUrl();?>/officehierarchy/index/inlineedit?subOfficeId="+subOfficeId; 
    var req = getXMLHTTP();
        if (req) {
            $('#addofficehierarchy').hide();	
            req.onreadystatechange = function() {
            if (req.readyState == 4) {
                if (req.status == 200) {
                    document.getElementById('statediv'+subOfficeId).innerHTML=req.responseText;
                } else {
                    alert("There was a problem while using XMLHTTP:\n" + req.statusText);
                  }
            }	
        }	
        req.open("GET", strURL, true);
        req.send(null);
        }
        $('.b1').hide();
        }

    function reload(val) {
        self.location='officehierarchy?officeNo=' + val ;
    }

    function addPerson() {
        var current =$("#officeNo").val();
        var limit=current+1;
        var maxLevel=10;
        if(current == maxLevel) {
           alert("you reached max level ..you cant create more then "+maxlevel+" level");
        } else if (current == limit)  {
                alert("AT a time u can create only one level");
            } else {
                current++;
          var strToAdd = ' <input type="hidden" name="officeNo" id="officeNo" value="'+current+'" size="2" class="textfield" />'
            $('#mainField').append(strToAdd)
            $('#next').show();
            $('#mainField').show();
            $('#OFFICE_NO').hide();
            $('#addofficehierarchy').hide();
            $('#Edit').hide();
            $('#next').show();
            $('.b1').attr('disabled', 'disabled');
        }
    }
    $(document).ready(function(){
    $('#addofficehierarchy').click(addPerson)
    });


$(document).ready(function() {
$('input#officeCode1').autotab({ target: 'officeCode1', maxlength: 2, format: 'alpha' });
    for(var i=2;i<10;i++) {
        $('input#officeType'+i).autotab({ target: 'officeType'+i,maxlength: 50, format: 'alphas' });
        $('input#officeCode'+i).autotab({ target: 'officeCode'+i,maxlength: 2, format: 'alpha' });
    }
    $('input#officeLevel').autotab({ target: 'officeLevel',maxlength: 2, format: 'number' });
});


$(function() {
    $('.error').hide();
    $('.error1').hide();
    $('.error2').hide()
    $('input.txt_put').css({});
    $('input.txt_put').blur(function(){
    $(this).css({backgroundColor:"#FFFFFF"});
  });

});


function officehierarchy() {
    var name = $("input#officeLevel").val(); // alert(name);
    var current =$("input#officeNo").val(); // alert(current);
        current=current-1;
    if (name > current || name<=0 || name == "" || name == "a" || name == "b") 
        {
        alert('office level should be less then '+(current+1)+' and more then 0');
        $("input#officeLevel").css({backgroundColor:"#FFFFD5"});
        $("input#officeLevel").css({border:"2px solid red"});
        $("input#officeLevel").focus();
        return false;
        }
    for(var i=1;i<=10;i++) 
    {
        var name = $("input#officeCode"+i).val();
        if (name == "") {
            alert('* marked  are mandatory');
            $("input#officeCode"+i).css({backgroundColor:"#FFFFD5"});
            $("input#officeCode"+i).css({border:"2px solid red"});
            $("input#officeCode"+i).focus();
            return false;
        }

    var name = $("input#officeCode"+i).val();
    if (name.length != 2) {
        alert('For office code only 2character allowed');
        $("input#officeCode"+i).css({backgroundColor:"#FFFFD5"});
        $("input#officeCode"+i).css({border:"2px solid red"});
        $("input#officeCode"+i).focus();
        return false;
    }
    var name = $("input#officeType"+i).val();
    if (name == "") {
        alert('* marked  are mandatory');
        $("input#officeType"+i).css({backgroundColor:"#FFFFD5"});
        $("input#officeType"+i).css({border:"2px solid red"});
        $("input#officeType"+i).focus();
        return false;
    }

    var name = $("input#officeType"+i).val();
    if (name.length < 4) {
        alert('For office type minimum 4 character enter');
        $("input#officeType"+i).css({backgroundColor:"#FFFFD5"});
        $("input#officeType"+i).css({border:"2px solid red"});
        $("input#officeType"+i).focus();
        return false;
    }
  }
}

</script>

<?php if($this->noOfficeLevel == 0) { ?>		
    <div class="cont-rgt-data">
        <form action="<?php  echo $this->baseUrl();?>/officehierarchy?officeNo=<?php  echo $this->cat;?>" method="POST">
            <table id="hor-minima be less then '+(current+1)+' and more then 0')list-b" summary="Employee Pay Sheet">
                <tr class="tdbrownheading">
                    <th width="33%"><?php echo $this->translate('Officelevel'); ?></th>
                    <th width="33%"><?php echo $this->translate('OfficeType'); ?></th>
                    <th width="33%"><?php echo $this->translate('officeTypeCode'); ?></th>
                </tr>
                <tr>
                    <td><?php echo $this->translate('Officelevel'); ?>Enter number of office level</td>
                    <td colspan="2"><?php echo $this->form1->officeNo;  ?></td>
                </tr>
                <tr class="tdbrown">
                    <td><?php echo "1 Officfalsee Level" ;?></td>
                    <td><?php echo $this->form1->officeType1;  ?></td> 
                    <td><?php echo $this->form1->officeCode1;  ?></td>
                </tr>
                <?php for($i=2;$i<=$this->cat;$i++) {
                          $a='officeType'.$i;
                          $b='officeCode'.$i;
                ?>
                <tr class="tdbrown">
                    <td><?php echo $i.$this->translate(" Office Level"); ?></td>
                    <td> <?php echo $this->form1->$a;  ?></td> 
                    <td> <?php echo $this->form1->$b;  ?></td>
                </tr>
                <?php
                }
                ?>

            <tr>
                <td colspan="4"><?php if($this->cat){ echo $this->form1->Edit; }  ?></td>
            </tr>
    </table>
    </form>
    </div>
</fieldset>
        <? } else { ?>	
<!--        <table>
            <tr>
                <td width="85%"></td>
                <td><a href="<? //php echo $this->baseUrl();?>/index/officehierarchy"> Office hierarchy strcture</a><br /></td>
            </tr>
        </table>-->

    <div class="cont-rgt-data">
            <form method="POST"  action="<?php  echo $this->baseUrl();?>/officehierarchy/index/edit">
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <tr class="tdbrownheading">
                        <th width="33%"><?php echo $this->translate('Office level'); ?></th>
                        <th width="33%"><?php echo $this->translate('OfficeType'); ?></th>
                        <th width="33%"><?php echo $this->translate('officeTypeCode'); ?></th>
                    </tr>
                    <?php echo $this->form1->officeNo;  ?>
                        <? $i=1; foreach($this->officeHierarchySelect as $eacharraysent) { 
                           $a='officeType'.$i;
                           $b='officeCode'.$i;
                           $c='id'.$i;
                           $d='hierarchyLevel'.$i;	
                           $e='disable'.$i;
                        ?>
                    <tr id="statediv<?php echo $eacharraysent->id;?>">
                        <td><?php echo $i." Office Level" ;?></td>
                        <td><?php echo $eacharraysent->type;?> <?php echo $this->form1->$a;?>
                            <?php echo $this->form1->$c; ?><?php echo $this->form1->$d;?></td> 
                        <td><span style="float:left; width:55px;"> <?php echo $eacharraysent->short_name;?><?php echo $this->form1->$b;?></span>
                            <Input style="float: left;" type="button" <?php echo $this->$e;?> 
                            onclick="getState(<?php echo $eacharraysent->id;?>);" 
                            value="<?php echo $this->translate('edit'); ?>"  class="b1" <?php if($this->$e=='') {?> style="margin-left:2px;"<?php }?>>
                            <a style="float: left;" href="<?php echo $this->baseUrl();?>/officehierarchy/index/delete/officeTypeId/<?php echo $eacharraysent->id;?>/delete=del be less then '+(current+1)+' and more then 0')ete">
                            <Input type="button" <?php echo $this->$e;?>
                            value="delete"  class="b1" <?php if($this->$e=='') {?> style="margin-left:2px;"<?php }?>></a>
	               </td>
                    </tr>
                <?php $i++;
            } ?>
        </table>

            <br />
            <div style="display:none;" id="mainField">

        <table>
            <TR class="tdbrown">
                <td width="33%"><label for="Office_Level'+current+'"><?php echo $this->translate('After Which Level'); ?></label>
                &nbsp;&nbsp;<?php echo $this->form1->officeLevel;  ?><span class="reqMark">*</span></td>
                <TD width="33%"><input type="text" id="officeType<?php echo $this->noOfficeLevel+1;?>" 
                                        name="officeType<?php echo $this->noOfficeLevel+1;  ?>" size="15" class="txt_put" />
                                        &nbsp;<span class="reqMark">*</span></td>
                <td width="33%"><input id="officeCode<?php echo $this->noOfficeLevel+1;  ?>" 
                                        name="officeCode<?php echo $this->noOfficeLevel+1;?>" size="2" class="txt_put"/>
                        &nbsp;<span class="falsereqMark">*</span></td>
            </TR>
        </table>

  </div>
    </div>
        <table>
            <tr><TD colspan="5"><div style="display:none;" id="next">
                <div style="float:left"><input type="submit" name="Next" id="Next" value="Next" onclick="return officehierarchy();"></div>
                <div style="float:left"><a href="<?php echo $this->baseUrl();?>/officehierarchy"><input name="submit" type="submit" class="officebutton" 
                     value="<?php echo $this->translate('cancel'); ?>"></a></div>
                </div>
                <input type="button" id="addofficehierarchy" class="officebutton"
                        value="Add New Level"></TD></tr>
          </table>
    </form>

<?php if($this->errorExisted) {?>
<CENTER class="updateerror"><?php echo $this->errorExisted; ?></CENTER>
<?php }?>

<?php
}?>

