<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
    <legend><?php echo $this->translate('View Holiday'); ?></legend>
	<div class="cont-rgt-data">
        <?php foreach($this->holiday as $holiday) {  ?>
            <TABLE width="100%" id="hor-minimalist-b">
                <TR class="tdbrown">
                    <TD width="20%"><?php echo $this->translate('Holiday Name'); ?></TD>
                    <TD width="20"><?php echo $holiday['holidayname'];?></TD>
                    <td></td>
                    <TD width="20%"></TD>
                    <TD></TD>
                </TR>

                <TR class="tdbrown">
                    <TD width="20%"><?php echo $this->translate('Office Name'); ?></TD>
                    <TD width="40%"><?php echo $holiday['office_id'];?></TD>
                    <TD></TD>
                    <TD width="20%"></TD>
                    <TD></TD>
                </TR>

                <TR class="tdbrown">
                    <TD width="20%"><?php echo $this->translate('Holiday From'); ?></TD>
                    <TD width="20"><?php echo $holiday['holidayfrom'];?></TD>
                    <TD></TD>
                    <TD width="20%"></TD>
                    <TD></TD>
                </TR>

                <TR class="tdbrown">
                    <TD width="20%"><?php echo $this->translate('Holiday UpTo'); ?></TD>
                    <TD width="20%"><?php echo $holiday['holidayupto'];?></TD>
                    <TD></TD>
                    <TD width="20%"></TD>
                    <TD></TD>
                 </TR>

                <TR class="tdbrown">
                    <TD width="20"><?php echo $this->translate('Repayment'); ?></TD>
                    <TD width="20"><?php echo $holiday['holidayrepayment_id'];?></TD>
                    <TD width="20"></TD>
                    <TD width="20"></TD>
                    <TD width="20"></TD>

                </TR>
    
                <TR>
		      <TD><a href="<?php echo $this->baseUrl(array('controller'=>'index','action'=>'index')); ?>">
                                <input name="submit" type="submit" class="officebutton" value="<?php echo $this->translate('Back'); ?>"></a></TD>
                      <TD width="20"></TD>
                      <TD width="20"></TD>
                      <TD width="20"></TD>
                      <TD width="20"></TD>
	       </TR>
        </TABLE>
<?php } ?>
    </div>
</fieldset>


