<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div style="width:440px;float:left">
    <fieldset>
        <legend>New Fee</legend> 
                <table id="hor-minimalist-b"> 
				<?php echo $this->form;?>
				<TD><a href="<?php echo $this->baseUrl(); ?>/management/fee">
				<input name="submit" type="submit" class="officebutton" value="Back"></a></TD>
                </table>
    </fieldset>
</div>


<div style="width:360px;float:right;">
    <fieldset>
        <legend>Existing Fee</legend>
        <table id="hor-minimalist-b">
            <TR>
                    <TH>Name</TH>
                    <TH>Amount</TH>  
                    <TH>Member Type</TH>
					<TH>Fee for</TH>
					
            </TR>
    
            <?php foreach($this->feeDetails as $feeDetails) { ?>
            <TR>
            <TD><?php echo $feeDetails["feename"];?></TD>
            <TD ><?php echo $feeDetails["feevalue"];?></TD>
            <TD><?php echo $feeDetails["membertype"];?></TD>
			<TD><?php echo $feeDetails["feedescription"];?></TD>
			
            </TR> 
            <?php }?>
			
        </table>
    </fieldset>
</div>
