<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/management/fee" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Member type:</td>
                                    <td ><? echo $this->form->field1;?></td>
                                    <td class="label">Fee Name:</td>
                                    <td ><? echo $this->form->field2;?></td>
                                </tr>

                                <tr>
                                    <td class="label">Fee Amount:</td>
                                    <td ><? echo $this->form->field3;?></td>
                                    <td class="label"></td>
                                    <td ></td>
                                </tr>
                                <tr>
                                    <td colspan="4" align="center"><? echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 

 <fieldset>
        <legend>Fee</legend>
        <table id="hor-minimalist-b">
            <tr>
                <th>Fee Name</th>
                <th>Fee Description</td>
                <th>Member Type</td>
                <th>Amount</th>
                <th>Edit</td>
                <th>Delete</th>
            </tr>
                <?php if (count($this->paginator)): ?>
                <?php foreach ($this->paginator as $fee): ?>
            <tr>
                <td><a href="<?php echo $this->baseUrl()."/management/fee/feeview/id/".$fee['feedetails_id']; ?>">
                            <?php echo $this->escape($fee['feename']); ?></a></td>
            <td><?php echo $this->escape($fee['feedescription']);?></td>
            <td><?php echo $this->escape($fee['membertype']);?></td>
            <td><?php echo $this->escape($fee['feevalue']);?></div></td>
            <td><a href="<?php echo $this->baseUrl();?>/management/fee/feeedit/id/<?php echo $fee['feedetails_id'];?>">
                        <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></td>
            <td><a href="<?php echo $this->baseUrl();?>/management/fee/feedelete/id/<?php echo $fee['feedetails_id'];?>">
                        <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
                        <?php endforeach; ?>
                        <?php endif; ?>
            </tr>
            <tr>
                <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                            '/partials/my_pagination_control.phtml'); ?></div></td>
            </tr>
        </table>

<br>
<table>
    <tr>
        <td colspan="8"><a href="<?php  echo $this->baseUrl();?>/management/fee/feeadd">
        <input name="submit" type="submit" class="NormalBtn" value="New Fee"></a></td>
    </tr>
</table>
</fieldset>