<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--<BODY onload="getSavingAccount(savingtypeId);"></BODY> -->
<div class="register">
	<div class="profile_tab"> 
		<table style="float:left">
			<tr>
				<td colspan="5" class="td_border">Product information</td>
			</tr>
			<TR >
				<TD class="label" align="right" width="40%">Product name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->form->offerproductname;?><?php echo $this->form->currentdates;?><SPAN style="color:red"><?php echo $this->errorofferproductname; ?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			</TR>
			<tr>
				<TD class="label" align="right" >Short name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->form->offerproductshortname;?></TD>
			</TR>
			<TR >
				<TD class="label" align="right">Description<span class="reqMark">*</span></TD>
				<TD><?php echo $this->form->offerproduct_description;?></TD>
			</TR>
			<tr>
				<td colspan="2" class="td_border1">Dates</td> 
			</tr>
			<tr> 
				<td class="label" align="right">Begin date:<span class="reqMark">*</span><B style='color:red'>yyyy-mm-dd</b></td>
				<td ><?php echo $this->form->begindate;?></td>
			</tr>
			<tr> 
				<td class="label" align="right">Applicable to:<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->applicableto;?></td>
			</tr>
			<tr>
				<td colspan="2" class="td_border1">Fee accounting line</td>
			</tr>
			<tr> 
				<td class="label" width="45%" align="right">Initial deposit<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->minmumdeposit;?></td>
			</tr>
			<tr > 
				<td class="label" align="right">Freequency of deposit<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->frequencyofdeposit;?></td>
			</tr>
			<tr>
				<td colspan="2" class="td_border1">Installments</td>
			</tr>
			<tr>
				<td class="label" align="right">Interest cal period<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->Int_timefrequency_id;?></td>
			</tr>
			<tr>
				<td class="label" align="right">Interest on calculation<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->frequencyofinterestupdating;?></td>
			</tr>
			<tr> 
				<td class="label" align="right">Minimumbalance for interest<span class="reqMark">*</span></td>
				<td ><?php echo $this->form->minimumbalanceforinterest;?></td>
			</tr>
			<tr>
				<td colspan="2" class="td_border1">Periods and rates</td> 
			</tr>
		<input type="hidden" id="id" value="1">
		<input type="hidden" name="memberCount" id="memberCount" value=""  class="textfield" />	
			<tr>
				<td >From (years)<span class="reqMark">*</span>&nbsp;&nbsp;&nbsp;&nbsp;To (years)<span class="reqMark">*</span>&nbsp;&nbsp;&nbsp;&nbsp;
				Rate of interest<span class="reqMark">*</span></td>
				<td></td>
			</tr><br/>
			<tr>
				<td><input type='text' size='3' name='interestfrom' id='interestfrom' value="" class = 'txt_put'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<input type='text' size='3' name='interestto' id='interestto' value="" class = 'txt_put'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<input type='text' size='3' name='interestrate' id='interestrate' value="" class = 'txt_put'></td>
				<td></td>
			</tr>
			<div id="interestperiods"></div>
				<TD width="50%"><input type="button" onClick="addFormField(); return false;" value="Add interest"></TD>
			<table>
				<tr>
					<td ><font color="Red" size="2" ><b><?php echo $this->errorproductname; ?></b></font></td>
				</tr>
				<tr>
					<td colspan="5" class="td_border"></td>
				</tr>
			</table>
		</table>
	</div>
</div>
