<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
<legend>New savings</legend>
	<form action="<?php echo $this->baseUrl();?>/management/savings/savingsadd" method="POST"  name= "myform">
		<div class="register">
			<div class="profile_tab">
				<table style="float:left">
				    <TR >
						<TD>Product type<span class="reqMark">*</span></TD>
						<TD><?php echo $this->form->productType;?></TD>
						<TD></TD>
						<TD></TD>
					</TR>
				</table>
			</div>
		</div>
		<div id="savingdiv">
			<?php if($this->producttype=='ps') {
				echo $this->render('/savings/persnolsavings.phtml');
			}
			if($this->producttype=='fd') {
				echo $this->render('/savings/fixedsavings.phtml');
			}
			if($this->producttype=='rd') {
				echo $this->render('/savings/recurringsavings.phtml');
			} ?>
		</div>
			<table width="100%">
				<tr>
					<td><?php echo $this->form->Submit;?><td>
					<td><a href="<?php echo $this->baseUrl(); ?>/management/savings/">
                                <input name="submit" type="submit" class="officebutton" value="Back"></a></td>
				</tr>
			</table>
</fieldset>
</form>