<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->



<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
		<form action="<?php echo $this->baseUrl();?>/creditlineindex/index" method="POST">
			<table width="100%">
                                <tr>
                                    <td class="label"><?php echo $this->translate('Creditline name:'); ?></td>
                                    <td ><?php echo $this->form->searchCreditline;?></td>
                                </tr>
                                <tr>
                                    <td class="label"><?php echo $this->translate('Creditline From:'); ?></td>
                                    <td ><?php echo $this->form->search_from_credit;?></td>
                                    <td class="label"><?php echo $this->translate('Creditline To:'); ?></td>
                                    <td ><?php echo $this->form->search_to_credit;?></td>
                                </tr>
                                <tr>
                                   <td></td> <td><font color="red"><?php echo $this->errorMsg;?></font></td>
                                </tr>
                        </table>
			<div class="btnhouse">
				<div class="ltbtns">
				<input type="Submit" name="Search" value="<?php echo $this->translate('Search'); ?>">
				</div>
			</div>
		</form>	
            </div>
    </fieldset> 
</div> 

<table id="hor-minimalist-b" summary="">
	<tr class="tdbrownheading">
	<th><?php echo $this->translate('Creditline name'); ?></th>
	<th><?php echo $this->translate('Portfolio value (R$)'); ?></th>
	</tr>

	<?php if (count($this->paginator)): ?>
	<?php foreach ($this->paginator as $creditline ): ?>
	<tr>
		<td><a href="<?php echo $this->baseUrl()."/creditlinecommonview/index/creditlinecommonviewview/id/".$creditline['id']; ?>"><?php echo $this->escape($creditline['name']);?></a></td>
		<td><?php echo $this->escape($creditline['portfolio']); ?></td>
	<?php endforeach; ?>
	<?php endif; ?>
	
	<tr>
		<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
					'/partials/my_pagination_control.phtml'); ?></div></td>
	</tr>
	</tr>
</table>
