<head>
<script>
    var current =0;
    function addPerson() {
    current++;
    var id = document.getElementById("id").value;
     $("#FamilyInformation").append("<tr id=row"+id+"><td><label for='from" + id + "'><input type='text' size='4' name='period_ofrange_monthfrom"+id+"' id='from" + id + "' class = 'txt_put'></td><td><label for='to" + id + "'><input type='text' size='4' name='period_ofrange_monthto"+id+"' id='to" + id + "' class = 'txt_put'></td><td><label for='rate" + id + "'><input type='text' size='4' name='Interest"+id+"' id='rate" + id + "' class = 'txt_put'><td><a href='#' onClick='removeFormField(\"#row" + id + "\"); return false;'><img src='<?php echo $this->baseUrl(); ?>/images/delete.gif'  border=0 width='16' height='16'></a></td></tr>");

    document.myform.memberCount.value = id;   
    id = (id - 1) + 2;
    document.getElementById("id").value = id;
    }
    $(document).ready(function(){
    $('#addPerson').click(addPerson)
   });

    function removeFormField(id) {
        $(id).remove();
    }
</script>
</head> 
<form action="<?php echo $this->baseUrl();?>/loans/index/loansedit/id/<?php echo $this->offerproduct_id;?>" method="POST" name= "myform">
<fieldset>
    <legend>Edit Loan</legend>
        <div class="register">
            <div class="profile_tab">

            <table id="hor-minimalist-b">
                <TR>
                    <TH>ProductDetails</TH>
                    <TH></TH>
                    <TH></TH>
                    <TH></TH>
                 </TR>
                <TR>
                    <TD>Product Type</TD>
                    <TD><?php echo $this->form->product_id;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD>Productname</TD>
                    <TD><?php echo $this->form->offerproductupdate_id;echo $this->form->offerproductname;?></TD>
                    <TD>ShortName</TD>
                    <TD><?php echo $this->form->offerproductshortname;?></TD>
                </TR>
                <TR>
                    <TD>Description</TD>
                    <TD><?php echo $this->form->offerproduct_description;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TH>Date</TH>
                    <TH></TH>
                    <TH></TH>
                    <TH></TH>
                 </TR>

                <TR>
                    <TD>BeginDate</TD>
                    <TD><?php echo $this->form->begindate;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD>CloseDate</TD>
                    <TD><?php echo $this->form->closedate;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD>applicableTo</TD>
                    <TD><?php echo $this->form->applicableto;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD>GL subcode</TD>
                    <TD><?php echo $this->form->glsubcode_id;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TH>loanAmount</TH>
                    <TH></TH>
                    <TH>Installments</TH>
                    <TH></TH>
                 </TR>
                <TR>
                    <TD>Minimum</TD>
                    <TD><?php echo $this->form->minmumloanamount;?></TD>
                    <TD>Minimum</TD>
                    <TD width="20"><?php echo $this->form->minimumfrequency;?></TD>
                </TR>
                <TR>
                    <TD>Maximum</TD>
                    <TD><?php echo $this->form->maximunloanamount;?></TD>
                    <TD>Maximum</TD>
                    <TD><?php echo $this->form->maximumfrequency;?></TD>
                </TR>
                <TR>
                    <TH>Penal Fee</TH>
                    <TH></TH>
                    <TH>Interest type</TH>
                    <TH></TH>
                 </TR>
                <TR>
                    <td>Penal Fee</td>
                    <TD><?php echo $this->form->penal_Interest;?></TD>
                    <TD>Interest type</TD>
                    <TD><?php echo $this->form->interesttype_id;?></TD>
                </TR>
                    <tr> 
                        <TD >Penal glsubcode</TD>
                        <td><?php echo $this->form->fee_glsubcode_id;?></td>
                        <TD >Interest glsubcode</TD>
                        <td><?php echo $this->form->interest_glsubcode_id;?></td>
                    </tr>
                <TR>
                    <TH>GracePeriod</TH>
                    <TH></TH>
                    <TH>InterestRates</TH>
                    <TH></TH>
                 </TR>
                <tr> 
                    <TD>GracePeriod</TD>
                    <TD><?php echo $this->form->graceperiodnumber;?></TD>
                    <td>
                        <input type="hidden" name="memberCount" id="memberCount" value=""  class="textfield" />
                        <table>
                            <tr class="tdbrownheading"> 
                               	<Th width="10%">From</Th>
                                <Th width="5%">To</Th>
                                <Th width="3%">Rate</Th>
                                <th></th>

                            </tr>
                            <?php $count1 = 0; ?>
                <?php foreach($this->interest1 as $loan) { ?>
                        <?php $count1++; ?>
                        <input type = "hidden" name = "count1" value = " <?php echo $count1; ?>">
                        <input type = "hidden" name = "Interestperiod_id1<?php echo $count1?>" value = " <?php echo $loan->Interestperiod_id; ?>">
                            <tr id="row<?php echo $count1;?>">
                            <td><input name ="period_ofrange_monthfrom<?php echo $count1?>" type="text" 
                                        value="<?php echo $loan['period_ofrange_monthfrom'];?>" size="4" class="txt_put">
                            </td>
                            <td><input name ="period_ofrange_monthto<?php echo $count1?>" type="text" 
                                        value="<?php echo $loan['period_ofrange_monthto'];?>" size="4" class="txt_put">
                            </td>
                            <td><input name ="Interest<?php echo $count1?>" type="text" 
                                        value="<?php echo $loan['Interest'];?>" size="4" class="txt_put">
                            </td>
                            <td><?php if($count1>1) { ?>
                                <a href='#' onClick='removeFormField("#row<?php echo $count1?>"); return false;'> <img src='<?php echo $this->baseUrl(); ?>/images/delete.gif'  border=0 width='16' height='16'><br></a> 
                                <?php } ?></td>
                            </tr>
                <?php } ?>
                    <input type="text" id="id" value="<?php echo $count1+=1;?>">
                            </table>
                        <table id="FamilyInformation"></table>
                            <input type="button" id="addPerson" class="officebutton" value="addTerm">
                         </td>
                    <td></td>
                </tr>
                <TR>
                    <TD><input name="Update" type="submit" class="officebutton" value="Update"></TD>
                      <TD><a href="<?php echo $this->baseUrl(); ?>/loans/index">
                    <input name="submit" type="submit" class="officebutton" value="back"></a></td>
                </TR>
        </table>
            <div><?php echo $this->datesinfo; ?><?php echo $this->amounts; ?><?php echo $this->freequency; ?></div>
        <center style="color:red"><?php echo $this->updateerror; ?></center>
</div>
</div>
</fieldset>
</form>