<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

 <div id="container-1">
<form action="<?php echo $this->baseUrl();?>/fee/index/editfeedetail/id/<?php echo $this->fee_id; ?>" method="POST">

             <fieldset>
				<legend>edit Fee Information</legend>
	               <div class="profile_tab">
		<table class="fieldsets">	
			<?php echo $this->form->fee_id;?>
			<TR >	
				<td><label for="fld1" class="mand">Fee Name:</label></td>
				<TD><?php echo $this->form->feename;?></TD>
			</TR>

		

			<TR >
				<td><label for="fld1" class="mand">Fee description<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->form->feedescription;?></TD>
			</TR>

                	<TR >
				<td><label for="fld1" class="mand">Amount<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->form->feeamount;?></TD>
			</TR>
 			<TR >
				<td><label for="fld1" class="mand">member type</label></TD>
				<TD ><?php echo $this->form->membertype;?></TD>
			</TR>
 </table>


<div class="btnhouse">
                <div class="ltbtns">
                    <?php echo $this->form->Update;?>
                 </div>
                <div class="rtbtns">
                   <a href="<?php echo $this->baseUrl();?>/fee"><?php echo $this->form->Back;?></a>
                </div>
            </div>
</fieldset>
</div>