<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<table width="100%"><TR><TD><HR></HR></TD></TR></table>
<div>
	<?php If($this->type==3) { ?>
	<a href="#" id="open">Group account members</a>
		<div class="box">
			<div id="content1">
				<fieldset>
				<legend> <?php echo $this->memberListtitle;?> </legend>
					<div class="cont-rgt-data">
						<table id="hor-minimalist-b" summary="Employee Pay Sheet">
							<tr>
								<td width="30%">Name</td>
								<td width="50%">Code</td>
							</tr>
							<?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
								<tr class="tdbrown">
									<TD width="30%"><?php echo $arrayroles1['memberfirstname'];?></TD>
									<TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
								</tr>
							<?php }?>
						</table>
					</div>
				</fieldset>
				<p><a href="#" id="close">Hide</a></p>
			</div>
		</div>
	<?php }?>
</div><br/><br/>


		<fieldset>
		<legend>Saving transaction details</legend>
			<div class="cont-rgt-data">
				<table id="hor-minimalist-b" summary="Employee Pay Sheet">
					<tr>
						<th >Tr number</th>
						<th > date</th>
						<th > type</th>
						<th > mode</th>
						<th >mode details</th>
						<th >Credit</th>
						<th >Debit</th>
					</tr>
					<?php foreach ($this->savingsDetails1 as $savingsdetails): ?>
						<tr>
							<td ><?php echo $this->escape($savingsdetails['transaction_id']);?></td>
							<td ><?php echo $this->escape($savingsdetails['transaction_date']);?></td> 
							<td ><?php echo $this->escape($savingsdetails['transactiontype']);?></td>
							<td><?php echo $this->escape($savingsdetails['paymenttype_description']);?></td>  
							<td ><?php echo $this->escape($savingsdetails['paymenttype_details']);?></td> 
							<?php $transaction_type = $this->escape($savingsdetails['transactiontype']); ?>
							<?php if($transaction_type=="credit - Deposit"){ ?>
								<td ><?php echo $this->escape($savingsdetails['transaction_amount']);?></td>
								<td >-</td></td>
							<?php } ?>
							<?php if($transaction_type=="debit - Withdrawal"){ ?>
								<td >-</td></td>
								<td ><?php echo $this->escape($savingsdetails['transaction_amount']);?></td>
							<?php } ?>
						</tr>
					<?php endforeach; ?>
				</table>
			</div>
		</fieldset>
		<fieldset>
		<legend></legend>
			<table summary="Employee Pay Sheet">
				<tr>
					<td ><B style="color:red;margin-left:600px;">Total balance = <?php echo $this->savingsbalance;?></B></td> 
				</tr>
			</table>
		</fieldset>