<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
<legend>View Roles</legend>
    <div class="register">
        <div class="profile_tab">
            <table id="hor-minimalist-b">
                <tr> 
                    <th  width = "20%">Role Name<td>
                    <?php foreach($this->grantView as $grant) {?>
                    <th width = "40%"><?php echo $grant['grantname'];?></SPAN></td>
                    <?php } ?>
                    <th width = "80%"></th>
                </tr>
            </table>
            <table id="hor-minimalist-b" >
                <tr>

                    <?php $i =0; foreach($this->module as $module) {  ?>
                    <?php foreach($this->activityView as $activityView) { $i++;?>
                    <?php if ($activityView['module_id'] == $module['module_id']) {?>
                    <?php if ($i == 1) {?>
                    <td width="30%"><input type="checkbox" checked = "true"  DISABLED="true" value="<?php echo $module['module_id'] ?>"><?php echo $module['module_description']?></td>
                    
                    <?php }  ?> 
                    
                    <?php } ?>
                    <?php } }?>
                </tr> 
                    <?php foreach($this->activityView as $editActivity) {?>  
                <tr>
                    <td >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" DISABLED="true" checked = "true" name="subModule[]"  DISABLED value="<?php echo $editActivity['activity_id']?>"><?php echo $editActivity['submodule_description']?></td>
                </tr>
                <tr>
                    <?php foreach($this->editActivity as $subcheckbox) {?>
                    <?php if ($editActivity['submodule_id'] == $subcheckbox['submodule_id']) {?>
                    <td ></td>
                    <td><input type="checkbox" name="activity[]" checked = "true" DISABLED value="<?php echo $subcheckbox['activity_id'] ?> - <?php echo $subcheckbox['activity_id'] ?> "> <?php echo $subcheckbox['activity_name']?></td>
                    <?php } ?> 
                </tr>
                    <?php } ?>
                    

                </tr>
                <?php } ?>


                <?php foreach($this->activityView1 as $checkbox) {?>
                    <tr>
                         <td >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" DISABLED name="subModule[]" value="<?php echo $checkbox['submodule_id'] ?>"><?php echo $checkbox['submodule_description']?></td>
                    </tr>
                    <tr>
                        <?php foreach($this->subactivity as $subcheckbox) {?>
                        <?php if ($checkbox['submodule_id'] == $subcheckbox['submodule_id']) {?>
                        <td></td>
                        <td ><input type="checkbox" name="activity[]" DISABLED value="<?php echo $subcheckbox['submodule_id'] ?> - <?php echo $subcheckbox['activity_id'] ?> "> <?php echo $subcheckbox['activity_name']?></td>
                       <?php } ?> 
                   </tr>
                   <?php } ?>
                   <?php } ?>
                    <tr>
                          <td><a href="<?php echo $this->baseUrl();?>/management/roles">
                          <input name="submit" type="submit" class="officebutton" value="Back"></a> </td>
                </tr>
            </table>
        </div>
    </div>
</fieldset>