<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">
<form action="<?php echo $this->baseUrl();?>/services/index/edit/id/<?php echo $this->memberid; ?>" method="POST">
<table id="hor-minimalist-b">
<tr> 
    <th width="27%"><?php echo $this->translate("Service details"); ?></th>
    <th width="12%"><?php echo $this->translate("To whom"); ?></th>
    <th width="10%"><?php echo $this->translate("Own fund"); ?></th>
    <th width="17%"><?php echo $this->translate("Recuired loan/help"); ?></th>
</tr>
<?php  
for($i=1;$i<=$this->number;$i++) {
    $a='services'.$i;
    $c='whom'.$i;
    $d='fund'.$i;
    $e='help'.$i;
    $f='source_id'.$i;

?>
<tr>
    <td><?php echo $this->form->$a; ?></td>
    <td><?php echo $this->form->$c; ?></td>
    <td><?php echo $this->form->$d; ?></td>
    <td><?php echo $this->form->$e; echo $this->form->$f; ?></td>
</tr> 
<?php }?>
<tr><td><input type="submit" id="update" name="update" value="<?php echo $this->translate("Update"); ?>"></td>
<td><a href="<?php echo $this->baseUrl();?>/individualmcommonview/index/commonview/id/<?php echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a></td>
</tr>
</table>
</form>
</div>