<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/meeting.js"></script>

<div id = "searchDiv">
<fieldset>
<legend>Add meeting</legend>
	<form action="<?php echo $this->baseUrl();?>/meeting/index/meetingadd" method="POST">
		<table class="fieldsets">
			
			<TR >
				<TD ><label for="fld1" class="mand">Meeting name</TD>
				<TD ><?php echo $this->meetingForm->meeting_name;?></TD>
			</TR>
			<TR >
				<TD ><label for="fld1" class="mand">Office type</TD>
				<TD ><?php echo $this->meetingForm->institute_bank_id;?></TD>
			</TR>
			<TR >
				<TD ><label for="fld1" class="mand">Group name</TD>
				<TD ><div id="groupDiv"><?php echo $this->meetingForm->group_name;?></div><SPAN style="color:red"><?php echo $this->startMsg;?></SPAN></TD>
			</TR>
			<TR >
				<TD ><label for="fld1" class="mand">Group head</TD>
				<TD ><?php echo $this->meetingForm->group_head;?><SPAN style="color:red"><?php echo $this->endMsg;?></SPAN></TD>
			</TR>
			<TR >
				
				<TD ><label for="fld1" class="mand">Meeting place</TD>
				<TD ><?php echo $this->meetingForm->meeting_place;?></TD>
			</TR>
			<TR >
				
				<TD ><label for="fld1" class="mand">Meeting time</TD>
				<TD ><?php echo $this->meetingForm->meeting_time;?></TD>
			</TR>
			<TR >
				
				<TD ><label for="fld1" class="mand">Meeting day</TD>
				<TD ><?php echo $this->meetingForm->meeting_day;?></TD>
			</TR>
		</table>
		</table>
		<div class="btnhouse">
			<div class="ltbtns">
			<?php echo $this->meetingForm->Submit;?>
			</div>
			<div class="rtbtns">
			<a href="<?php echo $this->baseUrl();?>/meetingindex"><?php echo $this->meetingForm->Back;?></a>
			</div>
		</div>
	</form>
</fieldset>
</div>
