<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div>
<div style="width:470px;float:left">
<fieldset>
    <legend>Create NewFundings</legend>
        <div class="cont-rgt-data">
            <form action="<?php echo $this->baseUrl();?>/management/fundings/fundingsadd" method="POST">
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <tr>
                        <TD>Funders</TD>
                        <TD><?php echo $this->form->funder_id;?></TD>
                    </TR>
                   
			<tr> 
                        <td>Instituition Name</td>
                        <td><?php echo $this->form->institutionname;?></td>
						</tr>
                    <tr> 
                        <td>Funding Name</td>
                        <td><?php echo $this->form->fundingname;?></td>
                   </tr>
                    <tr> 
                        <td>Funding Amount</td>
                        <td><? echo $this->form->fundingamount;?></td>
						</tr>
						<tr> 
                        <td>Interest</td>
                        <td><?php echo $this->form->interest;?></td>
						</tr>
                    <tr> 
                        <td>Funding Currency</td>
                        <td><? echo $this->form->funding_currency_id;?></td>
                    </tr>
                    <tr> 
                        <td>Currency Exchanging Rate</td>
                        <td><? echo $this->form->exchangerate;?></td>
                    </tr>
                    <tr> 
                        <td>Funding Period From   (yyyy-mm-dd)</td>
                        <td><? echo $this->form->fund_beginingdate;?></td>
                    </tr>
                    <tr> 
                        <td>Funding Period To   (yyyy-mm-dd)</td>
                        <td><? echo $this->form->fund_closingdate;?></td>
                    </tr>
                </table>
            </div>
        <table width="100%">
            <TR>
                 <td><a href="<?php echo $this->baseUrl(); ?>/management/fundings"><input name="submit" type="submit" class="NormalBtn" 
                                    value="back"></a></td>
                    <td align="right"><?echo $this->form->Submit;?></td>
            </TR>
        </table>
            <b style="color:red;"><?php echo $this->existedFunderName; ?></b>
    </form>
</fieldset>
</div>
    <div style="width:320px;float:left;">
    <fieldset>
        <legend>Alreadyexisting Funders</legend>
            <div class="cont-rgt-data">
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <TR class="tdbrownheading">
                        <th>Funding Name</th>
                        <th>Funding Amount</th>
                    </TR>
                    <?php foreach($this->result as $fundings) : ?>
                    <tr>
                        <td><?php echo $this->escape($fundings['fundingname']);?></td>
                        <td> <?php echo $this->escape($fundings['fundingamount']);?></td>
                    </tr>
                    <?php endforeach;?>
            </table>
        </div>
</fieldset>
</div>
</div>