<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
    <legend>View Fundings</legend>
        <div class="cont-rgt-data">
                <?php foreach($this->fundings as $fundings) { ?>
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <tr>
                        <TD>Funders</TD>
                        <TD><?php echo $fundings['fundername'];?></TD>
                    </TR>
		<tr> 
                        <td>Instituition Name</td>
			<TD><?php echo $fundings['institutionname'];?></TD>
		</tr>


                    <tr> 
                        <td>Funding Name</td>
                        <td><?php echo $fundings['fundingname'];?></td>
                   </tr>
                    <tr> 
                        <td>Funding Amount</td>
                        <td><?php echo  $fundings['fundingamount'];?></td>
                    </tr>
			<tr> 
                        <td>Interest</td>
			<td><?php echo  $fundings['interest'];?></td>
			</tr>
                    <tr> 
                        <td>Funding Currency</td>
                        <td><?php echo $fundings['currencyname'];?></td>
                    </tr>
                    <tr> 
                        <td>Currency Exchanging Rate</td>
                        <td><?php  echo  $fundings['exchangerate'];?></td>
                    </tr>
                    <tr> 
                        <td>Funding Period From   (yyyy-mm-dd)</td>
                        <td><?php echo  $fundings['fund_beginingdate'];?></td>
                    </tr>
                    <tr> 
                        <td>Funding Period To   (yyyy-mm-dd)</td>
                        <td><?php echo  $fundings['fund_closingdate'];?></td>
                    </tr>
                </table>
                <?php } ?>
            </div>
        <table width="100%">
            <TR>
                 <td><a href="<?php echo $this->baseUrl(); ?>/management/fundings"><input name="submit" type="submit" class="NormalBtn" 
                                    value="back"></a></td>
                    <td></td>
            </TR>
        </table>
</fieldset>
