<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->



<SCRIPT LANGUAGE="JavaScript">


function Check(chk)
{
if(document.myform.mainModule.checked==true){
for (i = 0; i < chk.length; i++)
chk[i].checked = true ;
}else{

for (i = 0; i < chk.length; i++)
chk[i].checked = false ;
}
}



function Subcheck(submodid, submodlen,actlen)
{
	var i,su;
	for(su=1;su<=submodlen;su++)
	{
 		var submo=eval("document.myform.subModule"+su);
		var str=eval("document.myform.activity"+su);

		if((submodid==su) && (submo.checked==true))
		{
			for (i = 0; i < actlen; i++)
			{
				str[i].checked=true;
			}
		}
		if((submodid==su) && (submo.checked==false))
		{
			for (i = 0; i < actlen; i++)
			{
				str[i].checked=false;
			}
		}

	}

}


</script> 
<fieldset>
<legend>View Roles</legend>
    <div class="register">
        <div class="profile_tab">
             <form action="<?php echo $this->baseUrl();?>/management/roles/rolesedit" method="POST" name="myform" class="cmxform"  id="signupForm">
            <table id="hor-minimalist-b">
                <tr> 
                    <td><B>Role Name</B><td>
                    <?php foreach($this->grantView as $grant) {?>
                    <td><?php echo $grant['grantname'];?></td>
                    <?php } ?>
                    <td><input type = "hidden" name = "id" value = "<?php echo $this->grant_id;?>"></td>
                </tr>
            </table>
            <table id="hor-minimalist-b" >
                <tr>

                    <?php $i =0; foreach($this->module as $module) {  ?>
                    <?php foreach($this->activityView as $activityView) { $i++;?>
                    <?php if ($activityView['module_id'] == $module['module_id']) {?>
                    <?php if ($i == 1) {?>
                    <td width="30%"><input type="checkbox" checked = "true"  onclick="Check(document.myform)" name = "mainModule" value="<?php echo $module['module_id'] ?>"><?php echo $module['module_description']?></td>
                    
                    <?php }  ?> 
                    
                    <?php } ?>
                    <?php } }?>
                </tr> 
                    <?php foreach($this->activityView as $editActivity) {?>  
                <tr>
                    <td >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" name = "subModule[]" checked = "true" name="subModule[]" value="<?php echo $editActivity['submodule_id']?>"><?php echo $editActivity['submodule_description']?></td>
                </tr>
                <tr>
                    <?php foreach($this->editActivity as $subcheckbox) {?>
                    <?php if ($editActivity['submodule_id'] == $subcheckbox['submodule_id']) {?>
                    <td ></td>
                    <td><input type="checkbox" name="activity[]" checked = "true" value="<?php echo $subcheckbox['submodule_id'] ?> - <?php echo $subcheckbox['activity_id'] ?>"> <?php echo $subcheckbox['activity_name']?></td>
                    <?php } ?> 
                </tr>
                    <?php } ?>
                    <?php if($this->countActivity != $this->countGantActivity) { ?>
                    <?php foreach($this->subactivity as $subactivity)  {?>
                    <?php if ($editActivity['submodule_id'] == $subactivity['submodule_id'] && $editActivity['activity_id']!=$subactivity['activity_id'] ) {?>
                    <td ></td>
                    <td><input type="checkbox" name="activity[]"  value="<?php echo $subactivity['submodule_id'] ?> - <?php echo $subactivity['activity_id'] ?>">  <?php echo $subactivity['activity_name']?></td>
                    <?php } ?> 
                </tr>
                <?php } }?>
                </tr>
                <?php } ?>


                <?php foreach($this->activityView1 as $checkbox) {?>
                    <tr>
                         <td >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox"  name="subModule[]" value="<?php echo $checkbox['submodule_id'] ?>"><?php echo $checkbox['submodule_description']?></td>
                    </tr>
                    <tr>
                        <?php foreach($this->subactivity as $subcheckbox) {?>
                        <?php if ($checkbox['submodule_id'] == $subcheckbox['submodule_id']) {?>
                        <td></td>
                        <td ><input type="checkbox" name="activity[]"  value="<?php echo $checkbox['submodule_id'] ?> - <?php echo $subcheckbox['activity_id'] ?> "> <?php echo $subcheckbox['activity_name']?></td>
                       <?php } ?> 
                   </tr>
                   <?php } ?>
                   <?php } ?>
                   <tr>
                       <td colspan="2" class="txt_rgt" style="font-weight:bold; padding-left:225px;padding-top:25px;padding-bottom:10px;">
                       <div style="float:left"><?php echo $this->form->Submit;?></div>
                       <div style="float:left"><a href="<?php echo $this->baseUrl();?>/management/roles">
                       <input name="submit" type="submit" class="officebutton" value="Back"></a></div> </td>
                    </tr>
            </table>
            </form>
        </div>
    </div>
</fieldset>