<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<SCRIPT LANGUAGE="JavaScript">

var flag =false;
var incre=0;
var actv=0;
var subv=0;
var va=0;
function Check(chk,submodlen)
{
// var modid =1;
//  var management = eval(document.myform.mainModule+modid);

	if(document.myform.mainModule1.checked==true)
	{
		flag =true;
		for(i = 1; i < chk.length; i++)
		chk[i].checked=true;
		for(su=1;su<=submodlen;su++)
			{
		
				var submo=eval("document.myform.subModule"+su);
				submo.checked=true;
				va++;
			}
	}
	else
	{
		flag=false;
		for (i = 0; i < chk.length; i++)
		chk[i].checked = false ;
		for(su=1;su<=submodlen;su++)
			{
		
				var submo=eval("document.myform.subModule"+su);
				submo.checked=false;
				va=0;
			}

	}//alert("value"+va);
subv = va;
}

function Subcheck(submodid, submodlen,actlen)
{
//alert(flag);
		
	var i,su,submo;

	for(su=1;su<=submodlen;su++)
	{
		

 		var submo=eval("document.myform.subModule"+su);
		var str=eval("document.myform.activity"+su);
if(flag==false)
{
		if(incre <= 0)
		{
			document.myform.mainModule1.checked=false; 
		}
		else
		{
			 document.myform.mainModule1.checked=true; 
		}

			if((submodid==su) && (submo.checked==true))
			{
 			incre=incre+1;
 		      //  alert(incre);
				if(incre > 0)
				{
					document.myform.mainModule1.checked=true; 
				}
									 
				for (i = 0; i < actlen; i++)
				{
					str[i].checked=true;
				}
			}
			if((submodid==su) && (submo.checked==false))
			{
			incre=incre-1;
 			//alert(incre);
		
		if(incre <= 0)
		{
			document.myform.mainModule1.checked=false; 
		}
					
				for (i = 0; i < actlen; i++)
				{
					str[i].checked=false;
				}
			}

		

}

if(flag==true)
{
		if(subv <= 0)
		{
			document.myform.mainModule1.checked=false; 
		}
		else
		{
			 document.myform.mainModule1.checked=true; 
		}
		if((submodid==su) && (submo.checked==true))
			{
			subv++;alert(subv);
				document.myform.mainModule1.checked=true; 
 				for (i = 0; i < actlen; i++)
				{
					str[i].checked=true;
					//actv++;
                                       document.myform.mainModule1.checked=true; 
				}
 				
			}
									
				
			
			if((submodid==su) && (submo.checked==false))
			{
			subv--;alert(subv);if(subv <= 0)
		{
			document.myform.mainModule1.checked=false; 
		}
		else
		{
			 document.myform.mainModule1.checked=true; 
		}
				for (i = 0; i < actlen; i++)
				{
					str[i].checked=false;
					//actv--;					
				}
			
			}
// 			if((subv <0 || actv<0))
// 					{
// 						document.myform.mainModule1.checked=false; 
// 					}
// 					if(subv > 0 || actv > 0)
// 					{
// 						document.myform.mainModule1.checked=true; 
// 					}

}
					

}
}


// function count()
// {
// for(su=1;su<=submodlen;su++)
// 	{
// 
//  		var submo=eval("document.myform.subModule"+su);
// 		if(submo.checked==true)
// 		{
// 		va++;
// 		}
// 	}
// }

var Increm =0;
function BottomApproach(actid,subid, modid)
{
var mainmodule=eval("document.myform.mainModule"+modid);
var submodule=eval("document.myform.subModule"+subid);
var activityid=eval("document.myform.activity"+actid);
submodule.checked= true;
mainmodule.checked= true;

//alert(activityid);
// var flag=false;
// if(a
// if(Increm <= 0)
// {
// submodule.checked =false;
// mainmodule.checked= false;
// }
// 
// if(activity.checked == true)
// {
// Increm+=1;
// }
// if(activity.checked == false)
// {
// Increm-=1;
// }

}

</script>

<fieldset>
<legend>New Roles</legend>
    <div class="register">
        <div class="profile_tab">
            <form action="<?php echo $this->baseUrl();?>/management/roles/rolesadd" method="POST" name="myform" class="cmxform"  id="signupForm">
                <table id="hor-minimalist-b">
                    <tr> 
                        <th width = "20%">Role Name     <span class="reqMark">*</span></td>
                        <th width = "40%"><?php echo $this->form->grantname;?><?php echo $this->errorgrantname;?></SPAN></th>
                        <th width = "80%"></th>
                    </tr>
                </table>
                <table id="hor-minimalist-b" >
            	   <tr>
                        <?php $i =0; $sub=count($this->checkbox); foreach($this->module as $module) {?>
                        <?php $i++; ?>
                        <?php if ($i == 1) {?>
                        <td width="30%"><input type="checkbox" onClick="Check(document.myform,<?php echo $sub; ?>)" name="mainModule<?php echo $module['module_id'];?>" value="<?php echo $module['module_id'] ?>"><?php echo $module['module_description']?></td>
                        
                        <?php } ?> 
                        <?php } ?>
                        <?php $sub=count($this->checkbox); $subchk=count($this->subcheckbox); foreach($this->checkbox as $checkbox) { 
				?>
                                <tr>
                        
                                    <td >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" onClick="Subcheck(<?php echo $checkbox['submodule_id'] ?>,<?php echo $sub; ?>,<?php echo $subchk; ?>)" name="subModule" id="subModule<?php echo $checkbox['submodule_id'] ?>" value="<?php echo $checkbox['submodule_id'] ?>"><?php echo $checkbox['submodule_description']?></td>
                                </tr>
                                <tr>
                                    <?php foreach($this->subcheckbox as $subcheckbox) {?>
                                    <?php if ($checkbox['submodule_id'] == $subcheckbox['submodule_id']) {?>
                                    
                                    <td></td>
                                    <td ><input type="checkbox" name="activity[]" onclick="BottomApproach(<?php echo $subcheckbox['activity_id']?>,<?php echo $subcheckbox['submodule_id']?>,1)" id="activity<?php echo $subcheckbox['submodule_id'] ?>" value="<?php echo $subcheckbox['submodule_id'] ?> - <?php echo $subcheckbox['activity_id'] ?> "> <?php echo $subcheckbox['activity_name']?></td>
                                    <?php } ?> 
                            
                                </tr>
                        
                        <?php } ?>
                        <?php } ?>
                        
                        <td ><?php echo $this->form->subactivity_id; ?></td>
                        </tr>
                        <tr>
                              <td colspan="2" class="txt_rgt" style="font-weight:bold; padding-left:225px;padding-top:25px;padding-bottom:10px;">
                              <div style="float:left"><?php echo $this->form->Submit;?></div>
                              <div style="float:left"><a href="<?php echo $this->baseUrl();?>/management/roles/index">
                              <input name="submit" type="submit" class="officebutton" value="Back"></a></div> </td>
                        </tr>
                   </table>
              </form>
         </div>
    </div>
</fieldset>