<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->




<div class="register">
	<div class="profile_tab"> 
<fieldset>
<legend><?php echo $this->translate('Credit Line VIEW'); ?></legend>
<?php   
	
	foreach($this->fetchcreditline as $fetchcreditline){ ?>
		<table style="float:left">
			<tr>
				<td colspan="5" class="td_border">Credit Line</td>
			</tr>
			<TR >
				<TD class="label" align="right" width="40%"><?php echo $this->translate('Name'); ?><span class="reqMark">*</span></TD>
				<TD ><?php echo $fetchcreditline['name'];?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%"><?php echo $this->translate('Portfolio Value'); ?><span class="reqMark">*</span></TD>
				<TD ><?php echo $fetchcreditline['protfolio_value'];?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%"><?php echo $this->translate('Start Date'); ?><span class="reqMark">*</span></TD>
				<TD ><?php echo $fetchcreditline['start_date'];?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%"><?php echo $this->translate('End Date'); ?><span class="reqMark">*</span></TD>
				<TD ><?php echo $fetchcreditline['end_date'];?><SPAN style="color:red"></SPAN></TD>
			</TR>
			<TR >
				
				<TD class="label" align="right" width="40%"><?php echo $this->translate('Active'); ?><span class="reqMark">*</span></TD>
				<TD ><?php if($fetchcreditline['status']==1){ echo "Active";} else { echo "In Active"; }?></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%"></TD>
				<TD ><a href="<?php echo $this->baseUrl();?>/creditline/index"><input type="button" value="<?php echo $this->translate('Back'); ?>"></a></TD>
			</TR>
		</table>
<?php   } ?>

</fieldset>
