<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->



<table  id="hor-minimalist-b">
		<TR>
			<TH class = "firsttd"><?php echo $this->translate('Creditline Information'); ?></TH>
			<TH class = "secondtd"></TH>
			<TH class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/creditline/index/creditlineedit/id/<?php echo $this->id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></TH>
		</TR>
	<?php

	$convertdate = new Creditline_Model_dateConvertor();

	foreach($this->fetchcreditline as $fetchcreditline) { ?>
		<TR >
			<TD class = "firsttd"><?php echo $this->translate('Name'); ?></TD>
			<TD class = "secondtd"><?php echo $fetchcreditline['name'];?></TD>
			 <TD class = "thirdtd"></TD>
		</TR>
		<TR >
			<TD class = "firsttd"><?php echo $this->translate('Portfolio value'); ?></TD>
			<TD class = "secondtd">R$ <?php echo $fetchcreditline['portfolio'];?></TD>
			 <TD class = "thirdtd"></TD>
		</TR>
		<TR >
			<TD class = "firsttd"><?php echo $this->translate('Start date'); ?></TD>
			<TD class = "secondtd"><?php echo $startdate=$convertdate->phpnormalformat($fetchcreditline['start_date']);?></TD>
			 <TD class = "thirdtd"></TD>
		</TR>
		<TR >
			<TD class = "firsttd"><?php echo $this->translate('End date'); ?></TD>
			<TD class = "secondtd"><?php echo $enddate=$convertdate->phpnormalformat($fetchcreditline['end_date']);?></TD>
			 <TD class = "thirdtd"></TD>
		</TR>
		<TR >
			<TD class = "firsttd"><?php echo $this->translate('Active'); ?></TD>
			<TD class = "secondtd"><?php if($fetchcreditline['status']==1){ echo "Yes";} else { echo "No"; }?></TD>
			 <TD class = "thirdtd"></TD>
		</TR>
	<?php   } ?>

</table>

<div class="btnhouse">
	<div class="ltbtns">
	
	</div>
	<div class="rtbtns">
	<a href="<?php echo $this->baseUrl();?>/creditlineindex"><input type="button" value="<?php echo $this->translate('Back'); ?>" /></a>
	</div>
</div>
