<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<html>
<head>
<title></title>
<script type="text/javascript" language="JavaScript">
    function check(yy)
    { 
        var div1=document.getElementById(1);
        if (yy=="checkbox" || yy=="select" || yy=="radio"){
            div1.style.display='block';
        }
        if (yy=="text") {
            div1.style.display='none';
        }
    }
</script> 
</head>
<body>
<form action="<?php echo $this->baseUrl();?>/settings/customization/index" method="POST">
    <table id="hor-minimalist-b">

        <tr>
            <td>Module name</td>
            <td><select name = "feild7" class="txt_put">
                <option value="1">Management</option>
                <option value="2">Membership</option>
                <option value="3">Accounting</option>
                <option value="4">Transaction</option>
                <option value="5">Enquiry</option>
                <option value="6">Reports</option>
                </select>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>From name</td>
            <td><select name = "feild8" class="txt_put">
                <option value="1">Category</option>
                <option value="2">Fee </option>
                <option value="3">Funders</option>
                <option value="4">Holiday</option>
                <option value="5">Loans</option>
                <option value="6">Office</option>
                <option value="7"></option>
                <option value="8"></option>
                <option value="9">Product</option>
                <option value="10">Roles</option>
                <option value="11">Savings</option>
                <option value="12">User</option>
                </select>
            </td>
            <td></td>
        </tr>
        <tr>
            <td>Feild name</td>
            <td><input type = text class="txt_put" name = "feild1" size = 15></td>
            <td></td>
        </tr>
        <tr>
            <td>Display name</td>
            <td><input type = text class="txt_put" name = "feild2" size = 15></td>
            <td></td>
        </tr>
        <tr>
            <td>Feild Type</td>
            <td><select name = "feild3" class="txt_put" onclick="check(this.value);">
                <option value="text">text</option>
                <option value="select">select</option>
                <option value="radio">radio</option>
                <option value="checkbox">Multiple Check box</option>
                </select>
            </td>
            <td id="1" style="display: none">
                <select name = "feild9" class="txt_put" onchange="document.getElementById('Form1').submit()">
				<option value="ourbank_gender">Gender</option>
				<option value="ourbank_membermaritalstatus">Marital Status</option>
				<option value="ourbank_membertypes">Applicable To</option>
				<option value="ourbank_currency">Currency</option>
				<option value="ourbank_feefrequency">Frequencyofdeposit</option>
				<option value="ourbank_frequencyofpayment">Installment Frequency</option>
				<option value="ourbank_interesttypes">Interest Type</option>
				<option value="ourbank_graceperiods">Grace Period</option>
				<option value="ourbank_holidayrepayment">Repayment</option>
				<option value="ourbank_paymenttypes">Transaction Mode</option>
				<option value="ourbank_transaction_type">Transaction Type</option>
		</select>
            </td>
        </tr>
        <tr>
            <td>Data Type</td>
            <td><select name = "feild4" class="txt_put">
                <option value="varchar">varchar</option>
                <option value="int">int</option>
                <option value="smallint">smallint</option>
                <option value="date">date</option>
                </select>
            </td>
            <td></td>
        </tr>

        <tr>
            <td>Mandatory</td>
            <td><input type = checkbox name = "feild5"  value = "1"></td>
            <td></td>
        </tr>

        <tr>
            <td>Dispaly</td>
            <td><input type = checkbox name = "feild6"  value = "1"></td>
            <td></td>
        </tr>

        <TR>
            <TD><input type="submit" name="submit" value="Confirm"></TD>
            <TD><input type="reset" name="reset" value="Clear"></TD>
            <TD></TD>
        </TR>

    </table>
</form>
</body>
</html>


