<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div style="float:left;width:350px"> 
<table id="hor-minimalist-s">
   <TR>
      <td>Member code</td><TD><? echo $this->membercode; ?></TD>
   </TR>
   <TR>
        <td><? echo $this->label; ?></td>
         <td><?php echo $this->groupname; echo $this->memberfirstname;?></TD>
    </TR>
    <TR>
        <td>Branch</td><td><?php echo $this->branch ;?></td>
    </TR>
</table>
<br/>
<table id="hor-minimalist-s">
     <tr>
         <th>Loans</th>
     </tr>
     <?php foreach ($this->savingsProducts as $savingsProducts) { ?>
     <tr>
         <td><a href = "<?php echo $this->baseUrl();?>/account/index/loans/activityId/<?php echo $savingsProducts->activity_id;?>/memberId/<?php echo $this->memberId;?>/" ><?php echo $savingsProducts->activity_name;?></a></td>
    </tr>
    <?php }  ?>
</table>
</div>

<div style="float:right;width:350px">
    <table id="hor-minimalist-s">
       <TR>
           <th>Account</td>
           <th>Products</th>
       </TR>
       <?php foreach($this->account as $arrayroles2)  { ?>
       <TR>
           <TD><?php echo $arrayroles2->account_number;?></TD>
           <TD><?php echo $arrayroles2->activity_name;?></TD>
       </TR>
       <? } ?>
     </table>
</div>

