<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
	<legend>Search member</legend>
		<form action="<?php echo $this->baseUrl();?>/account" method="POST">
			<table class="fieldsets">
                            <TR>
                                <TD><label for="fld3">Member code / Name</label></TD>
                                <TD><? echo $this->form->membercode;?></TD>
                            </TR>
                        </table>
                        <div class="btnhouse">
                            <div class="ltbtns">
                                <?php echo $this->form->Submit;?>
                            </div>
                        </div>
		</form>

</fieldset>

<?php if($this->result) { ?>
	<table id="hor-minimalist-b">
		<tr>
			<Th>Member code</Th>
			<Th>Name/Group name</th>
			<Th>Branch</th>
		</tr>
		<?php foreach($this->result as $member) : ?>
		<tr>
			<td><a href="<?php echo $this->baseUrl();?>/account/index/loans/memberId/<?php echo $member->id;?>/membercode/<?php echo $member->code;?>"><?php echo $member->code;?></a></td>
			<td><?php  echo $member->name;?></td>
			<td><?php  echo $member->Office;?></td>
		</tr>
		<?php endforeach; ?>
	</table>
<?php }?>