<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/fee/index/add/id/<?php echo $this->fee_id; ?>/modId/<?php echo $this->mod_id; ?>/subId/<?php echo $this->sub_id; ?>" method="POST">
	<div class="profile_tab"> 
		<fieldset>
			<legend>Fee details</legend>
				<table class="fieldsets">	
					<?php echo $this->form;?>
				</table>
					<div class="btnhouse">
						<div class="ltbtns">
							<input type="submit" name="Submit" id="Submit" value="Submit">			
						</div>
							<div class="rtbtns">
							<a href="<?php echo $this->baseUrl();?>/fee"><?php echo $this->form->Back;?></a>
					</div>
		</fieldset>
	</div>
</form>
