<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
				<form action="<?php echo $this->baseUrl();?>/fee/" method="POST">
					<table width="100%">
						<tr>
							<td class="label">Fee name:</td>
							<td ><?php echo $this->form->field3;?></td>
							<td class="label">Fee amount:</td>
							<td ><?php echo $this->form->field2;?></td>
						</tr>
						<tr>
							<td colspan="4" align="center"><?php echo $this->form->Search;?></td>
						</tr>
					</table>
					<input type="submit" name="Search" id="Submit" value="Search">			
				</form>	
            </div>
    </fieldset> 
</div> 
	<table id="hor-minimalist-b">
		<tr>
			<th>Fee name </th>
			<th>Fee description</td>
			<th>Amount</td>
		</tr>
		<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $individual): ?>
				<tr>
					<td>
					<a href="<?php echo $this->baseUrl()."/fee/index/view/id/".$individual->id; ?>">
					<?php echo $this->escape($individual->name); ?></a>
					</td>            
					<td>
					<?php echo $this->escape($individual->description);?>
					</td>
					<td>
					<?php echo $this->escape($individual->value);?></td>
			<?php endforeach; ?>
		<?php endif; ?>
		</tr>
 		<tr>
			<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                            '/partials/my_pagination_control.phtml'); ?></div></td>
		</tr>
	</table>

