<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<a href="#" id="open"></B>Change Log</B></a>

<div id="content1">
<fieldset>
<legend>Members in account</legend>

<table id="hor-minimalist-b">
<tr >
<th >Field Name</th>
<th >Old Value</td>
<th >New Value</td>
<th >Changed By</td>
<th >Change Date</th>
</tr>

<?php foreach ($this->changelog as $changelog): ?>
<tr >
<td ><?php echo $this->escape($changelog['fieldname']);?></td>
<td ><?php echo $this->escape($changelog['previous_data']);?></td>
<td ><?php echo $this->escape($changelog['current_data']);?></td>
<td ><?php echo $this->escape($changelog['login_name']);?></td>
<td ><?php echo $this->escape($changelog['modified_date']);?></td>
</tr>
<?php endforeach; ?>
</table>
</fieldset>
<p><a href="#" id="close">hide</a></p>
</div>  

<br/><br/> 


<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/management/product" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Sector Name:</td>
                                    <td ><?php echo $this->form->field2;?></td>
                                    <td class="label">Created date:</td>
                                    <td ><?php echo $this->form->field6;?></td>
                                </tr>

                                <tr>
                                    <td class="label">Sector short name:</td>
                                    <td ><?php echo $this->form->field3;?></td>
                                    <td class="label">Description:</td>
                                    <td ><?php echo $this->form->field4;?></td>
                                    
                                </tr>
                                <tr>
                                    <td colspan="4" align="center"><?php echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div>  
    <fieldset>
        <legend>Sectors</legend>
<table id="hor-minimalist-b" summary="">
    <tr class="tdbrownheading">
 <!--       <th>Category Name</th>-->
        <th>Sector Name</td>
        <th>Sector Short Name</td>
        <th>Description</td>
       <th>Created Date</th>
        <th>edit</td>
        <th>delete</th>
    </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $product ): ?>
    <tr>
 <!--       <td><?php echo $this->escape($product['categoryname']); ?></td>-->
    <td><a href="<?php echo $this->baseUrl()."/management/product/productview/product_id/".$product['product_id']; ?>"><?php echo $this->escape($product['productname']);?></a></td>
    <td><?php echo $this->escape($product['productshortname']);?></td>
    <td><?php echo $this->escape($product['product_description']);?></td>
    <td><?php echo $this->escape($product['createddate']);?></div></td>


    <td><a href="<?php echo $this->baseUrl()."/management/product/productedit/product_id/".$product['product_id']; ?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></td>


    <td><a href="<?php echo $this->baseUrl()."/management/product/productdelete/product_id/".$product['product_id']; ?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
        <?php endforeach; ?>
        <?php endif; ?>

    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                    '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>
</tr>
</table>
<br>
    <table>
        <TR>        
                   <td colspan="8"><a href="<?php  echo $this->baseUrl();?>/management/product/productadd">
        <input name="submit" type="submit" class="NormalBtn" value="New Sector"></a></td>
        </TR>
    </table>
</fieldset>