<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
   <legend>Edit Product</legend> 
            <table id="hor-minimalist-b"> 
                <?php echo $this->form;?>
            </table>
</fieldset>
<!--<fieldset>
<legend>Edit Sectors</legend>
            <table id="hor-minimalist-b">
                <TR>
                    <TH>Sectors Details</TH>
                    <TH></TH>
                    <TH></TH>
                    <TH></TH>
                 </TR>
                <TR>
                    <TD><?php echo $this->form->category_id;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD><?php echo $this->form->productname;?></TD>
                </TR>
                <TR>
                    <TD><?php echo $this->form->productshortname;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                  <TR>
                    <TD><?php echo $this->form->product_description;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>


               <TR>
                    <TD><?php echo $this->form->bank_id;?>present Bank:</TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
               <tr>
                     <TD>Present Name</TD>
                   
                    <TD><?php  foreach($this->bankdetails as $bank_name) {
                                echo $bank_name['bankname']."<br>";
                        } ?>  </TD>
               </tr>
              <TR>
                    <TD><?php echo $this->form->Submit;?></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
	   </table>
			
</fieldset>-->





