<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
	<!--to change language -->
        <legend><?php echo $this->translate("Search"); ?></legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/office" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">	<?php echo $this->translate("Office type:"); ?></td>
                                    <td ><?php echo $this->form->office;?></td>
                                    <td class="label"><?php echo $this->translate("Office Short Name:"); ?></td>
                                    <td ><?php echo $this->form->shortname;?></td>
                                </tr>

                                <tr>
                                    <td class="label"><?php echo $this->translate("City:"); ?></td>
                                    <td ><?php echo $this->form->city;?></td>
                                    <td class="label"><?php echo $this->translate("Office Name:"); ?></td>
                                    <td ><?php echo $this->form->officename;?></td>
                                </tr>
                        </table><input type="submit" name="search" value="<?php echo $this->translate('Search'); ?>">
                    </form>	
            </div>
    </fieldset> 
</div> 
<!-- <p align="right"><a href="<?php echo $this->baseUrl()?>/management/newoffice/tree">Office tree structure</a></p> -->
<table id="hor-minimalist-b">
    <tr>
        <th><?php echo $this->translate('Office Name'); ?></th>
        <th><?php echo $this->translate('Short Name'); ?></th>
        <th><?php echo $this->translate('Office Type'); ?></th>
<!--        <th>City</th>-->
           </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $office): ?>
    <tr>
    <td><a href="<?php echo $this->baseUrl()."/officecommonview/index/commonview/id/".$office['id']; ?>"><?php echo $this->escape($office['name']);?></a></td>
    <td><?php echo $this->escape($office['short_name']);?></td>
    <td><?php echo $this->escape($office['type']);?></td>
<!--    <td><?php echo $this->escape($office['officecity']);?></div></td>-->
                <?php endforeach; ?>
                <?php endif; ?>
    </tr>
    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                    '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>
</table>
<br>

