<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/membership/individual/individualadd" method="POST" name= "myform">
            <div id="container-1">
             <fieldset>
	           <legend>Add Individual Information</legend>
                   <div class="register">
	               <div class="profile_tab">
                       <table id="hor-minimalist-b">

                         <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='branch_name') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td>Branch Name:</td>
                         <TD class="label" align="right">Click to Add :</TD>
				<TD><a href="<?php echo $this->baseUrl();?>/branch/index">ADD</a></TD>
                        </tr>
                         <?php }}} ?>

                          <tr><td>First Name:</td>
                         <TD class="label" align="right">Click to Add :</TD>
				<TD><a href="<?php echo $this->baseUrl();?>/membername/index">ADD</a></TD>
                        </tr>
                
                           <tr><td>Middle and Last Name:</td>
                         <TD class="label" align="right">Click to Add :</TD>
				<TD><a href="<?php echo $this->baseUrl();?>/middlename/index">ADD</a></TD>
                        </tr>


                        <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='member_address') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td>Member address:</td>
                         <TD class="label" align="right">Click to Add :</TD>
				<TD><a href="<?php echo $this->baseUrl();?>/address/index">ADD</a></TD>
                        </tr>
                         <?php }}} ?>



                         <?php 
                            foreach($this->plugin as $selectplugin){
                            if($selectplugin['plugin_name']=='personal') {
                            if($selectplugin['staus']==1) {
                            ?>
                        <tr><td>Member Personal Information</td>
                         <TD class="label" align="right">Click to Add :</TD>
				<TD><a href="<?php echo $this->baseUrl();?>/personal/index">ADD</a></TD>
                        </tr>
                         <?php }}} ?>

                         </table>
                   </div>
	         </div>
            </fieldset>
        </div>
</form>

 