<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/management/attendance/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Meeting Place:</td>
                                    <td ><? echo $this->form->field1;?></td>
                                    <td class="label">Meeting Date:</td>
                                    <td ><? echo $this->form->field2;?></td>
                                </tr>

                                <tr>
                                    <td class="label">Office Name</td>
                                    <td ><? echo $this->form->field7;?></td>
                                    <td class="label">Group Name</td>
                                    <td ><? echo $this->form->field5;?></td>
                                </tr>
                                <tr>
                                    <td colspan="4" align="center"><? echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
               </div>
        </fieldset> 
</div> 
<fieldset>
        <legend>Search Results</legend>
            <table id="hor-minimalist-b">
                <tr>
                    <th>Meeting Place</th>
                    <th>Group Name</td>
                    <th>Meeting Date</td>
                    <th>Office Name</th>
                    <th>edit</td>
                    <th>delete</th>
                </tr>
                    <?php if (count($this->paginator)): ?>
                        <?php foreach ($this->paginator as $meeting): ?>
                    <tr>
                        <td><a href="<?php echo $this->baseUrl()."/management/attendance/attendanceview/id/".$meeting['attendance_id']; ?>">
                        <?php echo $this->escape($meeting['meeting_place']); ?></a></td>
                        <td><?php echo $this->escape($meeting['groupname']);?></td>
                        <td><?php echo $this->escape($meeting['meeting_date']);?></td>
                        <td><?php echo $this->escape($meeting['office_name']);?></div></td>
                        <td><a href="<?php echo $this->baseUrl();?>/management/attendance/attendanceedit/id/<?php echo $meeting['attendance_id'];?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></td>
                        <td><a href="<?php echo $this->baseUrl();?>/management/attendance/attendancedelete/id/<?php echo $meeting['attendance_id'];?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                        </tr>
                        <tr>
                            <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                                        '/partials/my_pagination_control.phtml'); ?></div></td>
                        </tr>
                        </table>
                        <br>
                        <table>
                            <tr>
                                <td colspan="8"><a href="<?php  echo $this->baseUrl();?>/management/attendance/attendanceadd">
                                <input name="submit" type="submit" class="NormalBtn" value="Attendance"></a></td>
                            </tr>
                        </table>
                        </fieldset>

                    



