<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div style="width:480px;float:left"> 
<fieldset>
    <legend>Add Institution</legend> 
            <table id="hor-minimalist-b"> 
                <?php echo $this->form;?>
            </table>

</fieldset>
</div>
<div style="width:300px;float:left"> 
<fieldset>
    <legend>Existing Institutions</legend> 
            <table id="hor-minimalist-b"> 
			<TR class="tdbrownheading">
				<Th width="100%">Institution Name</Th>
			</TR>
			<?php foreach($this->institutionName as $institutionname) { ?>
			<TR class="tdbrown">
				<td><?php echo $this->escape($institutionname['institutionname']);?></td>
			</tr>
			<?php } ?>
            </table>
</fieldset>
</div>