<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--<a href="#" id="open"></B>Change Log</B></a>

<div id="content1">
<fieldset>
<legend>Members in account</legend>

<table id="hor-minimalist-b">
<tr >
<th >Feild Name</th>
<th >Old Value</td>
<th >New Value</td>
<th >Changed By</td>
<th >Change Date</th>
</tr>

<?php// foreach ($this->changelog as $changelog): ?>
<tr >
<td ><?php //echo $this->escape($changelog['filedname']);?></td>
<td ><?php //echo $this->escape($changelog['previous_data']);?></td>
<td ><?php //echo $this->escape($changelog['current_data']);?></td>
<td ><?php //echo $this->escape($changelog['login_name']);?></td>
<td ><?php //echo $this->escape($changelog['modified_date']);?></td>
</tr>
<?php //endforeach; ?>
</table>
</fieldset>
<p><a href="#" id="close">hide</a></p>
</div>  

<br/><br/>   -->
<fieldset>
    <legend>View Institution</legend>
	<div class="cont-rgt-data">
        <?php foreach($this->institution as $institution) {  ?>
            <TABLE id="hor-minimalist-b">
                <TR>
                    <TD>institution name</TD>
                    <TD><?php echo $institution['institutionname'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>short name</TD>
                    <TD><?php echo $institution['institutionshortname'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>Description</TD>
                    <TD><?php echo $institution['institutiondescription'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>Address1</TD>
                    <TD><?php echo $institution['address1'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>Address2</TD>
                    <TD><?php echo $institution['address2'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>Address3</TD>
                    <TD><?php echo $institution['address3'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>city</TD>
                    <TD><?php echo $institution['city'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>state</TD>
                    <TD><?php echo $institution['state'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD>country</TD>
                    <TD><?php echo $institution['country'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>pincode</TD>
                    <TD><?php echo $institution['pincode'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>phone</TD>
                    <TD><?php echo $institution['phone'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>


                <TR>
                    <TD>fax</TD>
                    <TD><?php echo $institution['fax'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>


                <TR>
                    <TD>email_Id</TD>
                    <TD><?php echo $institution['email_Id'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>


                <TR>
                    <TD>contactperson</TD>
                    <TD><?php echo $institution['contactperson'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>


                <TR>
                    <TD>contactperson_phone1</TD>
                    <TD><?php echo $institution['contactperson_phone1'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>contactperson_phone2</TD>
                    <TD><?php echo $institution['contactperson_phone2'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>

                <TR>
                    <TD>contactperson_email</TD>
                    <TD><?php echo $institution['contactperson_email'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
        </TABLE>
        <br>
        <TABLE>
                <TR>
                    <TD><a href="<?php echo $this->baseUrl(); ?>/management/institution/">
                                <input name="submit" type="submit" class="officebutton" value="Back"></a></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
              </TR>
      </TABLE>
<?php } ?>
    </div>
</fieldset>


