<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<BODY onload="toggleField();"></BODY> 


<script>
    function AutoFill() {
        var numb1 = document.form1.recurringamount.value;
        var interest = (document.form1.recurringamount.value * document.form1.perioddescription.value* document.form1.interest.value) / (100 * 12);
        var tAmount =  eval(numb1) + eval(interest);
        document.form1.totalamount.value = tAmount;
        var feeTotal = document.form1.feeTotal.value;
        var pamount = eval(numb1) + eval(feeTotal);

        document.form1.payableamount.value = pamount;
}
</script> 

<script>
function getXMLHTTP() {
		var xmlhttp=false;	
		try{
			xmlhttp=new XMLHttpRequest();
		}
		catch(e)	{		
			try{			
				xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
			}
			catch(e){
				try{
				xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
				}
				catch(e1){
					xmlhttp=false;
				}
			}
		}
		 	
		return xmlhttp;
    }
	
	function getInterests(countryId,path) {	
		  var productId=document.form1.productId.value;
		  var strURL = path+"/transaction/fixed/interests?country="+countryId+"&productId="+productId;
		  //document.write(strURL);
		var req = getXMLHTTP();
		if (req) {
			req.onreadystatechange = function() {
				if (req.readyState == 4) {
					// only if "OK"
					if (req.status == 200) {
					document.getElementById('statediv').innerHTML=req.responseText;
					} else {
					alert("There was a problem while using XMLHTTP:\n" + req.statusText);
					//document.write(countryId);
					}
				}
			}
			req.open("GET", strURL, true);
			req.send(null);
			}
					
			var perioddescription=$('#perioddescription').val();
			if(perioddescription!='') {
			$('#errorspan').show();
			} else {
			$('#errorspan').hide();
			}
						
	}
</script> 

<?php if(!$this->reneval) {?>   
<div>
	<div style="width:350px;float:left">
		<fieldset>
			<legend>Details</legend>
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<Tr>
					<td><b class="star">Name</b></td>
					<TD><?php echo $this->offerproductname;?></TD>
				</TR>
				<TR>
					<td><b class="star">Account number:</b></td>
					<TD><?php echo $this->accountnumber;?></TR>.
				</TR>
				<TR>
					<td><b class="star">Begin date:</b></td>
					<TD><?php echo $this->begin_date;?></TD>
				</TR>
				<TR>
					<td><b class="star">Mature date:</b></td>
					<TD><?php echo $this->mature_date;?></TD>
				</TR>
				<TR>
					<td><b class="star">Amount:</b></td>
					<TD><?php echo $this->fixed_amount;?></TD>
				</TR>
				<TR>
					<td><b class="star">Interest rates:</b></td>
					<TD><?php echo $this->fixed_interest;?></TD>
				</TR>

				<TR>
					<td><b class="star"><SPAN style="color:red">Matured interest:</SPAN></b></td>
					<TD><SPAN style="color:red"><?php echo $this->interestamount;?></SPAN></TD>
				</TR>
				<TR>
					<td><b class="star"><SPAN style="color:red">Total matured amount:</SPAN></b></td>
					<TD><SPAN style="color:red"><?php echo $this->Totalamount;?></SPAN></TD>
				</TR>
			</table>
		</fieldset>
	</div>
</div>
<DIV style="float:left;width:50%">
<?php If($this->membertype_id==3) { ?>
<a href="#" id="open">Group members</a>
<div class="box">
<div id="content1">
	<fieldset>
		<legend>Members in account</legend>
		<div class="cont-rgt-data">
	<table id="hor-minimalist-b" summary="Employee Pay Sheet">
		<tr class="tdbrownheading">
			<td width="30%">Name</td>
			<td width="50%">Code</td>
		</tr>
	<?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
			<tr class="tdbrown">
				<TD width="30%"><?php echo $arrayroles1['memberfirstname'];?></TD>
				<TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
			</tr>
	<?php }?>
		</table>
</div></fieldset>
<p><a href="#" id="close">Hide</a></p>
</div>
</div>
<?php }	?>
<table width="100%"><TR><TD><HR></HR></TD></TR></table>
</DIV>

<div style="float:left;width:50%">
	<fieldset>
		<legend>Amount details</legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet" >
				<TR>
					<td><b class="star"><SPAN style="color:red">Capital amount:</SPAN></b></td>
					<TD><SPAN style="color:red"><?php echo $this->fixed_amount;?></SPAN></TD>
				</TR>
				<TR>
					<td><b class="star"><SPAN style="color:red">Interest amount:</SPAN></b></td>
					<TD><SPAN style="color:red"><?php echo $this->interestamountfrombank;?></SPAN></TD>
				</TR>
				<TR>
					<td><b class="star"><SPAN style="color:red">Total amount:</SPAN></b></td>
					<TD><SPAN style="color:red"><?php echo $this->maturedinterestamount;?></SPAN></TD>
				</TR>
			</table>
		</div>
	</fieldset>
</div>

<div style="float:left;width:50%">
	<fieldset>
		<legend>Transaction type</legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet" border="1">
				<TR>
					<td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/transaction/fixed/renewal/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/capital/<?php echo base64_encode($this->capitalAmount);?>">Capital amount reneval</a></TD>
				</TR>
				<TR>
					<td colspan="2"><a href="<?php echo $this->baseUrl(); ?>/transaction/fixed/renewal/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>/matured/<?php echo base64_encode($this->maturedinterestamount);?>">Matured amount reneval</a></TD>
				</TR>
			</table>
		</div>
	</fieldset>
</div>

<?php if(!$this->Submit) { ?>
<div>
	<div style="width:100%;float:left">
		<fieldset>
			<legend>Fixed accounts</legend>
			<form name="form1" action="<?php echo $this->baseUrl();?>/transaction/fixed/renewal" method="POST" onsubmit='return validate(this)'>
				<table id="hor-minimalist-b" summary="Employee Pay Sheet">
					<TR class="tdbrown">
						<TD width="40%">Account opening date</TD>
						<TD width="60%"><?php echo $this->form2->accountId;echo $this->form2->productId; echo $this->form2->memberId; echo $this->form2->capitalamount;echo $this->form2->feeTotal;echo $this->form2->maturedintrestamount; echo $this->form2->startdate;?><span class="reqMark">(yyyy-mm-dd)*</span></TD>
						<td></td>
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Deposit period</TD>
						<TD width="60%"><?php echo $this->form2->perioddescription;?><span class="reqMark">Months *</span></TD>
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Interest rates</TD>
						<TD width="60%"><div id="statediv"><?php echo $this->form2->recurringinterest;?></div></TD>
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Fixed amount</TD>
						<TD width="60%"><?php echo $this->form2->recurringamount;?><span class="reqMark">*</span></TD>
					</TR>
					<?php if($this->fee) { ?>
					<TR class="tdbrown">
						<TD width="40%">Fee<div align="right"><?php foreach($this->fee as $fee) { ?><?php echo $fee['feename'];?><br/><br/><?php } ?></div></TD>
						<TD width="60%"><?php foreach($this->fee as $fee) { ?><input type="text" name = "fee" value="<?php echo $fee['feevalue'];?>" size="11" readonly="true" class = "textfield"><br/><br/><?php } ?></TD>	
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Payable amount</TD>
						<TD width="60%"><?php echo $this->form2->payableamount;?><span class="reqMark">*</span></TD>
					</TR>
					<?php } ?>
					<TR class="tdbrown">
						<TD width="40%">Matured amount</TD>
						<TD width="60%"><?php echo $this->form2->totalamount;?><span class="reqMark">*</span></TD>
					</TR>
					<tr >
						<td width="40%">Transaction mode</td>
						<td width="60%"><?php echo $this->form2->paymenttype;?><?php echo $this->form2->paymenttype_details;?><h id="details" style="display:none">voucher/cheque/draft number</h> </td> 
					</tr>
					<tr>
						<td width="40%">Description</td>
						<td width="60%"><?php echo $this->form2->transactiondescription;?></td>
					</tr>
				</table>
				<table>
					<tr>
						<td><?php echo $this->form2->Confirm;?></td>
						<td ><a href="<?php echo $this->baseUrl();?>/transaction/fixed/fixed/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>"><input name="submit" type="submit" value="back" tabindex="25"></a></td>
						<td><span class="reqMark">* Markedfieldsaremandatory</span></td>
					</tr>
				<table>
				</table><B style="color:red"><?echo $this->Perioderror;?></B>
			</form>
		</fieldset>
	</div>
</div>
<?php } ?>

<?php if($this->Submit) { ?>
<div>
	<div style="width:100%;float:left">
		<fieldset>
			<legend>Fixed accounts</legend>
			<form name="form1" action="<?php echo $this->baseUrl();?>/transaction/fixed/renewal" method="POST" onsubmit='return validate(this)'>
				<table id="hor-minimalist-b" summary="Employee Pay Sheet">
					<TR class="tdbrown">
						<TD width="40%">Account opening date</TD>
						<TD width="60%"><?php echo $this->form2->accountId;echo $this->form2->productId; echo $this->form2->memberId; echo $this->form2->capitalamount;echo $this->form2->feeTotal;echo $this->form2->maturedintrestamount;
						echo $this->form2->startdate1;
						echo $this->form2->perioddescription1;
						echo $this->form2->interest1;
						echo $this->form2->recurringamount1;
						echo $this->form2->paymenttype1;
						echo $this->form2->paymenttype_details1;
						echo $this->form2->transactiondescription1;
						echo $this->startdate;?></TD>
						<td></td>
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Deposit period</TD>
						<TD width="60%"><?php echo $this->perioddescription;?><span class="reqMark">Months *</span></TD>
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Interest rates</TD>
						<TD width="60%"><?php echo $this->interest;?></TD>
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Fixed amount</TD>
						<TD width="60%"><?php echo $this->recurringamount;?></TD>
					</TR>
					<?php if($this->fee) { ?>
					<TR class="tdbrown">
						<TD width="40%">Fee<div align="right"><?php foreach($this->fee as $fee) { ?><?php echo $fee['feename'];?><br/><br/><?php } ?></div></TD>
						<TD width="60%"><?php foreach($this->fee as $fee) { ?><br/><?php echo $fee['feevalue'];?><br/><?php } ?></TD>	
					</TR>
					<TR class="tdbrown">
						<TD width="40%">Payable amount</TD>
						<TD width="60%"><?php echo $this->payableamount;?></TD>
					</TR>
					<?php } ?>
					<TR class="tdbrown">
						<TD width="40%">Matured amount</TD>
						<TD width="60%"><?php echo $this->maturedamount;?></TD>
					</TR>
					<tr >
						<td width="40%">Transaction mode</td>
						<td width="60%"><?php echo $this->transactionModetype;?></td> 
					</tr>
					<?php if ($this->paymenttype!=1) { ?>
					<tr >
						<td width="40%">voucher/cheque/draft number</td>
						<td width="60%"><?php echo $this->paymenttype_details;?></td> 
					</tr>
					<?php } ?>
					<tr>
						<td width="40%">Description</td>
						<td width="60%"><?php echo $this->transactiondescription;?></td>
					</tr>
				</table>
				<table>
					<TR>
						<TD><?php echo $this->form2->Submit;?></td>
						<td><a href="<?php echo $this->baseUrl();?>/transaction/fixed/renewal/accountId/<?php echo base64_encode($this->accountid);?>/productId/<?php echo base64_encode($this->productid);?>"><input name="submit" type="submit" value="back" tabindex="25"></a></TD>
					</TR>
				</table>
				</table>
			</form>
		</fieldset>
	</div>
</div>
<?php } ?>

<?php } else { ?>
	<B style="color:red"><?php echo $this->reneval; } ?></B>
