<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--<a href="#" id="open"></B>Change Log</B></a>

<div id="content1">
<fieldset>
<legend>Members in account</legend>

<table id="hor-minimalist-b">
<tr >
<th >Feild Name</th>
<th >Old Value</td>
<th >New Value</td>
<th >Changed By</td>
<th >Change Date</th>
</tr>

<?php //foreach ($this->changelog as $changelog): ?>
<tr >
<td ><?php //echo $this->escape($changelog['filedname']);?></td>
<td ><?php //echo $this->escape($changelog['previous_data']);?></td>
<td ><?php //echo $this->escape($changelog['current_data']);?></td>
<td ><?php //echo $this->escape($changelog['login_name']);?></td>
<td ><?php //echo $this->escape($changelog['modified_date']);?></td>
</tr>
<?php //endforeach; ?>
</table>
</fieldset>
<p><a href="#" id="close">hide</a></p>
</div>  -->
<div id="container-1">
	<div class="register">
		<div class="profile_tab">
            <TABLE id="hor-minimalist-b">
<?php if(($this->productdetails)!=NULL) {
					foreach($this->productdetails as $edit_id) { ?>
<tr>
						<th class = "firsttd">product Details</th>
						<th class = "secondtd"></th>
                                                <th class = "third"></th>	
<th></th>
<th class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/product/index/productedit/id/<?php echo $edit_id['id'];?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th>
</tr>
<?php }}  ?>
        <?php foreach($this->productdetails as $product) {  ?>
                <TR>
                    <TD>product Name</TD>
                    <TD><?php echo $product['name'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
 <TR>
                    <TD>Short name</TD>
                    <TD><?php echo $product['shortname'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD>Product Description</TD>
                    <TD><?php echo $product['description'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
 <TR>
                    <TD>category name</TD>
                    <TD><?php echo $product['categoryname'];?></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                </TR>
                <TR>
                    <TD></TD>
                    <TD></TD>
                    <TD></TD>
                    <TD  align="right"></TD>
                    <TD><a href="<?php echo $this->baseUrl(); ?>/product">
                                <input name="submit" type="submit" class="officebutton" value="Back"></a></TD>
              </TR>
        </TABLE>
<?php } ?>
</div>
</div>
</div>

