<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!-- chart view -->
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
   <script type="text/javascript">
     google.load('visualization', '1', {packages: ['corechart']});
   </script>
   <script type="text/javascript">

     function drawVisualization() {

var data = new google.visualization.DataTable();
       data.addColumn('string', 'Name');
       data.addColumn('number', 'records');
       data.addColumn('boolean', 'Total Rupees');
       data.addRows(5);
       data.setCell(0, 0, '16-25');
       data.setCell(0, 1, <? echo $this->age1 ?>);
       data.setCell(0, 2, true);
       data.setCell(1, 0, '26-35');
       data.setCell(1, 1, <? echo $this->age2 ?>);
       data.setCell(1, 2, false);
       data.setCell(2, 0, '36-40');
       data.setCell(2, 1, <? echo $this->age3 ?>);
       data.setCell(2, 2, true);
       data.setCell(3, 0, '41-60');
       data.setCell(3, 1, <? echo $this->age4 ?>);
       data.setCell(3, 2, true);
       data.setCell(4, 0, '60 above');
       data.setCell(4, 1, <? echo $this->age5 ?>);
       data.setCell(4, 2, true);
       // Create and draw the visualization.
       new google.visualization.PieChart(document.getElementById('visualization')).
           draw(data,  {title:"Gender and activity chart-<?php if($this->genderid==1) { echo "Male";} else if($this->genderid==2){ echo "Female";} else { echo "Male and female";} ?>"});
     }
     google.setOnLoadCallback(drawVisualization);
   </script>

	<div class="maincol_box">
	<div id="visualization" style="width: 600px; height: 350px;"></div>
	</div>

<!-- summary report view -->	 
<div class="register">
     <div class="profile_tab">
		<table id="hor-minimalist-b">
			
                <tr><td id="reportth"><?php echo $this->translate("Age"); ?></td><td align="center" id="reportth"><?php if($this->gendername==1) { echo $this->translate("Male");} else if($this->gendername==2){ echo $this->translate("Female");} else { echo $this->translate("Male and female");} ?>-accounts</td></tr>

                <tr><td><?php echo $this->translate('Age between'); ?> <?php echo $this->from1; ?> - <?php echo $this->to1; ?></td>
                        <td align="center"><? echo $this->age1 ?></td>
                </tr>

                <tr><td><?php echo $this->translate('Age between'); ?><?php echo $this->from2; ?> - <?php echo $this->to2; ?></td>
                       <td align="center"><? echo $this->age2 ?></td>
                </tr>

                <tr></td><td><?php echo $this->translate('Age between'); ?><?php echo $this->from3; ?> - <?php echo $this->to3; ?></td>
                        <td align="center"><? echo $this->age3 ?></td>
                </tr>

                 <tr></td><td><?php echo $this->translate('Age between'); ?><?php echo $this->from4; ?> - <?php echo $this->to4; ?></td>
                        <td align="center"><? echo $this->age4 ?></td>
                </tr>

                 <tr><td><?php echo $this->translate('Age above'); ?> <?php echo $this->age; ?></td>
     </div>
</div>                        <td align="center"><? echo $this->age5 ?></td>
                </tr>

          </table>
     </div>
</div>

