<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>Search<?php echo $this->translate("Address details"); ?></legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/activityreport" method="POST">
                            <table width="100%">
                                <tr>
                                    <td><?php echo $this->translate("Activity name"); ?></td><td><? echo $this->form->activity;?></td>
                                    <td><?php echo $this->translate("Gender"); ?></td><td><? echo $this->form->gender;?></td>
                                </tr>
				<tr><TD colspan="2" align="center"><? echo $this->form->Search;?></TD></tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 

<?php if($this->no){ ?>
<div class="register">
     <div class="profile_tab">
		<table id="hor-minimalist-b">
			
                <tr><td id="reportth"><?php echo $this->translate("Age"); ?></td><td align="center" id="reportth"><?php if($this->gendername==1) { echo $this->translate("Male");} else if($this->gendername==2){ echo $this->translate("Female");} else { echo $this->translate("Male and female");} ?>-accounts</td></tr>

                <tr><td><?php echo $this->translate('Age between'); ?><?php echo $this->from1; ?> - <?php echo $this->to1; ?></td>
                        <td align="center"><? echo $this->age1 ?></td>
                </tr>

                <tr><td><?php echo $this->translate('Age between'); ?><?php echo $this->from2; ?> - <?php echo $this->to2; ?></td>
                       <td align="center"><? echo $this->age2 ?></td>
                </tr>

                <tr></td><td><?php echo $this->translate('Age between'); ?><?php echo $this->from3; ?> - <?php echo $this->to3; ?></td>
                        <td align="center"><? echo $this->age3 ?></td>
                </tr>

                 <tr></td><td><?php echo $this->translate('Age between'); ?><?php echo $this->from4; ?> - <?php echo $this->to4; ?></td>
                        <td align="center"><? echo $this->age4 ?></td>
                </tr>

                 <tr><td><?php echo $this->translate('Age above'); ?><?php echo $this->age; ?></td>
     </div>
</div>                        <td align="center"><? echo $this->age5 ?></td>
                </tr>

          </table>
     </div>
</div>
<form action="<?php echo $this->baseUrl();?>/activityreport/index/pdftransaction" method="POST">
<div class="reportdiv">      <input type="submit" value="PDF"  id="reportbutton"><input type="hidden" name="activity" value="<?php echo $this->activityname; ?>"> <input type="hidden" name="gender" value="<?php echo $this->gendername;?>"></div>
</form>
<div class="reportdiv"><a href="<?php echo $this->baseUrl();?>/activityreport/index/chart/act_id/<? echo $this->activityname; ?>/gen_id/<? echo $this->gendername; ?>">      <input type="submit" value="Graph"  id="reportbutton"></td></a></div>

		<tr>
<?php } ?>
