<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div class="register">
     <div class="profile_tab">
		<table id="hor-minimalist-b">
			
                <tr><td id="reportth"><?php echo $this->translate("Age"); ?></td><td align="center" id="reportth"><?php if($this->gendername==1) { echo $this->translate("Male");} else if($this->gendername==2){ echo $this->translate("Female");} else { echo $this->translate("Male and female");} ?>-accounts</td></tr>

                <tr><td><?php echo $this->translate('Age between'); ?><?php echo $this->from1; ?> - <?php echo $this->to1; ?></td>
                        <td align="center"><?php echo $this->age1 ?></td>
                </tr>

                <tr><td><?php echo $this->translate('Age between'); ?><?php echo $this->from2; ?> - <?php echo $this->to2; ?></td>
                       <td align="center"><?php echo $this->age2 ?></td>
                </tr>

                <tr></td><td><?php echo $this->translate('Age between'); ?><?php echo $this->from3; ?> - <?php echo $this->to3; ?></td>
                        <td align="center"><?php echo $this->age3 ?></td>
                </tr>

                 <tr></td><td><?php echo $this->translate('Age between'); ?><?php echo $this->from4; ?> - <?php echo $this->to4; ?></td>
                        <td align="center"><?php echo $this->age4 ?></td>
                </tr>

                 <tr><td><?php echo $this->translate('Age above'); ?><?php echo $this->age; ?></td>
     </div>
</div>                        <td align="center"><?php echo $this->age5 ?></td>
                </tr>

          </table>
     </div>
</div>
