<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form name="editform" action="<?php echo $this->baseUrl();?>/bank/index/editbank" method="POST">
	<fieldset>
    	<legend><?php echo $this->translate("Edit bank"); ?><a href="<?php echo $this->baseUrl();?>/bank/index/deletebank/id/<?php echo $this->id;?>">
                        <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="20" height="20" align="right"></a></legend> 
        <table class="fieldsets"> 
            <?php echo $this->form;?>
        </table>
        <div class="btnhouse">
	   		<div class="ltbtns">
				<input type = "submit" name = "update" value = "<?php echo $this->translate('update');?>">
	   		</div>
	   		<div class="rtbtns">
				<a href="<?php echo $this->baseUrl();?>/bank"><input type = "button" name = "Back" value = "<?php echo $this->translate('Back'); ?>"></a>
	   		</div>
        </div>
	</fieldset>
</form>

