<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!-- shows the bank details !-->
<table id="hor-minimalist-b">
    <tr>
        <th class = "firsttd"><?php echo $this->translate('Bank information'); ?></th>
        <th class = "secondtd"></th>
        <th class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/bank/index/editbank/id/<?php echo $this->id;?>">
                        <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th>

    </tr>
    <?php foreach($this->institution as $institution){ ?>
    <tr>
        <td class = "firsttd"><?php echo $this->translate('Bank name'); ?></td>
        <td class = "secondtd"><?php echo $institution['name']; ?></td>
        <td class = "thirdtd"></td>
    </tr>
    <tr>
        <td class = "firsttd"><?php echo $this->translate('Active'); ?></td>
        <?php if ($institution['status'] == 1) { ?>
        <td class = "secondtd"><?php echo $this->translate('Yes'); ?></td>
        <?php } else { ?>
        <td class = "secondtd"><?php echo $this->translate('No'); ?></td>
        <?php } ?>
        <td class = "thirdtd"></td>
    </tr>
    <?php } ?>
</table>
<br>

<!-- shows the bank address information !-->
<table id="hor-minimalist-b">
    <tr>
        <th class = "firsttd"><?php echo $this->translate('Address information'); ?></th>
        <th class = "secondtd"></th>
        <?php if (count($this->address)!=0) {?>
        <th class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/address/index/edit/id/<?php echo $this->id;?>/modId/<?php echo $this->mod_id ?>/subId/<?php echo $this->sub_id ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th>
        <?php } else { ?>
        <th class = "firsttd"><a href="<?php echo $this->baseUrl();?>/address/index/add/id/<?php echo $this->id; ?>/modId/<?php echo $this->mod_id ?>/subId/<?php echo $this->sub_id ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="20" height="20"></a></th>
        <?php } ?>
    </tr>

        <?php if (count($this->address)!=0) {?>
        <?php foreach($this->address as $address){ ?>
        <tr>
            <td class = "firsttd"><?php echo $this->translate('Address line1'); ?></td>
            <td class = "secondtd"><?php echo $address['address1']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd"><?php echo $this->translate('Address line2'); ?></td>
            <td class = "secondtd"><?php echo $address['address2']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd"><?php echo $this->translate('Address line3'); ?></td>
            <td class = "secondtd"><?php echo $address['address3']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd"><?php echo $this->translate('City'); ?></td>
            <td class = "secondtd"><?php echo $address['city']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd"><?php echo $this->translate('Country'); ?></td>
            <td class = "secondtd"><?php echo $address['country']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
        <tr>
            <td class = "firsttd"><?php echo $this->translate('Pin code'); ?></td>
            <td class = "secondtd"><?php echo $address['zipcode']; ?></td>
            <td class = "thirdtd"></td>
        </tr>
 
        <?php } ?>
        <?php } ?>

        <?php  ?>
    </table>
<br>

<!-- shows the bank contact information !-->
<table id="hor-minimalist-b">
    <tr>
        <th class="firsttd"><?php echo $this->translate('Contact information'); ?></th>
        <th class = "secondtd"></th>
        <?php if((count($this->contact))!=0) {
        foreach($this->contact as $edit_id) { ?>
        <th><a href="<?php echo $this->baseUrl();?>/contactdetails/index/editcontact/id/<?php echo $this->id; ?>/subId/<?php echo $this->sub_id;  ?>/modId/<?php echo $this->mod_id;  ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th>
        <?php }} else { ?>
        <th><a href="<?php echo $this->baseUrl();?>/contactdetails/index/addcontact/id/<?php echo $this->id; ?>/subId/<?php echo $this->sub_id;  ?>/modId/<?php echo $this->mod_id;  ?>"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="20" height="20"></a></th>
        <?php } ?>
    </tr>

    <?php foreach($this->contact as $contact){ ?>

    <tr>
        <td class="firsttd"><?php echo $this->translate('Telephone number:'); ?></td>
        <td class = "secondtd"><?php echo $contact['telephone']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate('Mobile number:'); ?></td>
        <td class = "secondtd"><?php echo $contact['mobile']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <tr>
        <td class="firsttd"><?php echo $this->translate('Email ID:'); ?></td>
        <td class = "secondtd"><?php echo $contact['email']; ?></td>
        <td class="thirdtd"></td>
    </tr>
    <?php } ?>
</table> 
    <div class="btnhouse">
	<div class="ltbtns">
	</div>
	<div class="rtbtns">
	   <a href="<?php echo $this->baseUrl();?>/bank"><input type = "button" name = "Back" value = "<?php echo $this->translate('Back'); ?>"></a>
	</div>
    </div>    
