<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<table id = "hor-minimalist-b">
<tr>
<td>
<SPAN style="color:Green">Mangement</SPAN>
<p>Management Module is the First and vast module which gives knowledge to the userIn the top we have a search option where we can search the requried category</p>
<p>
The Management modules mainly deals with creating offices to Defining the Products. Precisely one can say the management module can be maintained by administrator.</p>
<p>The applications starts with the Office creation in the form of office Hierarchy. User can easily understand which one is the parent office and children Office by viewing the Hierarchy structure.</p>
<p>User can identify the Ledger by using unique key which have code and also subcode. </p>
<p>For Particular Product ,when the user want to take a loan or save the amount, the “fee” is being collected from the user. </p>
<p>Ourbank has Funders who funds the amount of money to the “ourbank”. The Funder's details, their fundings are being captured in their respective applications like Funds, Funders and Fundings. </p>
<p>
The admin can create any number of categories according to their requirement and offer for the bank. The Instances for category called “Product” can be created in Product. </p>
<p>The Product definition can be defined in the categories like Loan, Savings and Insurance </p>
<p>
The administrator can be able to create new Holidays and also can see the holidays through Holiday Module in the “OurBank” Application. </p>
</td>
</tr>
</table>







