<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<!-- delete form action !-->
<form action="<?php echo $this->baseUrl();?>/user/index/delete/id/<?php echo $this->id; ?>" method="POST">
	<div class="register">
		<div class="profile_tab"> 
			<fieldset>
			<legend>Delete user details</legend>
			<table id="hor-minimalist-b">
<!-- display datas in delete form  !--> 

			<?php foreach($this->userdetails as $funder_view){?>
                          
			<tr>
				<td >User name:</td>
				<td ><?php echo $funder_view['username'];?></td>
				<td ></td>
			</tr>
			<tr>
				<td >Bank name:</td>
				<td ><?php echo $funder_view['name'];?></td>
				<td ></td>
			</tr>
			<tr>
				<td >Gender:</td>
				<td ><?php echo $funder_view['sex'];?></td>
				<td ></td>

			</tr>
			<tr>
				<td >Designation:</td>
				<td ><?php echo $funder_view['designation_name'];?></td>
				<td ></td>

			</tr>
			<tr>
				<td >Granted as:</td>
				<td ><?php echo $funder_view['grant'];?></td>
				<td ></td> 
                        </tr>                 
			

			<tr>
                                <td >Remarks<span>*</span></td>
                                <td ><?php echo $this->deleteform->remarks;?></td>
                                <td ></td>  
                        </tr>
                        <tr>
                                <td><font color="red">Do you want to delete</font></td>
				<td ></td>
                                <td ></td>  
			</tr> 
<?php } ?>
			
		</table>
				<input type="submit" name="Delete" id="Delete" value="Delete">			

<a href="<?php echo $this->baseUrl();?>/user/index/edituserdetail/id/<?php echo $this->user_id ?>"><input type="button" name="no" value="No"></a>

	</fieldset>
	</div>
	</div>
</form>