
<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<fieldset>
<!--  delete button  !-->
	<legend>Edit user information <a href="<?php echo $this->baseUrl();?>/user/index/delete/id/<?php echo $this->id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" align="right" border=0 width="16" height="16"></a></legend>
<!-- edit form action  !-->
	<form action="<?php echo $this->baseUrl();?>/user/index/edituserdetail/id/<?php echo $this->id; ?>" method="POST">
		<table class="fieldsets">
		

		
			<?php echo $this->form->fee_id;?>
			<?php echo $this->form;?>


	</table>
	<div class="btnhouse">
			<div class="ltbtns">
<!-- update button  !-->
			<input type="submit" name="Update" id="Update" value="Update">  			</div>
			<div class="rtbtns">
<!-- back button !-->
			<a href="<?php echo $this->baseUrl();?>/user/index/commonview/id/<?php echo $this->user_id; ?>"><?php echo $this->form->Back;?></a>
			</div>
		</div>
	</form>
</fieldset>
