<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<html>
  <head>
    <script type='text/javascript' src='<?php  echo $this->baseUrl();?>/js/jquery-1.3.2.min.js'></script>
    <script type='text/javascript' src='<?php  echo $this->baseUrl();?>/js/jquery-1.3.1.js'></script>
    <script type='text/javascript'>
$(document).ready(
  function() {
    $('input#tmpAddRow').click(
      function() {
        var newRow = $('tr#tmp').clone(true).removeAttr('id');
        newRow.children("select").each( function() {
            $(this).children(':first').attr('selected', 'selected');
        });
        //$('input:text').val('');
        newRow.children("input:text").val("");
        newRow.appendTo('tbody');
        //$('#tmp').show();
      }
    );

    $('tr input[type=text]').focus(
      function() {
        $(this).addClass('myFocused');   
      }
    ).blur(
      function() {
        $(this).removeClass('myFocused');
      }
    );

    $('.delete-icon').click(function() {$(this).closest('tr').remove()});
  }
);

    </script>
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">      
    <form name="form1" action="<?php echo $this->baseUrl();?>/familymembers/index/editfamily/id/<?php echo $this->id; ?>/subId/<?php echo $this->subId; ?>/modId/<?php echo 2; ?>" method="POST">
        <table id="hor-minimalist-b">
            <tr> 
                <th ><?php echo $this->translate("Name"); ?></th>
                <th ><?php echo $this->translate("Relation"); ?></th>
                <th ><?php echo $this->translate("Education"); ?></th>
                <th ><?php echo $this->translate("Age"); ?></th>
                <th ><?php echo $this->translate("Gender"); ?></th>
                <th ><?php echo $this->translate("Proffession"); ?></th>
                <th ><?php echo $this->translate("Skill"); ?></th>
                <th ><?php echo $this->translate("Bank A/C"); ?></th>
                <th ><?php echo $this->translate("DOB"); ?></th>
                <th ><?php echo $this->translate("Joined SHG"); ?></th>
                <th ><?php echo $this->translate("Marital status"); ?></th>
                <th></th>

            </tr>
            <?php $i = 0; ?>
            <?php foreach ($this->familydetails as $familydetails) { $i++;?>
             <?php if ($i == 1) { ?>
             <tr id='tmp'>
            <?php } else { ?>
            <tr>
            <?php } ?>
                <td><INPUT type="text" name = "mem_name[]" value="<?php echo $familydetails['name']?>" ></td>   

                <td><select name = "relation[]">
          
                        <OPTION value="<?php echo $familydetails["relationship_id"]; ?>">
                            <?php echo $familydetails["relationname"]; ?>
                        </OPTION>
              <?php
                foreach ($this->relation as $relation) 
                {
                    if($relation['id']!= $familydetails["relationship_id"]) { ?>
                        <option value="<?php echo $relation['id']?>"><?php echo $relation['name']?></option>

                    <?php }
                }     ?>
                </select>
                </td>

                <td><select name = "education[]">
                        <OPTION value="<?php echo $familydetails["eductaion_id"]; ?>">
                            <?php echo $familydetails["qualifyname"]; ?>
                        </OPTION>
                    <?php foreach ($this->qualify as $qualify) { 
                                if($qualify['id']!= $familydetails["eductaion_id"]) { ?>
                    <option value="<?php echo $qualify['id']?>"><?php echo $qualify['name']?></option>

                    <?php }} ?>
                </select>    
                </td>

                <td><INPUT type="text" name = "age[]"  value="<?php echo $familydetails['age']?>" ></td>   

                <td><select name = "gender[]">
                        <OPTION value="<?php echo $familydetails["gender_id"]; ?>">
                            <?php echo $familydetails["gendername"]; ?>
                        </OPTION>
                    <?php foreach ($this->gender as $gender) { 
                        if($gender['id']!= $familydetails["gender_id"]) { ?>
                    <option value="<?php echo $gender['id']?>"><?php echo $gender['name']?></option>
                    <?php }} ?>
                </select>    
                </td>

                <td><select name = "proffesion[]">
                        <OPTION value="<?php echo $familydetails["profession_id"]; ?>">
                            <?php echo $familydetails["proffessionname"]; ?>
                        </OPTION>
                    <?php foreach ($this->proffession as $proffession) { 
                         if($proffession['id']!= $familydetails["profession_id"]) { ?>
                    <option value="<?php echo $proffession['id']?>"><?php echo $proffession['name']?></option>
                    <?php } } ?>
                </select>    
                </td>

                <td><select name = "skill[]">
                        <OPTION value="<?php echo $familydetails["skill"]; ?>">
                            <?php echo $familydetails["skillname"]; ?>
                        </OPTION>
                    <?php foreach ($this->skill as $skill) { 
                        if($skill['id']!= $familydetails["skill"]) { ?>
                    <option value="<?php echo $skill['id']?>"><?php echo $skill['name']?></option>
                    <?php } } ?>
                </select>    
                </td>


                <td><INPUT type="checkbox" name = "banckAccount[]" ></td>
                <td><INPUT type="text" name = "dob[]" value="<?php echo $familydetails['date_of_birth']; ?>"></td>   
                <td><INPUT type="checkbox" name = "joinedshg[]" ></td>

                <td><select name = "marital[]">
                        <OPTION value="<?php echo $familydetails["maritalstatus_id"]; ?>">
                            <?php echo $familydetails["maritalname"]; ?>
                        </OPTION>
                    <?php foreach ($this->marital as $marital) { 
                        if($marital['id']!= $familydetails["maritalstatus_id"]) { ?>
                    <option value="<?php echo $marital['id']?>"><?php echo $marital['name']?></option>

                    <?php }} ?>
                </select>   
                </td>

                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
            </tr> 

        <?php } ?>
        </table>  

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>"><input type="submit"  name="Update" value="<?php echo $this->translate("Update"); ?>"><a href="<? echo $this->baseUrl();?>/individualmcommonview/index/commonview/id/<? echo $this->id ?>"><input type="button" id="submit"  value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
</div>
