<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->  
<div id = "searchDiv">
    <fieldset>
        <legend><?php echo $this->translate('New activity'); ?></legend>
        <form name = "addform" action="<?php echo $this->baseUrl();?>/activity/index/activityadd" method="POST"  name= "myform">
            <table class="fieldsets"> 
                    <?php echo $this->form;?>
            </table>
            <div class="btnhouse">
                <div class="ltbtns">
                    <input type = "Submit" name = "Submit" id="Submit" value = "Submit"/>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/activity/index"><input type = "Button" name = "Back" id="Back" value = "Back"/></a>
                </div>
            </div>
        </form>
    </fieldset>
</div>