<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
    <legend><?php echo $this->translate('Delete institution'); ?></legend>
	<form name = "deleteform" action="<?php echo $this->baseUrl();?>/institution/index/deleteinstitution/" method="POST">
	   <table class="fieldsets">

	   
                <TR>
                    <TD  ><label for="fld1" class="mand"><?php echo $this->translate('Remarks'); ?></label></TD>
		    <TD  ><?php echo $this->form->remarks;?></TD>					
		</TR>

	    </table>
		<div class="btnhouse">
	   <div class="ltbtns">
		<?php echo $this->submitform->Submit;?>
	   </div>
	   <div class="rtbtns">
		<a href="<?php echo $this->baseUrl();?>/institution"><input type = "button" name = "Back" value = "<?php echo $this->translate('Back'); ?>"></a>
	   </div>
        </div>
	    <input type = "hidden" name = "id" value = "<?php echo $this->id; ?>">
	</form>
</fieldset>
