<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form name="editform" action="<?php echo $this->baseUrl();?>/institution/index/editinstitution" method="POST">
<fieldset>
    	<table id="hor-minimalist-b"> 
<tr><Th colspan="2"><b><?php echo $this->translate('Edit institution'); ?></b><a href="<?php echo $this->baseUrl();?>/institution/index/deleteinstitution/id/<?php echo $this->id;?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="20" height="20" align="right"></a></Th></tr>
            <?php echo $this->form;?>
        </table>
        <div class="btnhouse">
	    	<div class="ltbtns">
				<input type="submit" name="Update" id="Update" value="<?php echo $this->translate('Update'); ?>">
	   		</div>
	   		<div class="rtbtns">
				<a href="<?php echo $this->baseUrl();?>/institution"><input type = "button" name = "Back" value = "<?php echo $this->translate('Back'); ?>"></a>
	   		</div>
        </div>
		<input type="hidden" name="id" value="<?php echo $this->id;?>">
</fieldset>	
</form>

