<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

    <fieldset>
        <legend>Search</legend>
            <div class="cont-rgt-data">
                <form action="<?php echo $this->baseUrl();?>/index" method="POST">
                    <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                        <tr>
                            <td>From Account Number</td>
                            <td><?php echo $this->form->member_id;?></td>
                        </tr>
                        <tr>
                            <TD colspan = "2"><?php echo $this->form->Search;?></TD>
                        </tr>
                    </table>
                </form>
            </div>
    </fieldset>