<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script>
 <link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />


<script type="text/javascript">
$(document).ready(function() {
    $("#search_meeting_date").datepicker({"dateFormat":"dd/mm/yy"});
});
</script>


<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate("Search"); ?></legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/attendanceindex/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label"><?php echo $this->translate("Meeting name"); ?></td>
                                    <td ><?php echo $this->form->search_meeting_name_att;?></td>
                                    <td class="label"><?php echo $this->translate("Meeting date"); ?>:</td>
                                    <td ><?php echo $this->form->search_meeting_date;?></td>
                                </tr>

                        </table>
			<div class="btnhouse">
				<div class="ltbtns">
				<input type="Submit" name="Search" value="<?php echo $this->translate('Search'); ?>">
				</div>
			</div>
                    </form>	
            </div>
    </fieldset> 
</div> 

<table id="hor-minimalist-b" summary="">
	<tr class="tdbrownheading">
		<th><?php echo $this->translate('Meeting name'); ?></th>
		<th><?php echo $this->translate('Meeting date'); ?></th>
	</tr>
		<?php if (count($this->paginator)): 
		$convertdate = new Creditline_Model_dateConvertor();?>
		<?php foreach ($this->paginator as $attendance ): ?>
	<tr>
		
		<td><a href="<?php echo $this->baseUrl();?>/attendancecommonview/index/index/attendance_id/<?php echo$attendance['attid']; ?>"><?php echo $this->escape($attendance['name']);?></a></td>
		<td><?php echo $this->escape($convertdate->phpnormalformat($attendance['meeting_date'])); ?></td>
			<?php endforeach; ?>
			<?php endif; ?>
		
		<tr>
			<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
						'/partials/my_pagination_control.phtml'); ?></div></td>
		</tr>
	</tr>
</table>

