<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<head>
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset-min.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/styles.css" />
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker.js"></script>
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/datepicker1.js"></script> 
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/js/themes/base/ui.all.css" />


<script>
$(document).ready(function() {
    $("#loanAccountdate").datepicker({"dateFormat":"dd/mm/yy"});
});
</script>
</head> 




    <div id="ourbanklogo">
      <h1><a href="#" title="OurBank">OurBank</a></h1>
    </div>
    <div id="welcomebar"><span class="welcomusr">Welcome <a href="#"><?php echo $this->username;?></a></span> <span class="longdate"><?php echo date("r");?></span><span class="signout"><a href="<?php  echo $this->baseUrl();?>/index/logout">signout</a></span>
    </div>

    <div id="navigation">
      <div id="mainmenu">
     <ul>
	<li><a href="<?php  echo $this->baseUrl();?>/creditlinemain"><span>Creditline</span></a></li>
	<li class="selected"><a href="<?php  echo $this->baseUrl();?>/accounting"><span>Accounting</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/transaction"><span>Transaction</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/reports"><span>Reports</span></a></li>        
	<li><a href="<?php  echo $this->baseUrl();?>/meetingmain"><span>Meeting</span></a></li>
        <li><a href="<?php  echo $this->baseUrl();?>/membership"><span>Membership</span></a></li>
	<li><a href="<?php  echo $this->baseUrl();?>/management"><span>Management</span></a></li>
        <!--<li><a href="<?php  echo $this->baseUrl();?>/settings"><span>Setting</span></a></li>-->
        </ul>
      </div>
      <div id="submenu">
        <ul>
	   <?php if($this->pageTitle == "Account") { ?>
	   	<li class="selected"><a href="<?php echo $this->baseUrl();?>/account">Loans</a></li>
	   <?php } else { ?>
	   	<li><a href="<?php echo $this->baseUrl();?>/account">Loans</a></li>
	   <?php } ?>
	   
        </ul>
      </div>
    </div>


