<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<link type="image/x-icon" href="<?php echo $this->baseUrl();?>/images/linklog.jpeg" rel="shortcut icon"/>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery-1.2.3.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/runonload.js"></script>
<!--<script src="<?php echo $this->baseUrl();?>/js/member/jqueryval.js"></script>-->
<script language="JavaScript" src="<?php echo $this->baseUrl();?>/js/member/jquery.autotab.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery-1.1.3.1.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery.history_remote.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/jquery.tabs.pack.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/member/member.js"></script>

<script src="<?php echo $this->baseUrl();?>/js/member/groups.js"></script>

<title><?php echo $this->escape($this->title); ?></title>

<script src="<?php echo $this->baseUrl();?>/js/member/jquery.tabs.pack.js"></script>
<link href="<?php  echo $this->baseUrl();?>/css/reset-min.css" rel="stylesheet" type="text/css" />
<link href="<?php  echo $this->baseUrl();?>/css/styles.css" rel="stylesheet" type="text/css" />



<link rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/js/member/jquery.tabs.css" /> 
<link rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/js/member/themes/base/ui.all.css" />
<?php echo $this->jQuery(); ?>
</head>
<body>
<?php if($this->modId==2) { ?>

<div id="container">

	<div id="header"><?php echo $this->render('membershipheader.phtml'); ?></div>
	
		<div id="leftnavig">
		
		<?php if($this->pageTitle == "Individual address details" or $this->pageTitle == "Individual contact details") { ?>
			<h4><a href="#">Individual member</a></h4>
			<ul>
			<li><a href="<?php  echo $this->baseUrl();?>/individual"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/membername/index"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New Individual</a></li>
			</ul>
		<?php } ?>

		<?php if($this->pageTitle == "Individualm address details" or $this->pageTitle == "Individualm contact details") { ?>
			<h4><a href="#">Individual member</a></h4>
    <ul>
	<li><a href="<?php  echo $this->baseUrl();?>/individualm"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
      <li><a href="<?php  echo $this->baseUrl();?>/individualdefault/index/addmembername"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New individual</a></li>

    </ul>
		<?php } ?>
		
		<?php if($this->pageTitle == "Group address details") { ?>
			<h4><a href="#">Group Member</a></h4>
			<ul>
			<li><a href="<?php  echo $this->baseUrl();?>/group/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/groupdefault/index"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New group</a></li>
			</ul>
		<?php } ?>

            <?php if($this->pageTitle == "Groupm address details") { ?>
            <h4><a href="#">Group</a></h4>
            <ul>
                <li><a href="<?php  echo $this->baseUrl();?>/groupm/index/"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
                <li><a href="<?php  echo $this->baseUrl();?>/groupmdefault/index/addgroup"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New group</a></li>
            </ul>
            <?php } ?>
		
		<?php if($this->pageTitle == "Membership") { ?>
		<h4><a href="#">Membership</a></h4>
		<ul>
			<li class="selected"><a href="<?php  echo $this->baseUrl();?>/individual">Individual</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/group">Group</a></li>
		</ul>
		<?php } ?>
		</div>
				
		<div id="pagecontent">
			<h3><?php echo $this->pageTitle;?></h3>
			<?php echo $this->layout()->content; ?>
		</div>
		
		<div id="footer">
		<div id="copytxt"> Mahiti Infotech Pvt. Ltd., <a href="#">Terms &amp; Conditions</a></div>
		</div>
	</div>
</div>
<?php } ?>
	
<?php if($this->modId==1){ ?>
	<div id="container">
	
		<div id="header"><?php echo $this->render('managementheader.phtml'); ?></div>
		
		<div id="leftnavig">
		
		<?php if($this->pageTitle == "User address details" or $this->pageTitle == "User contact details") { ?>
			<h4><a href="#">User</a></h4>
			<ul>
			<li><a href="<?php  echo $this->baseUrl();?>/user"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/commonviewuser/index/index"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"> User add</a></li>
			</ul>
		<?php } ?>
		
		
		<?php if($this->pageTitle == "Funder address details" or $this->pageTitle=="Funder contact details") { ?>
			<h4><a href="#">Funder</a></h4>
			<ul>
				<li><a href="<?php  echo $this->baseUrl();?>/funder"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64.png" border=0 width="16" height="16">Search</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/funderdetails"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"> New funder</a></li>
			</ul>
		<?php } ?>
		
		<?php if($this->pageTitle == "Bank address details" or $this->pageTitle == "Bank contact details") { ?>
			<h4><a href="#">Bank</a></h4>
			<ul>
					<li><a href="<?php  echo $this->baseUrl();?>/bank"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/bank/index/addbank"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"> New bank</a></li>
			</ul>
		<?php } ?>
		
		<?php if($this->pageTitle == "Institution address details" or $this->pageTitle == "Institution contact details") { ?>
			<h4><a href="#">Institution</a></h4>
			<ul>
			<li><a href="<?php  echo $this->baseUrl();?>/institution"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/institution/index/addinstitution"> <img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16">New institution</a></li>
			</ul>

		<?php } ?>
		
                		<?php if($this->pageTitle == "Office address details" or $this->pageTitle=="Office contact details") { ?>
			<h4><a href="#">Office</a></h4>
	   <ul>
       <li><a href="<?php  echo $this->baseUrl();?>/office"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64" border=0 width="16" height="16">Search</a></li>
     <li><a href="<?php  echo $this->baseUrl();?>/officedefault/index/officeadd"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"> New office</a></li>
   </ul>

		<?php } ?>

		<?php if($this->pageTitle == "Management") { ?>
		<h4><a href="#">Management</a></h4>
			<ul>
			<li ><a href="<?php  echo $this->baseUrl();?>/institution">Institution</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/bank">Bank</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/roles">Roles</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/user">User</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/funder">Funder</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/fundings">Fundings</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/sectors">Sector</a></li>
			<li><a href="<?php  echo $this->baseUrl();?>/activity">Activites</a></li>
			</ul>
		<?php } ?>
		</div>
			<div id="pagecontent">
				<h3><?php echo $this->pageTitle;?></h3>
				<?php echo $this->layout()->content; ?>
			</div>
		
		
		<div id="footer">
		<div id="copytxt"> Mahiti Infotech Pvt. Ltd., <a href="#">Terms &amp; Conditions</a></div>
		</div>
</div>
</div></div>

<?php } ?>
</BODY>
</html>
