<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<head>
<title><?php echo $this->escape($this->title); ?></title>
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/site.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/reset.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/style2.css" />
<link rel="stylesheet" type="text/css"  href="<?php  echo $this->baseUrl();?>/css/wforms.css" />
</head>


<body>
<div id="container">
    <div id="header"><?php echo $this->render('meetingmainheader.phtml'); ?></div>

  <div id="leftnavig">

	<?php if($this->pageTitle == "Community Meetings") { ?>
	<h4><a href="#">Meeting</a></h4>
        <ul>
		<li><a href="<?php  echo $this->baseUrl();?>/meetingindex">Meeting</a></li>
		<li><a href="<?php  echo $this->baseUrl();?>/attendanceindex">Attendance</a></li>
	</ul>
	<?php } ?>
	<?php if($this->pageTitle == "Meetings") { ?>
		<h4><a href="#">Meeting</a></h4>
		<ul>
		<li><a href="<?php  echo $this->baseUrl();?>/meetingindex"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64.png" border=0 width="16" height="16"> Search</a></li>
		<li><a href="<?php  echo $this->baseUrl();?>/meeting/index/meetingadd"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"> Meeting add</a></li>
		</ul>
	<?php } ?>
	
	<?php if($this->pageTitle == "Attendance") { ?>
		<h4><a href="#">Attendance</a></h4>
		<ul>
		<li><a href="<?php  echo $this->baseUrl();?>/attendanceindex"><img src="<?php echo $this->baseUrl(); ?>/images/Button-search-64.png" border=0 width="16" height="16"> Search</a></li>
		<li><a href="<?php  echo $this->baseUrl();?>/attendance/index/attendanceadd"><img src="<?php echo $this->baseUrl(); ?>/images/add.gif" border=0 width="16" height="16"> Attendance add</a></li>
		</ul>
	<?php } ?>
   
  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>


  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>
</html>

