<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?php echo $this->escape($this->title); ?></title>


</head>
<body>
<div id="container">

    <div id="header"><?php echo $this->render('transactionheaderg.phtml'); ?></div>

  <div id="leftnavig">


        <?php if($this->pageTitle == "Transaction") { ?>
	<h4><a href="#">Transaction</a></h4>
        <ul>
           <li ><a href="<?php echo $this->baseUrl();?>/savingswithdrawal">Savings</a></li>
           <li ><a href="<?php echo $this->baseUrl();?>/fixedtransaction">Fixed savings</a></li>
	   <li ><a href="<?php echo $this->baseUrl();?>/recurringtransaction">Recurring savings</a></li>
	   <li ><a href="<?php echo $this->baseUrl();?>/loandisbursmentg">Loans</a></li>
	</ul>
	<?php } ?>
        <?php if($this->type == "savings") { ?>
		<h4><a href="#">Transaction</a></h4>
		<ul>
            <li><a href="<?php echo $this->baseUrl();?>/savingswithdrawal">Saving withdrawal</a></li>
            <li><a href="<?php echo $this->baseUrl();?>/savingsdeposit">Saving deposit</a></li>
            <li><a href="<?php echo $this->baseUrl();?>/psdetails">Saving details</a></li>
                </ul>
	<?php } ?>
	<?php if($this->type == "loans") { ?>
	<h4><a href="#">Transaction</a></h4>
	<ul>
            <li><a href="<?php echo $this->baseUrl();?>/loandisbursmentg">Loan disbursment </a></li>
            <li><a href="<?php echo $this->baseUrl();?>/loanrepaymentg">Loan repayment </a></li>
            <li><a href="<?php echo $this->baseUrl();?>/loandetailsg">Loan details </a></li>
       </ul>
                </ul>
	<?php } ?>

        <?php if($this->type == "recurring") { ?>
	<h4><a href="#">Transaction</a></h4>
	<ul>
	   <li ><a href="<?php echo $this->baseUrl();?>/recurringtransaction">Recurring transaction</a></li>
       </ul>
                </ul>
	<?php } ?>

        <?php if($this->type == "fixed") { ?>
	<h4><a href="#">Transaction</a></h4>
	<ul>
            <li ><a href="<?php echo $this->baseUrl();?>/fixedtransaction">Fixed transaction</a></li>
       </ul>
                </ul>
	<?php } ?>


  </div>

    <div id="pagecontent">
        <h3><?php echo $this->pageTitle;?></h3>
        <?php echo $this->layout()->content; ?>
    </div>


  <div id="footer">
    <?php echo $this->render('footer.phtml'); ?>
  </div>
</div>
</BODY>

</html>

