<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<table  id="hor-minimalist-b">
		<TR>
			<TH class = "firsttd">Graceperiod Information</TH>
			<TH class = "secondtd"></TH>
			<TH class = "thirdtd"><a href="<?php echo $this->baseUrl();?>/graceperiod/index/graceperiodedit/graceperiod_id/<?php echo $this->id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></TH>
		</TR>
	<?php foreach($this->viewgracedetails as $viewgracedetails) { ?>
		
		
		<TR >
			<TD class = "firsttd">Name</TD>
			<TD class = "secondtd"><?php echo $viewgracedetails['name'];?></TD>
			<TD class = "thirdtd"></TD>
		</TR>
		<TR >
			<TD class = "firsttd">Days</TD>
			<TD class = "secondtd"><?php echo $viewgracedetails['days'];?></TD>
			<TD class = "thirdtd"></TD>
		</TR>
		<TR >
			<TD class = "firsttd">Creditline Name</TD>
			<TD class = "secondtd"><?php echo $viewgracedetails['creditline_name'];?></TD>
			<TD class = "thirdtd"></TD>
		</TR>
		<TR >
			<TD class = "firsttd">Active</TD>
			<TD class = "secondtd"><?php if($viewgracedetails['status']) echo "Yes"; else echo "No";?></TD>
			<TD class = "thirdtd"></TD>
		</TR>
	<?php } ?>

</table>

<div class="btnhouse">
	<div class="ltbtns">
	
	</div>
	<div class="rtbtns">
	<a href="<?php echo $this->baseUrl();?>/graceperiodindex"><input type="button" value="Back"></a>
	</div>
</div>	

