<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/membershipgroupedit.js"></script>
<fieldset>
    <legend>Edit group</legend>
    <form action="<?php echo $this->baseUrl();?>/groupdefault/index/editgroup/id/<?echo $this->groupid;?>" method="POST">
        <div class="btnhouse">
            <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/groupdefault/index/deletegroup/id/<? echo $this->groupid;?>">
                    <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a>
            </div>
        </div>
        <table  class="fieldsets">
            <TR >
                <td><label for="fld1" class="mand">Branch name:</td>
                <TD><?php echo $this->form->office;?></TD>
            </TR>	  
            <TR >		
                <TD ><?php echo $this->form->groupname;?></span></TD>
            </TR>
            <TR >
                <TD><?php echo $this->form->Created_Date;?></TD></TD>
            </TR>
        </table>
        <table class="fieldsets">
            <TR id="membersdiv">
            </TR>
        </table>

        <div class="btnhouse">
            <div class="ltbtns">
                <?php echo $this->form->Submit;?>
            </div>
            <div class="rtbtns">
                <a href="<?php echo $this->baseUrl();?>/groupcommonview/index/commonview/id/<?echo $this->groupid; ?>"><?php echo $this->form->Back;?></a>
            </div>
        </div>
        <?php if($this->error) { echo "<font color = 'red'><b>You are wrongly chosen group head , please chose again</b>"; } ?>
    </form>
</fieldset>