<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<?php if($this->assignMembers) { 
   $head = $this->grouphead;   ?>
      <TABLE BORDER WIDTH=50% class="fieldsets">
	 <tr><th>Group members</th><th> Group head</th></tr>
            <? foreach($this->assignMembers as $members) {?>
            <TR>
                <td width="25%">
                    <input type="checkbox"  name="member_id[]" id = "member_id[]"  checked="true"  value="<?php echo $members["id"];?>" ><? echo $members["member_name"];?>
                </td>
                <td width="25%">
                    <input type="radio" name="memberhead"   id="memberhead" <? if($head == $members["id"]) { ?> checked="true" <? } ?> value="<?php echo $members["id"];?>">
                </td>
            </TR>
		<? }?>
		 <? foreach($this->members as $members) {?>
            <TR>
                <td width="25%">
                    <input type="checkbox"  name="member_id[]" id = "member_id[]"    value="<?php echo $members["id"];?>" ><? echo $members["member_name"];?>
                </td>
                <td width="25%">
                     <input type="radio" name="memberhead"   id="memberhead"  value="<?php echo $members["id"];?>">
                </td>
 		</TR>
		<? }?>
            </table>
	    <?php }    
 else {
        echo "<font color='RED'>No Members in the branch you seleted</font>";
 } ?>