<script type="text/javascript" language="JavaScript1.3">
function getXMLHTTP() { //fuction to return the xml http object
    var xmlhttp=false;	
        try {
            xmlhttp=new XMLHttpRequest();
        }
        catch(e) {	
            try {
              xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
            }
       catch(e){
            try{
             xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
            }
       catch(e1) {
            xmlhttp=false;
            }
        }
    }
        return xmlhttp;
    }

    
function getMember(branch_id,path) {	
		if(branch_id != '') { 
			var strURL = path+"/groupdefault/index/getmembersadd?branch_id="+branch_id;  
				var req = getXMLHTTP();
				if (req) {
					req.onreadystatechange = function() {
					if (req.readyState == 4) {   // only if "OK"
					if (req.status == 200) {	
				
						document.getElementById('membersdiv').innerHTML=req.responseText;							
					} else {
							alert("There was a problem while using XMLHTTP:\n" + req.statusText);
						}
					}
						}	
					req.open("GET", strURL, true);
					req.send(null);
					}
		}
		else
		{
			alert('Chose any Branch...')
		}
    }

		$(document).ready(function()
		{
			$("form").submit(function()
			{
				if (!isCheckedById("selector"))
				{
					alert ("Please select at least one member / No Members in the group");
					return false;
				}				
			
				else
				{
					return true; //submit the form
				}				
			});
			
			function isCheckedById(id)
			{
				var checked = $("input[@id="+id+"]:checked").length;
				if (checked == 0)
				{
					return false;
				}
				else
				{
					return true;
				}
			}
		});
	
	$(document).ready(function()
		{
			$("form").submit(function()
			{
				if (!isCheckedById("memberhead"))
				{
					alert ("Please select group head");
					return false;
				}				
			
				else
				{
					return true; //submit the form
				}				
			});

	
			function isCheckedById(id)
			{
				var checked = $("input[@id="+id+"]:checked").length;
				if (checked == 0)
				{
					return false;
				}
				else
				{
					return true;
				}
			}
		});

		function valid()
		{
	
		var groupname = document.getElementById('groupname').value;
	
		var createdate =  document.getElementById('Created_Date').value;

		//var members[] = document.getElementById('selector').value;
		



/*
for(var i=0;i<members.length;i++){
document.write("<b>members["+i+"] is </b>=>"+members[i]+"<br>");
}*/


		if(groupname == "")
		{
			
 			alert("Would you please enter group name?")
 			return false;
		}
		
		if(createdate == "")
		{
			alert("Would you please enter date?")	
			return false;
		}
		return true;
// 		
 		}
	</script>
               
<div id = "searchDiv">
<fieldset>
<legend>Group details</legend>
<form action="<?php echo $this->baseUrl();?>/groupdefault/index/groupaccount" method="POST" onsubmit="return valid()">
		 <table class="fieldsets"> 

			<TR>
				<TD><label for="fld1" class="mand">Branch name:</td>
				<TD><?php echo $this->form->office;?></TD>
			</TR>	
			<TR>		
				<TD><label for="fld1" class="mand">Group name:</td>
				<TD><?php echo $this->form->groupname;?></TD>
			</TR>

			<TR>
				<TD><label for="fld1" class="mand">Created date:</TD>
				<TD ><?php echo $this->form->Created_Date;?></TD></TD>
		        </TR>

		</table><br/>
		<table class="fieldsets">
			<TR id="membersdiv">
				
				
			</TR>
                  </table>
		<div class="btnhouse">
			<div class="ltbtns">
			<?php echo $this->form->Submit;?>
			</div>
			<div class="rtbtns">
			<a href="<?php echo $this->baseUrl();?>/group/index"><?php echo $this->form->Back;?></a>
			</div>
		</div>
	</form>
</fieldset>
</div>
<?php if($this->error) { echo "<font color = 'red'><b>You are wrongly chosen group head , please chose again</b>"; } ?>


