<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div id="searchDiv">
    <fieldset>
        <legend><?php echo $this->translate('test'); ?>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/attendance/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Meeting Name</td>
                                    <td ><? echo $this->form->field1;?></td>
                                    <td class="label">Meeting Dates:</td>
                                    <td ><? echo $this->form->field2;?></td>
                                </tr>

                                <tr>
                                    <td colspan="4" align="center"><? echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 

<fieldset>
	<legend><?php echo $this->translate('Attendance'); ?></legend>
	<table id="hor-minimalist-b" summary="">
		<tr class="tdbrownheading">
		<th><?php echo $this->translate('Meeting Name'); ?></th>
		<th><?php echo $this->translate("Member's Name"); ?></th>
		</tr>
			<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $attendance ): ?>
		<tr>
			
			<td><a href="<?php echo $this->baseUrl()."/attendance/index/attendanceview/attendance_id/".$attendance['attendance_id']; ?>"><?php echo $this->escape($attendance['meeting_id']);?></a></td>
			<td><?php echo $this->escape($attendance['meeting_date']); ?></td>
				<?php endforeach; ?>
				<?php endif; ?>
			
			<tr>
				<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
							'/partials/my_pagination_control.phtml'); ?></div></td>
			</tr>
		</tr>
	</table>
</fieldset>