<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/loandisbursereport/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Credit Line:</td>
                                    <td ><?php echo $this->form->field1;?></td>
                                    <td class="label">Bank Name:</td>
                                    <td ><div id="groupDiv"><?php echo $this->form->field2;?></div></td>
                                </tr>

                                <tr>
                                    <td colspan="4" align="center"><?php echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 








<?php if($this->check) { ?>
<fieldset>
        <legend>Loan Disbursement</legend>
	<h3>
		<font color=red>Creditline Name :</font> <?php echo $this->creditline_name;?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<font color=red>Amount : </font> <?php echo $this->creditline_portfolio;?>
	</h3>


<table id="hor-minimalist-b">
    <tr>
      	<th>Disburse Number</th>
	<th>amount_disbursed </th>
    </tr>
        <?php $totalDisbursed = 0; if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $disburse ) { ?>
    	<tr>
		<td><?php echo $this->escape($disburse['loandisbursement_id']);?></td> 
		<td><?php echo $this->escape($disburse['amount_disbursed']);?></td> 
		
	<?php $totalDisbursed+=$disburse['amount_disbursed'];} ?>
	<?php endif; ?>
    	</tr>
	<tr>
		<TD>Total</TD><TD><?php echo $totalDisbursed; ?></TD><TD></TD>
	</tr>
    <tr>
		<td colspan="6" align="right">
			<div class="pagination">
				<?php echo $this->paginationControl($this->paginator,'Sliding',
						'/partials/my_pagination_control.phtml'); ?>
			</div>
		</td>
		</tr>
</table>

</fieldset>
<?php } ?>


