<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<?php if($this->savings) { ?>
<div style="float:left;width:380px">
<fieldset>
    <legend>Receipt List</legend>
            <?php $amountCredit = "0";
		$openingamountCredit = "0";
		$openingamountDebit = "0";
              $amountDebit = "0";
            ?>
    <table id="hor-minimalist-b">
        <TR>
            <TH >Receipt</TH>
            <TH class = "label">Amount</TH>
        </TR>
        <?php foreach($this->savingsCredit as $savingsCredit) { ?>
        <TR>

            <TD ><?php echo $savingsCredit->offerproductname ?></TD>
            <TD align = "right"><?php echo $savingsCredit->savingcredit; 
            $amountCredit = $amountCredit + $savingsCredit->savingcredit; ?></TD>
        </TR>
        <?php } ?>



        <!-- 
        //opening Balance
        -->
        <TR>
            <TD ><B>Opening Balance</B></TD>
            <TD align = "right" ></TD>
        </TR>

        <?php foreach($this->openingsavingsCredit as $openingsavingsCredit) { ?>
        <TR>

            <TD ><?php //echo $openingsavingsCredit->offerproductname ?></TD>
            <TD align = "right"><?php echo $openingsavingsCredit->openingBalance;
            $openingamountCredit = $openingamountCredit + $openingsavingsCredit->openingBalance; ?></TD>
        </TR>
        <?php } ?>


        
             <TD ><b>Total</B></TD>
             <?php if($openingamountCredit + $amountCredit != "0") { ?>
             <TD align = "right" ><B><?php echo sprintf("%4.2f", $openingamountCredit + $amountCredit); ?></B></TD>
             <?php } else { ?>
             <TD align = "right" ><B>----</B></TD>
             <?php } ?>
        </TR>
    </table>


<form action="<?php echo $this->baseUrl();?>/reports/receiptspayments/pdftransaction" method="POST"
onClick="window.open('/ourbank/public/reports/receiptspayments/reportdisplay/file/ReceiptsPayments.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">
            <input type="hidden" name="field1" value="<?php echo $this->field1; ?>">
            <input type="hidden" name="field2" value="<?php echo $this->field2;?>">
            <input type="submit" value="PDF" id="submit">
</form>
<fieldset>
</div>
<div style="float:left;width:380px">
<fieldset>
    <legend>Payments List</legend>
    <table id="hor-minimalist-b">
        <TR>

            <TH >Payments</TH>
            <TH class = "label">Amount</TH>
        </TR>
        <?php foreach($this->savingsDebit as $savingsDebit) { ?>
        <TR>

            <TD ><?php echo $savingsDebit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $savingsDebit->savingdebit; 
            $amountDebit = $amountDebit + $savingsDebit->savingdebit; ?></TD>
        </TR>
        <?php } ?>

        
        <!-- 
            Closing Balance 
        -->
        <TR>
            <TD ><B>Closing Balance</B></TD>
            <TD align = "right" ></TD>
        </TR>


        <?php foreach($this->openingsavingsDebit as $openingsavingsDebit) { ?>
        <TR>

            <TD ><?php //echo $openingsavingsDebit->offerproductname ?></TD>
            <TD align = "right"><?php  echo ($openingamountCredit + $amountCredit) - $amountDebit?></TD>
        </TR>
        <?php } ?>




        <TR>
             <TD ><b>Total</b></TD>
             <?php if($openingamountDebit + $amountDebit != "0") { ?>
             <TD align = "right" ><B><?php echo sprintf("%4.2f", (($openingamountCredit + $amountCredit) - $amountDebit) + $amountDebit); ?></B></TD>
             <?php } else { ?>
             <TD align = "right" ><B>----</B></TD>
             <?php } ?>
        </TR>
    </table>
</div>
</fieldset>

<?php } else {?>

<fieldset>
    <legend> search </legend>
        <div class="cont-rgt-data">
            <table id="hor-minimalist-b">
                <form action="<?php echo $this->baseUrl();?>/reports/receiptspayments" method="POST">
                    <TR>
                            <TD >Date From</TD>
                            <TD ><?php echo $this->form->field1;?></TD>
                            <TD >Date To</TD>
                            <TD ><?php echo $this->form->field2;?></TD>
                    </TR>
                    <TR>
                            <TD ></TD>
                            <TD ></TD>
                            <TD ></TD>
                            <TD ><?php echo $this->form->Search;?></TD>
                    </TR>

                </form>
            </table>
        </div>
</fieldset>


<?php } ?>


