<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<?php if($this->savings) { ?>
<div style="float:left;width:380px">
<fieldset>
    <legend>Receipt List</legend>
            <?php $amountCredit = "0";
              $amountDebit = "0";
            ?>
    <table id="hor-minimalist-b">
        <TR>
            <TH >Receipt</TH>
            <TH class = "label">Amount</TH>
        </TR>
        <?php foreach($this->savingsCredit as $savingsCredit) { ?>
        <TR>

            <TD ><?php echo $savingsCredit->offerproductname ?></TD>
            <TD align = "right"><?php echo $amountCredit = $savingsCredit->savingcredit?></TD>
        </TR>
        <?php } ?>

        <?php foreach($this->fixedCredit as $fixedCredit) { ?>
        <TR>

            <TD ><?php echo $fixedCredit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $fixedCredit->fixedcredit;
            $amountCredit = $amountCredit + $fixedCredit->fixedcredit; ?></TD>
        </TR>
        <?php } ?>
        <?php foreach($this->recurringCredit as $recurringCredit) { ?>
        <TR>

             <TD ><?php echo $recurringCredit->offerproductname ?></TD>
             <TD align = "right" ><?php echo $recurringCredit->recurringcredit;
             $amountCredit = $amountCredit + $recurringCredit->recurringcredit; ?></TD>
        </TR>
        <?php } ?>
        <?php foreach($this->laonCredit as $laonCredit) { ?>
        <TR>

            <TD ><?php echo $laonCredit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $laonCredit->loancredit;
            $amountCredit = $amountCredit + $laonCredit->loancredit; ?></TD>
        </TR>
        <?php } ?>
        <TR>

        <!-- 
        //opening Balance
        -->
        <TR>
            <TD ><B>Opening Balance</B></TD>
            <TD align = "right" ></TD>
        </TR>

        <?php foreach($this->openingsavingsCredit as $openingsavingsCredit) { ?>
        <TR>

            <TD ><?php echo $openingsavingsCredit->offerproductname ?></TD>
            <TD align = "right"><?php echo $openingamountCredit = $openingsavingsCredit->openingsavingcredit?></TD>
        </TR>
        <?php } ?>

        <?php foreach($this->openingfixedCredit as $openingfixedCredit) { ?>
        <TR>

            <TD ><?php echo $openingfixedCredit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $openingfixedCredit->openingfixedcredit;
            $openingamountCredit = $openingamountCredit + $openingfixedCredit->openingfixedcredit; ?></TD>
        </TR>
        <?php } ?>
        <?php foreach($this->openingrecurringCredit as $openingrecurringCredit) { ?>
        <TR>

             <TD ><?php echo $openingrecurringCredit->offerproductname ?></TD>
             <TD align = "right" ><?php echo $openingrecurringCredit->openingrecurringcredit;
             $openingamountCredit = $openingamountCredit + $openingrecurringCredit->openingrecurringcredit; ?></TD>
        </TR>
        <?php } ?>
        <?php foreach($this->openinglaonCredit as $openinglaonCredit) { ?>
        <TR>

            <TD ><?php echo $openinglaonCredit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $openinglaonCredit->openingloancredit;
            $openingamountCredit = $openingamountCredit + $openinglaonCredit->openingloancredit; ?></TD>
        </TR>
        <?php } ?>
        <TR>
        
             <TD ><b>Total</B></TD>
             <?php if($openingamountCredit + $amountCredit != "0") { ?>
             <TD align = "right" ><B><?php echo sprintf("%4.2f", $openingamountCredit + $amountCredit); ?></B></TD>
             <?php } else { ?>
             <TD align = "right" ><B>----</B></TD>
             <?php } ?>
        </TR>
    </table>


<form action="<?php echo $this->baseUrl();?>/reports/receiptspayments/pdftransaction" method="POST"
onClick="window.open('/ourbank/public/reports/receiptspayments/reportdisplay/file/ReceiptsPayments.pdf','mywindow','width=1000,height=700,left=100,top=100,screenX=800,screenY=600')">

            <input type="submit" value="PDF" id="submit">
</form>
<fieldset>
</div>
<div style="float:left;width:380px">
<fieldset>
    <legend>Payments List</legend>
    <table id="hor-minimalist-b">
        <TR>

            <TH >Payments</TH>
            <TH class = "label">Amount</TH>
        </TR>
        <?php foreach($this->savingsDebit as $savingsDebit) { ?>
        <TR>

            <TD ><?php echo $savingsDebit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $amountDebit = $savingsDebit->savingdebit?></TD>
        </TR>
        <?php } ?>

        <?php  foreach($this->fixedDebit as $fixedDebit) { ?>
        <TR>

            <TD ><?php echo $fixedDebit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $fixedDebit->fixeddebit; 
            $amountDebit = $amountDebit + $fixedDebit->fixeddebit; ?></TD>
        </TR>
        <?php } ?>
         <?php foreach($this->recurringDebit as $recurringDebit) { ?>
        <TR>

            <TD ><?php echo $recurringDebit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $recurringDebit->recurringdebit;
            $amountDebit = $amountDebit + $recurringDebit->recurringdebit; ?></TD>
                            
        </TR>
        <?php } ?>
         <?php  foreach($this->loanDebit as $loanDebit) { ?>
         <TR>

            <TD ><?php echo $loanDebit->offerproductname ?></TD>
            <TD align = "right"><?php echo $loanDebit->loandebit;
            $amountDebit = $amountDebit + $loanDebit->loandebit; ?></TD>
         </TR>
         <?php } ?>
        <!-- 
            Closing Balance 
        -->
        <TR>
            <TD ><B>Closing Balance</B></TD>
            <TD align = "right" ></TD>
        </TR>


        <?php foreach($this->openingsavingsDebit as $openingsavingsDebit) { ?>
        <TR>

            <TD ><?php echo $openingsavingsDebit->offerproductname ?></TD>
            <TD align = "right"><?php echo $openingamountDebit = $openingsavingsDebit->openingsavingdebit?></TD>
        </TR>
        <?php } ?>

        <?php foreach($this->openingfixedDebit as $openingfixedDebit) { ?>
        <TR>

            <TD ><?php echo $openingfixedDebit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $openingfixedDebit->openingfixeddebit;
            $openingamountDebit = $openingamountDebit + $openingfixedDebit->openingfixeddebit; ?></TD>
        </TR>
        <?php } ?>
        <?php foreach($this->openingrecurringDebit as $openingrecurringDebit) { ?>
        <TR>

             <TD ><?php echo $openingrecurringDebit->offerproductname ?></TD>
             <TD align = "right" ><?php echo $openingrecurringDebit->openingrecurringdebit;
             $openingamountDebit = $openingamountDebit + $openingrecurringDebit->openingrecurringdebit; ?></TD>
        </TR>
        <?php } ?>
        <?php foreach($this->openingloanDebit as $openingloanDebit) { ?>
        <TR>

            <TD ><?php echo $openingloanDebit->offerproductname ?></TD>
            <TD align = "right" ><?php echo $openingloanDebit->openingloandebit;
            $openingamountDebit = $openingamountDebit + $openingloanDebit->openingloandebit; ?></TD>
        </TR>
        <?php } ?>
        <TR>


        <TR>
             <TD ><b>Total</b></TD>
             <?php if($openingamountDebit + $amountDebit != "0") { ?>
             <TD align = "right" ><B><?php echo sprintf("%4.2f", $openingamountDebit + $amountDebit); ?></B></TD>
             <?php } else { ?>
             <TD align = "right" ><B>----</B></TD>
             <?php } ?>
        </TR>
    </table>
</div>
</fieldset>

<?php } else {?>

<fieldset>
    <legend> search </legend>
        <div class="cont-rgt-data">
            <table id="hor-minimalist-b">
                <form action="<?php echo $this->baseUrl();?>/reports/receiptspayments" method="POST">
                    <TR>
                            <TD >Date From</TD>
                            <TD ><?php echo $this->form->field1;?></TD>
                            <TD >Date To</TD>
                            <TD ><?php echo $this->form->field2;?></TD>
                    </TR>
                    <TR>
                            <TD ></TD>
                            <TD ></TD>
                            <TD ></TD>
                            <TD ><?php echo $this->form->Search;?></TD>
                    </TR>

                </form>
            </table>
        </div>
</fieldset>


<?php } ?>


