<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->



		<table id="hor-minimalist-b" summary="">
			<tr class="tdbrownheading">
				<th>Interest category</th>
				<th>Creditline</th>
				<th></th>
				<th>Loan start range (R$)</th>
				<th>Loan end range (R$)</th>
				<th>Interest (%)</th>
				<th>Fee (%)</th>
				<th>Billet (R$)</th>
				<th><a href="<?php echo $this->baseUrl();?>/interestrates/index/interestratesedit/interest_id/<?php echo $this->interest_id; ?>"><img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="20" height="20"></a></th>
			</tr>
			<?php $a='';?>
			<?php foreach ($this->fetchinterest as $interest ){ ?>
			<tr>
			<? if($a!=$interest['id']) { ?>
			
				<td><?php echo $this->escape($interest['name']);?></td>
				<td><?php echo $this->escape($interest['creditline_name']);?></td>
				<td></td>
			<? } else {
				echo "<td></td><td></td><td></td>";
			} ?>
				
				<td><?php echo $this->escape($interest['start_range']);?></td>
				<td ><?php echo $this->escape($interest['end_range']);?></td>
				<td ><?php echo $this->escape($interest['rate']);?></td>
				<td ><?php echo $this->escape($interest['fee']);?></td>
				<td ><?php echo $this->escape($interest['ballet']);?></td>
				<td></td>
			</tr>
				<?php $a=$interest['id'];
			} ?>
		</table>
<div class="btnhouse">
			<div class="ltbtns">
				
			</div>
			<div class="rtbtns">
				<a href="<?php echo $this->baseUrl();?>/interestratesindex"><input type="button" value="Back"></a>
			</div>
</div>
