<script type="text/javascript">
       function getSavingAccount(checkvalue) { 
        if (checkvalue == 'ps'){ 
            targeturl='<?php echo $this->baseUrl();?>/savings/index/persnolsavings'; 
            } 
        else if (checkvalue == 'fd'){
            targeturl='<?php echo $this->baseUrl();?>/savings/index/fixedsavings'; 
            }
        else if (checkvalue == 'rd'){
            targeturl='<?php echo $this->baseUrl();?>/savings/index/recurringsavings';  
            }
        $.ajax({ url: targeturl, success: function(data){ $('#savingdiv').html(data) }});
       }
</script> 
<div class="searchDiv">
  <fieldset>
        <legend>New savings</legend>
	<form action="<?php echo $this->baseUrl();?>/savings/index/savingsadd" method="POST"  name= "myform">
            <table class="fieldsets">
                <TR >
                    <TD>Product type</TD>
                    <TD><?php echo $this->form->productType;?></TD>
                </TR>
                <tr><TD  colspan="2" id="savingdiv"></TD></tr>
            </table>
           
            <div class="btnhouse">
                <div class="ltbtns">
                    <input type = "Submit" name = "Submit" id="Submit" value = "Submit"/>
                </div>
                <div class="rtbtns">
                    <a href="<?php echo $this->baseUrl();?>/management/savings/"><input type = "Button" name = "Back" id="Back" value = "Back"/></a>
                </div>
            </div>
        </form>
   </fieldset>
</div>
