<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/management/loans" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Sectors :</td>
                                    <td ><? echo $this->form->field1;?></td>
                                    <td class="label">Activity :</td>
                                    <td ><? echo $this->form->field2;?></td>
                                </tr>
                                <tr>
                                    <td class="label">Begin date :</td>
                                    <td ><? echo $this->form->field4;?></td>
                                    <td class="label">Close date :</td>
                                    <td ><? echo $this->form->field6;?></td>
                                </tr>
                                <tr>
                                    <td colspan="4" align="center"><? echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div>  
<fieldset>
        <legend>Activities</legend>
<table id="hor-minimalist-b">
    <tr>
        <th>Activities</th>
        <th>Sectors</td>
        <th>Begin date</td>
        <th>Close date</th>
        <th>edit</td>
        <th>delete</th>
    </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $loan ): ?>
    <tr>
        <td><a href="<?php echo $this->baseUrl()."/management/loans/loansview/offerproductupdate_id/".$loan['offerproductupdate_id']; ?>">
                     <?php echo $this->escape($loan['offerproductname']); ?></a></td>
    <td><?php echo $this->escape($loan['productname']);?></td>
    <td><?php echo $this->escape($loan['begindate']);?></td>
    <td><?php echo $this->escape($loan['closedate']);?></div></td>
    <td><a href="<?php echo $this->baseUrl();?>/management/loans/loansedit/offerproductupdate_id/<?php echo $loan['offerproductupdate_id'];?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></td>
    <td><a href="<?php echo $this->baseUrl();?>/management/loans/loansdelete/offerproductupdate_id/<?php echo $loan['offerproductupdate_id'];?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
        <?php endforeach; ?>
        <?php endif; ?>
    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                    '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>
       <td colspan="8"><a href="<?php  echo $this->baseUrl();?>/management/loans/loansadd"> <input name="submit" type="submit" class="NormalBtn" value="New Activity"></a></td>
    </tr>
</table>
</fieldset>