<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->



<fieldset>
    <legend>New Activity</legend>
        <div class="register">
            <div class="profile_tab">
                <form action="<?php echo $this->baseUrl();?>/management/loans/loansadd" method="POST"  name= "myform">
                    <table id="hor-minimalist-b">
                        <TR>
                            <TH>Activity Details</TH>
                            <TH></TH>
                            <TH></TH>
                            <TH></TH>
                        </TR>
                        <TR>
                            <TD>Sector Type<span class="reqMark">*</span></TD>
                            <TD><?php echo $this->form->product_id;?></TD>
                            <TD></TD>
                            <TD></TD>
                        </TR>
                        <TR>
                            <TD>Activity Name<span class="reqMark">*</span></TD>
                            <TD><?php echo $this->form->offerproductname;?></TD>
                            <TD>Short Name<span class="reqMark">*</span></TD>
                            <TD><?php echo $this->form->offerproductshortname;?></TD>
                        </TR>
                        <TR>
                            <TD>Description<span class="reqMark">*</span></TD>
                            <TD><?php echo $this->form->offerproduct_description;?></TD>
                            <TD></TD>
                            <TD></TD>
                        </TR>
                        <TR>
                            <TH>Date</TH>
                            <TH></TH>
                            <TH></TH>
                            <TH></TH>
                        </TR>
                        <tr> 
                            <td>Begin Date<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->begindate;?>
                            <span class="reqMark">[yyyy-mm-dd]</span></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr> 
                            <td>Close Date<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->closedate;?>
                            <span class="reqMark">[yyyy-mm-dd]</span></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr> 
                            <td>Applicable To<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->applicableto;?></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <TR>
                             <TH>Loan Amount</TH>
                             <TH></TH>
                             <TH>Installments</TH>
                             <TH></TH>
                        </TR>
                        <tr> 
                            <td>Minimum Loan Amount<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->minmumloanamount;?></td>
                            <td>Minimum Frequency<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->minimumfrequency;?></td>
                        </tr>
                        <tr> 
                            <td>Maximum Loan Amount<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->maximunloanamount;?></td>
                            <td>Maximum Frequency<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->maximumfrequency;?></td>
                        </tr>
                        <TR>
                             <TH>Penal Fee</TH>
                             <TH></TH>
                             <TH></TH>
                             <TH></TH>
                        </TR>
                        <tr> 
                            <td>Penal Fee(%)<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->penal_Interest;?></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <TR>
                            <TH>Grace Period</TH>
                            <TH></TH>
                            <TH></TH>
                            <TH></TH>
                        </TR>
                        <tr> 
                            <td>Grace Period<span class="reqMark">*</span></td>
                            <td><?php echo $this->form->graceperiodnumber;?>[days]</td>
                            <td><input type="hidden" id="id" value="1">
								<input type="hidden" name="memberCount" id="memberCount" value=""  class="textfield" />	
                          <!--  <table>
                                <tr> 
                                    <Th width="5%">From </Th>
                                    <Th width="2%">To</Th>
                                    <Th width="3%">Rate</Th>
                                </tr>
                                <tr> 
                                    <td width="5%">//<?php echo $this->form->period_ofrange_monthfrom;?></td> 
                                    <td width="2%">//<?php echo $this->form->period_ofrange_monthto;?></td>
                                    <td width="2%">//<?php echo $this->form->Interest;?></Th>
                                </tr>
                               </table><div id="interestperiods"></div>
									<input type="button" onClick="addFormField(); return false;" value="Add interest">
                                                                       -->
                            <td></td>
                        </tr>
                        <tr>
                            <TD><?php echo $this->form->Submit;?></TD>
                            <td><a href="<?php echo $this->baseUrl(); ?>/management/loans">
                                            <input name="submit" type="submit" class="NormalBtn" value="Back"></a></td>
                        </TR>
                </table>
            </form>
        </div>
    </div>
</fieldset>