<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<html>
  <head>
    <script type='text/javascript' src='js/jquery-1.3.2.js'></script>
    <script type='text/javascript'>
$(document).ready(
  function() {
    $('input#tmpAddRow').click(
      function() {
        $('tr#tmp').clone(true).removeAttr('id').appendTo('tbody');
       $(":text").val(""); 
      }
    );
 $("select").each( function() {
           $(this).children(':first').attr('selected', 'selected');

         });


    $('tr input[type=text]').focus(
      function() {
        $(this).addClass('myFocused');   
      }
    ).blur(
      function() {
        $(this).removeClass('myFocused');
      }
    );
    $('.delete-icon').click(function() {$(this).closest('tr').remove()});
  }
);

    </script>
</head>
<body>
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">
<form action="<?php echo $this->baseUrl();?>/agriculture/index/add/id/<?php echo $this->memberid; ?>" method="POST">
<table id="hor-minimalist-b">
<tr> 
    <th><?php echo $this->translate("Details of land"); ?></th>
    <th><?php echo $this->translate("Acquisition type"); ?></th>
    <th><?php echo $this->translate("Owner name"); ?></th>
    <th><?php echo $this->translate("Village"); ?></th>
    <th><?php echo $this->translate("Survey no"); ?></th>
    <th><?php echo $this->translate("Acre"); ?></th>
    <th><?php echo $this->translate("Value"); ?></th>
    <th>Action</th>
</tr>
 <tr id='tmp'>
            <td><select name = tenant[]>
                            <?php foreach ($this->land_details as $land_details) { ?>
                            <option value="<?php echo $land_details['id']?>"><?php echo $land_details['name']?></option>
                            <?php } ?>
                        </select>
            </td>  
            <td><select name = ownertype[]>
                                <?php foreach ($this->ownertype as $ownertype) { ?>
                                <option value="<?php echo $ownertype['id']?>"><?php echo $ownertype['name']?></option>
                                <?php } ?>
                            </select>
            </td> 
            <td><INPUT type="text" name = "ownername[]" size="15"></td> 
            <td><INPUT type="text" name = "villagename[]" size="15"></td>
            <td><INPUT type="text" name = "survey[]" size="5"></td>
            <td><INPUT type="text" name = "acre[]" size="5"></td>
            <td><INPUT type="text" name = "acrevalue[]" size="5"></td>
            <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
        </tr>
    </table>  
 <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">
    <input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>"><a href="<? echo $this->baseUrl();?>/individualmcommonview/index/commonview/id/<? echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
</div>
</body>
</html>