<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<table id="hor-minimalist-b">
<?php 
    $i=$this->oldcount+1;
    $j=$this->oldcount+$this->newvalue;
    for($i;$i<=$j;$i++) {
    $a='name'.$i;
    $b='age'.$i;
    $c='gender'.$i;
    $d='relationship'.$i;
    $e='physicalstatus'.$i;
    $f='maritalstatus'.$i;	
?>
<tr>
    <td><?php echo $this->form->$a; ?></td>
    <td><?php echo $this->form->$b; ?></td>
    <td><?php echo $this->form->$c; ?></td>
    <td><?php echo $this->form->$d; ?></td>
    <td><?php echo $this->form->$e; ?></td>
    <td><?php echo $this->form->$f; ?></td>
    <td></td><td></td><td></td>
</tr> 
<?php } ?>
</table>