<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<?php if($this->results){ ?>

	  <table id="hor-minimalist-b">
		<tr><th><?php echo $this->translate("Activity name"); ?></th><th><?php echo $this->translate("No of accounts"); ?></th></tr>
<?php foreach($this->results as $activityresult){ ?>
	<tr>
	<td><?php echo $activityresult['activity_name']; ?></td>
	<td><?php echo $activityresult['COUNT(a.account_id)']; ?></td>
	</tr>
<?php } ?>
        </table>
<?php } ?>