<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<select name='subOffice1'  id="subOffice1" class="txt_put">
<option value=''>Select one</option>
<?php foreach($this->branchs as $branch) 
					{ ?>

<option value=<?php echo $branch["office_id"];?>><?php echo $branch["office_name"];?></option>
<?php } ?>
</select><b class="star">*</b>
<?php //var_dump(); ?>