<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<body onclick="limiter()">
    <form action="<?php echo $this->baseUrl();?>/membership/individualclone/individualadd" method="POST" name= "myform">
        <fieldset>
	<legend>Personal Information Information</legend>
            <div class="register">
	       <div class="profile_tab">
                    <table id="hor-minimalist-b">
                        <tr>
                            <td class = "label">Office Levels</td>
                            <td ><?php  echo $this->form->officeType;?><span class="reqMark">*</span></td>
			
                        </tr>
                        <tr>
                                <td class = "label">Branch</td>
                                <td ><div id="statediv"><?php  echo $this->form->subOffice;?><span class="reqMark"></span></div></td>
                        </tr>



                            <TR >
                                <TD  class = "label">Name</TD>
                                <TD ><?php echo $this->form->membertitle;?><input type="text" name=one
                                               class="txt_put" size = "12" tabindex="4"
                                                <?php if($this->firstName) {?> value = "<?php echo $this->firstName;?>" readonly = "true"<?php } ?>><span class="reqMark">*</span></TD> 
                            </tr>
                            <tr >  
                                <TD  class = "label">Father/Husband's Name </TD>
                                <TD ><?php echo $this->form->familymembername;?></TD>
                            </tr>
                            <tr>  
                                <TD  class = "label">Address Line 1</TD>
                                <TD ><?php echo $this->form->memberaddressline1;?></TD>
                            </tr>
                         
                            <tr>
                                <TD  class = "label">Line 2</TD>
                                <TD ><?php echo $this->form->memberaddressline2;?></TD>
                            </tr>

                            <tr>
                                <TD  class = "label">Line 3</TD>
                                <TD ><?php echo $this->form->memberaddressline3;?></TD>
                            </tr>
                            <tr> 
                                <td  class = "label">City / Village</td>
                                <td ><?php echo $this->form->membercity;?></td>
                            </tr>
                            <TR>
				<TD class = "label"><?php echo $this->form->Submit;?>
          			      <a href="<?php echo $this->baseUrl(array('controller'=>'index',
	         		        'action'=>'index')); ?>"></a></TD>
                                <td><input name="Back" type="submit" class="officebutton" value="Back"></TD>
		            </TR>
                    </table>
               </div>
	  </div>
    </fieldset>
</form>

 
