<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div>
	<?php If($this->member) { ?>
<div style="float:left;width:400px">
	<fieldset>
		<legend>Member details </legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<TR><td width="30%">Name:</td><TD width="50%"><?php echo $this->name ;?></TD></TR>
				<TR><td width="30%">Member code :</td><TD width="50%"><?php echo $this->code ;?></TD></TR>
				<TR><td width="30%">Account number:</td><TD width="50%"><?php echo $this->accountCode ;?></TD></TR>
				<TR><td width="30%">Branch office :</td><TD width="50%"><?php echo $this->Branchoffice ;?></TD></TR>
				<?php If($this->type==3) { ?>
					<TR><td>No of members in group:</td><TD width=""><?php echo $this->noOfMemberinGroup;?></TD></TR>
				<?php } ?>
			</table> 
		</div>
	</fieldset> 
</div>

<div style="float:left;width:400px">
	<fieldset>
		<legend>Account details</legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<TR><td width="30%">Account name :</td><TD width="50%"><?php echo $this->offerproductname ;?></TD></TR>
				<TR><td width="30%">Account number:</td><TD width="50%"><?php echo $this->accountCode ;?></TD></TR>
				<TR><td width="30%">created date:</td><TD width="50%"><?php echo $this->accountdreateddate ;?></TD></TR>
				<TR><td width="30%">savings balance:</td><TD width="50%"><?php echo $this->savingsbalance;?></TD>
				</TR>
				<?php If($this->type==3) { ?>
					<TR><td>No of members in this group account:</td><TD width=""><?php echo $this->noOfMemberinAccount;?></TD></TR>
				<?php } ?>
			</table> 
		</div>
	</fieldset> 
</div>
	<?php } else { ?>
<fieldset>
	<legend>Search</legend>
	<div class="cont-rgt-data">
		<form action="<?php echo $this->baseUrl();?>/transaction/saving" method="POST">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<tr>
					<td>Account Number/Member code</td>
					<td><?php echo $this->form->member_id;?></td>
				</tr>
				<tr>
					<TD colspan = "2"><?php echo $this->form->Search;?></TD>
				</tr>
			</table>
		</form>
	</div>
</fieldset>
	<?php } ?>
</div>
<?php If($this->memberdetails) { ?>
	<fieldset>
		<legend>Savings account</legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<TR>
					<td><span class="reqMark">Account number</span></td><td><span class="reqMark">Product name</span></td></TR>
					<?php foreach($this->accountIDFetch as $arrayroles2)  { ?>
					<TR><TD><a href="<?php echo $this->baseUrl();?>/transaction/saving/view/accountcode/
				<?php echo base64_encode($arrayroles2['account_number']);?>/code/
				<?php echo base64_encode($this->code);?>/categoryType/
				<?php echo $this->categoryType;?>"><?php echo $arrayroles2['account_number'];?></a></TD>
					<TD><?php echo $this->offerproductname;?></TD>
				</TR>
				<?php } ?>
			</table>
		</div>
	</fieldset>
<?php } ?>
 

<div>
<?php If($this->type==3) { ?>
<a href="#" id="open">Group members</a>
<div class="box">
<div id="content1">
	<fieldset>
		<legend> <?php echo $this->memberListtitle;?> </legend>
		<div class="cont-rgt-data">
	<table id="hor-minimalist-b" summary="Employee Pay Sheet">
		<tr class="tdbrownheading">
			<td width="30%">Name</td>
			<td width="50%">Code</td>
		</tr>

	<?php foreach($this->groupMembersDetails as $arrayroles1)  {?>

			<tr class="tdbrown">
				<TD width="30%"><?php echo $arrayroles1['memberfirstname'];?></TD>
				<TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
			</tr>

	<?php }?>
		</table>
</div></fieldset>
<p><a href="#" id="close">Hide</a></p>
</div>
</div>
<?php }?>
</div>

