<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<BODY onload="toggleField();"></BODY>
<!--common detals div-->
<Div> 
<div style="float:left;width:380px">
	<fieldset>
		<legend>Member details</legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
				<TR>
					<td width="30%">name:</td><TD width="50%"><?php echo $this->name;?></TD>
				</TR>
				<TR>
					<td>Member code:</td><TD><?php echo $this->code;?></TD>
				</TR>
				<TR>
					<td width="30%">Account number:</td><TD width="50%"><?php echo $this->accountCode ;?></TD>
				</TR>
				<TR>
					<td width="30%">Branch office:</td><TD width="50%"><?php echo $this->Branchoffice ;?></TD>
				</TR>
				<?php If($this->type==3) { ?>
				<TR>
					<td width="50%">No of members in group:</td><TD><?php echo $this->noOfMemberinGroup;?></TD>
				</TR>
				<?php }?>
			</table>
		</div>
	</fieldset>
</div>
<?php if($this->accountCode) { ?>
<div style="float:right;width:380px">
	<fieldset>
		<legend>Account details </legend>
		<div class="cont-rgt-data">
			<table id="hor-minimalist-b" summary="Employee Pay Sheet">
			<?php $i=1;foreach($this->accountDetails as $arrayroles1) { 
				if($i==1) { ?>
				<TR><td>Account name:</td><TD><?php echo $arrayroles1['offerproductname'];?></TD>
				</TR>
				<TR><td>Account number:</td><TD><?php echo $arrayroles1['account_number'];?></TD>
				</TR>
				<TR>
					<td>Account created date:</Td><TD width="50%"><?php echo $this->createddate;?></TD>
				</TR>
				<TR>
					<td>Savings balance:</td><TD><?php echo $this->savingsbalance;?></TD>
				</TR>
				<?php If($this->type==3) { ?>
				<TR>
					<td width="50%">No of members in this group account:</td><TD><?php echo $this->noOfMemberinAccount;?></TD>
				</TR>
				<?php } ?>
				<?php }
				$i++; 	} ?>
			</table>
		</div>
	</fieldset>
</div>
<?php } ?>
</Div>

<?php if(!$this->accountCode) { ?>
<DIV style="float:left;width:100%">
<?php If($this->type==3) { ?>
<a href="#" id="open">group members</a>
<div class="box">
<div id="content1">
	<fieldset>
		<legend> <?php echo $this->memberListtitle;?> </legend>
		<div class="cont-rgt-data">
	<table id="hor-minimalist-b" summary="Employee Pay Sheet">
		<tr class="tdbrownheading">
			<td width="30%">Name</td>
			<td width="50%">Code</td>
		</tr>
	<?php foreach($this->groupMembersDetails as $arrayroles1)  {?>
			<tr class="tdbrown">
				<TD width="30%"><?php echo $arrayroles1['memberfirstname'];?></TD>
				<TD width="50%"><?php echo $arrayroles1['membercode'];?></TD>
			</tr>
	<?php }?>
		</table>
</div></fieldset>
<p><a href="#" id="close">Hide</a></p>
</div>
</div>
<?php }?>
</DIV>
<?php }	?>
