<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<fieldset>
	<legend>Edit Ledger</legend>
	   <div class="register">
	       <div class="profile_tab">
<p align="right"><a href="<?php echo $this->baseUrl();?>/ledger/index/deleteledger/id/<?php echo $this->id;?>"><img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="20" height="20"></a></p>
                    <TABLE id="hor-minimalist-b">

                        <form action="<?php echo $this->baseUrl();?>/ledger/index/editledger" method="POST">
			  <TR >
                            <TD class="txt_rgt">Gl code</TD>
                            <TD ><?php echo $this->glcode;?></TD>
                        </TR>
			  <TR >
                            <TD class="txt_rgt">Gl header</TD>
                            <TD ><?php echo $this->form1->accountHeader;?></TD>
                        </TR>
                        <TR >
                            <TD class="txt_rgt">Description</TD>
                            <TD ><?php echo $this->form1->glcodeDescription;?></TD>
                        </TR>
                        <TR>
                            <TD class="txt_rgt"><?php echo $this->form1->Submit;?></TD>
                            <td><a href=<?php echo $this->baseUrl(); ?>/ledger/index>
                              <input name="submit" type="submit" class="officebutton" value="Back"></a></td>
                        </TR>
                    </TABLE>
		    <CENTER style="color:red"><?php echo $this->updateerror; ?></CENTER>
		    <?php echo $this->form1->hidden_glcodeid;?>
	           </form>
	       </div>
	  </div>
</fieldset>
