<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div id =3 style="width:400px;float:left">
    <fieldset>
    <legend>Existing Ledger</legend>
        <table id="hor-minimalist-b">
            <tr >
                <td ><b class="star">Gl Code</b></td>
                <td ><b class="star">Gl Header</b></td>
            </tr>
            <?php foreach($this->gldetails as $ledger) : ?>
                <tr >
                    <td >
                    <a href = "javascript:check('01',<?php echo $ledger->id;?>),getSubproduct('<?php echo $this->baseUrl();?>',<?php echo $ledger->ledgertype_id;?>),getSubLedger('<?php echo $this->baseUrl();?>',<?php echo $ledger->id;?>);"><?php echo $ledger->glcode;?>
                    </a>
                    </td>
                    <td ><?php echo $ledger->header;?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
</div>