<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/membername/index/addmembername" method="POST">
<fieldset>
<legend><?php echo $this->translate("Member details"); ?></legend>
    <table class="fieldsets">
            <?php echo $this->form; ?>
    </table>
    <div class="btnhouse">
        <div class="ltbtns">
            <input type="submit" name="Submit" id="Submit" value="<?php echo $this->translate("Submit"); ?>">
        </div>
        <div class="rtbtns">
            <a href="<?php echo $this->baseUrl();?>/individual"><input type="submit" name="back" id="back" value="<?php echo $this->translate("Back"); ?>"></a>
        </div>
    </div>
</fieldset>
</form>
