
<html>
  <head>
    <script type='text/javascript' src='<?php  echo $this->baseUrl();?>/js/jquery-1.3.2.min.js'></script>
    <script type='text/javascript' src='<?php  echo $this->baseUrl();?>/js/jquery-1.3.1.js'></script>
    <script type='text/javascript'>
    $(document).ready(
    function() {
        $('input#tmpAddRow').click(
        function() {
            var newRow = $('tr#tmp').clone(true).removeAttr('id');


            newRow.children("select").each( function() {
                $(this).children(':first').attr('selected', 'selected');
            });
            newRow.children("input:text").val("");

            newRow.appendTo('tbody');
        }
        );

        $('tr input[type=text]').focus(
        function() {
            $(this).addClass('myFocused');
        }
        ).blur(
        function() {
            $(this).removeClass('myFocused');
        }
        );

        $('.delete-icon').click(function() {$(this).closest('tr').remove()});
    }
    );

    </script>

<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">      
    <form name="form1" action="<?php echo $this->baseUrl();?>/activities/index/addactivities/id/<?php echo $this->id; ?>/subId/<?php echo $this->subId; ?>/modId/<?php echo $this->modId; ?>" method="POST">
        <table id="hor-minimalist-b">
            <tr> 
                <th ><?php echo $this->translate("Activities willing to takeup to increase the income"); ?></th><th></th>
            </tr>

            <tr id='tmp'>

                <td><input type="text"  name = "activity[]"></td><td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>

            </tr> 


        </table>  

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">
        <input type="submit" id="submit" name="submit" value="<?php echo $this->translate("Submit"); ?>">

        <a href="<? echo $this->baseUrl();?>/individualmcommonview/index/commonview/id/<? echo $this->memberid ?>">
            <input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>">
        </a>
    </form>
</div>
</html>
