<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<html>
  <head>
    <script type='text/javascript' src='<?php  echo $this->baseUrl();?>/js/jquery-1.3.2.min.js'></script>
    <script type='text/javascript' src='<?php  echo $this->baseUrl();?>/js/jquery-1.3.1.js'></script>
    <script type='text/javascript'>

        $(document).ready(
        function() {
            $('input#tmpAddRow').click(
            function() {
                var newRow = $('tr#tmp').clone(true).removeAttr('id');
                newRow.children("select").each( function() {
                    $(this).children(':first').attr('selected', 'selected');
                });
                newRow.children("input:text").val("");
                newRow.appendTo('tbody');
            }
            );

            $('tr input[type=text]').focus(
            function() {
                $(this).addClass('myFocused');   
            }
            ).blur(
            function() {
                $(this).removeClass('myFocused');
            }
            );

            $('.delete-icon').click(function() {$(this).closest('tr').remove()});
        }
        );

    </script>
<div style="height:250px; width:750px; overflow-x:scroll ; overflow-y: scroll; padding-bottom:10px;">      
    <form name="form1" action="<?php echo $this->baseUrl();?>/activities/index/editactivities/id/<?php echo $this->id; ?>/subId/<?php echo $this->subid; ?>/modId/<?php echo 2; ?>" method="POST">
        <table id="hor-minimalist-b">

            <tr> 
                <th ><?php echo $this->translate("Activities willing to takeup to increase the income"); ?></th><th></th>
            </tr>


            <?php $i = 0; ?>
            <?php foreach ($this->activity as $editCrop) { $i++;?>
             <?php if ($i == 1) { ?>
             <tr id='tmp'>
            <?php } else { ?>
            <tr>
            <?php } ?>

                <td><INPUT type="text" name = "activity[]" value = "<?php echo $editCrop["activity"];?>"></td>

                <td><img class="delete-icon" alt="delete" src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width='16' height='16'></td>
            </tr> 

        <?php } ?>
        </table>  

        <input type="button" id="tmpAddRow" name="Add" value="<?php echo $this->translate("Add"); ?>">
        <input type="submit" id="Update" name="Update" value="<?php echo $this->translate("Update"); ?>">
        <a href="<?php echo $this->baseUrl();?>/individualmcommonview/index/commonview/id/<?php echo $this->memberid ?>"><input type="button" id="submit" name="submit" value="<?php echo $this->translate("Back"); ?>"></a>
    </form>
</div>
