<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script> 
function getXMLHTTP() {
    var xmlhttp=false;	
        try{
            xmlhttp=new XMLHttpRequest();
        }
        catch(e) {
            try {	
                xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
            }
            catch(e){
                try {
                    xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
                }
                catch(e1){
                    xmlhttp=false;
                }
            }
        }
        return xmlhttp;
    }
function getInterests(interest,path,productId) {	
    var strURL=path+"/loanaccount/index/interest?interest="+interest+"&productId="+productId;

    var req = getXMLHTTP();
        if (req) {
            req.onreadystatechange = function() {
            if (req.readyState == 4) {
                if (req.status == 200) {
                    document.getElementById('interestratediv').innerHTML=req.responseText;
                } else {
                    alert("There was a problem while using XMLHTTP:\n" + req.statusText);
                  }
            }
        }
        req.open("GET", strURL, true);
        req.send(null);
        }
        var perioddescription=$('#perioddescription').val();
        if(perioddescription!='') {
            $('#errorspan').show();
        } else {
            $('#errorspan').hide();
          }
}


function displayRow(type) {
    var row = document.getElementById("funder");
    if(type == '2')
    row.style.display = 'none';
    else if (type == '1')
    row.style.display = '';

}
</script>
<?php 
if ($this->account) {
foreach ($this->account as $account) {
?>
<div style="float:left;width:380px"> 
    <table id="hor-minimalist-s" summary="Employee Pay Sheet">
        <TR>
            <TH>Member details</TH>
            <TH></TH>
        </TR>
        <TR>
            <td>Member code:</td>
            <TD><?php echo $account->code; ?></TD>
        </TR>
        <TR>
            <td>Name:</td>
            <TD><?php echo $account->name;?></TD>
        </TR>
        <TR>
            <td>Branch:</td>
            <td><?php echo $account->officename ;?></TD>
        </TR>
        <TR>
            <TH>Product details</TH>
            <TH></TH>
        </TR>          

        <TR>
            <td>Product name:</td>
            <TD><?php echo $account->productname;?></TD>
        </TR>
        <TR>
            <td>Min disbursement:</b></td>
            <TD><?php echo $account->minamount;?></TD>
        </TR>

        <TR>
            <td>Max disbursement:</td>
            <TD><?php echo $account->maxamount; ?></TD>
        </TR> 
        <TR>
            <td>Penal interest:</td>
            <TD><?php echo $account->penalInterest; ?></TD>
        </TR>
        <TR>
            <TH>Interest per annum</TH>
            <TH></TH>
        </TR>
        <TR>
            <TD><B>Periods in months</B></TD>
            <TD><B>Interest</B></TD>
        </TR>
        <?php if ($this->interestRates) {
              foreach ($this->interestRates as $interestRates) { ?>
              <TR>
                <td><?php echo $interestRates->period_ofrange_description; ?></td>
                <TD><?php echo $interestRates->Interest; ?></TD>
             </TR>
       <?php } } ?>
    </table>
<?php } } ?>
</div>
<div style="float:left;width:350px"> 
    <fieldset>
        <legend>Loan account</legend>
            <form name="addform" action="<?php echo $this->baseUrl();?>/loanaccount/index/createaccount" method="POST">
            <table class="fieldsets">
                    <TR>
                        <TD><label for="fld1" class="mand">Date of account</TD>
                        <TD><?php echo $this->loanForm->date;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Disbursement amount</TD>
                        <TD><?php echo $this->loanForm->amount;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Installments (Months)</TD>
                        <TD><?php echo $this->loanForm->installments;?></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Interest rate</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->interest;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Interest type</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->interesttype_id;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Transfer amount to</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->savingAccount;?></div></TD>
                    </TR>
                    <TR>
                        <TD><label for="fld1" class="mand">Fundings</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->fundings;?></div></TD>
                    </TR>
                    <TR id = "funder" style="display:none">
                        <TD><label for="fld1" class="mand">Funder</TD>
                        <TD><div id="interestratediv"><?php echo $this->loanForm->funders;?></div></TD>
                    </TR>
					<?php if ($this->loanForm->group) { ?>
                    <TR>
                        <TD><label for="fld1" class="mand">Group Member</TD>
                        <td><?php echo $this->loanForm->group; ?></td>
                    </TR>
					<?php } ?>
                    <TR>
                        <TD><?php echo $this->loanForm->Submit; ?></TD>
                        <td><?php echo $this->loanForm->Back; ?></td>
                    </TR>
                    <?php echo '<font color=RED>'.$this->maxdate.'</font>'; ?>
                </table>
                <?php echo $this->loanForm->Id; ?> <?php echo $this->loanForm->code; ?> 
            </form>
</div>
