<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<?php if($this->selectedSuboffice) { ?> 
<select name='parentoffice_ids'  id="parentoffice_ids" class="selectbutton">
<option value=''>select...</option>
<?php foreach($this->selectedSuboffice as $eacharraysent) { ?>
<option value="<?php echo $eacharraysent->office_id;?>"><?php echo $eacharraysent->office_name;?></option>
<? } ?>
<? } else { ?>
<select name='parentoffice_ids'  id="parentoffice_ids" class="selectbutton">
<?php foreach($this->officetypename as $officetype) { ?>
<option value="<?php echo $this->officetypeid; ?>"><?php echo $officetype->officetype;?></option>
<?php } ?>
<?php } ?>
</select>