<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
    <legend>Delete fundings</legend>
	<form action="<?php echo $this->baseUrl();?>/fundings/index/deletefundings" method="POST">
	   <table class="fieldsets">
           <TR>
           	<TD><label for="fld1" class="mand">Remarks</label></TD>
	    	<TD><?php echo $this->form->remarks;?></TD>					
		</TR>
		
		<TR>
		    <TD ><?php echo $this->form->Yes;?></td>
		    <TD ><a href="<?php echo $this->baseUrl();?>/fundingscommonview/index/commonview/id/<?php echo $this->id; ?>">
		      <input name="submit" type="submit"  value="No" ></a></TD>
		</TR>
	    </table>
	    <input type = "hidden" name = "id" value = "<?php echo $this->id; ?>">
	</form>
</fieldset>
