<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

			<form action="<?php echo $this->baseUrl();?>/feeinfo/index" method="POST">

<fieldset>
    <legend>Fee information</legend>
	<div class="cont-rgt-data">
                <TABLE id="hor-minimalist-b">
                    <TR>
                        <TD>Fee Name</TD>
                        <TD><?php echo $this->form->feename;?></TD> 

                    </TR>
    
                    <TR>
                        <TD>Fee Amount</TD>
                            <TD><?php echo $this->form->feeamount;?></TD>   

                    </TR>
    
                    <TR>
                        <TD>Fee Description</TD>
                                <TD><?php echo $this->form->feedescription;?></TD>   

                    </TR>
    
                   <tr>
                   </tr>
 <TR>
                        <TD class="label"><?php echo $this->form->Submit;?></TD>
                        <TD><a href="<?php echo $this->baseUrl(); ?>/management/fee/feeadd">
						<input name="submit" type="submit" class="officebutton" value="Back"></a></TD>
                    </TR>
            </TABLE>
    </div>
</fieldset>
</form>