<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
	<legend>Delete Meeting</legend>
	<div class="cont-rgt-data">
	<table id="hor-minimalist-b" summary="Employee Pay Sheet">
			<?php foreach($this->meeting as $meeting) ?>
 			<tr>
				<TD><label>Meeting Name</label></TD>
				<TD><?php echo $meeting['meeting_name'];?></TD><td></td><td></td>
	 		</TR>
                        <tr>
				<td class="txt_rgt">Office Name</td>
				<td><?php echo $meeting['office_name'];?></td>
				<td></td><td></td>
			</tr>
                        <tr>
              		<Th colspan="4">address</Th>
			</tr> 
			
			<tr>
				<TD><label>Group Name</label></TD>
				<TD><?php echo $meeting['groupname'];?></td>
				<TD><label>Meeting Name</label></TD>
				<TD><?php echo $meeting['meeting_name'];?></td>
			</tr>			
                        <tr>
				<TD><label>Meeting Place</label></TD>
				<TD><?php echo $meeting['meeting_place'];?></td>
				<TD><label>Time</label></TD>
				<TD><?php echo $meeting['time']?><?php echo $meeting['hourclock']?></td>
			</tr>
                        <tr>
				<TD><label>Group Head</label></TD>
				<TD><?php echo $meeting['group_head'];?></td><td></td><td></td>
				
			</tr>
		</table>
	</div>
</fieldset>

<?php if($this->recordstatus_id==1) { ?>
<table id="hor-minimalist-b" summary="Employee Pay Sheet">
<?php foreach($this->meeting as $meeting) {  ?>
	<tr>
		<Th align="center"><p><B style="color:red">No you cannot delete since the Office exists for </b>&nbsp;&nbsp;<B style="color:red">'<?php echo $meeting['meeting_name'];?>' Office</b></Th>
    </tr>
<?php } ?>
</table>
<?php } else { ?>
<?php foreach($this->meeting as $meeting) {  ?>
<table id="hor-minimalist-b" summary="Employee Pay Sheet">
	<tr>
		<th><B style="color:red">Are you sure you want to delete Office</b>&nbsp;&nbsp;<B style="color:red">"<?php echo $meeting['meeting_name'];?>" ?*</b></th>
	<tr>
<?php } ?>
</table>
<fieldset>
	<legend>Delete</legend>
			<div class="cont-rgt-data">
				<form action="<?php echo $this->baseUrl();?>/management/meeting/meetingdelete/id/<?php echo $this->office_id; ?>" method="POST" name="joe" id="signupForm" class="cmxform">
				<table id="hor-minimalist-b" summary="Employee Pay Sheet">
					<TR>
						<TD  width="35%" align="right" ><label>Remarks<span class="reqMark">*</span></label></TD>
						<TD  width="65%"  align="left" ><?php echo $this->deleteform->remarks;?></TD>
					</TR>
					<TR>
						<TD width="35%" align="right"><?php echo $this->deleteform->Yes;?></td>
						<TD width="65%"><a href="<?php echo $this->baseUrl();?>/management/meeting/">
						<input name="submit" type="submit"  value="No" ></a></TD>
					</TR>
				</table>
				</form>
			</div>
		</div>
</fieldset>
<?php } ?>



