<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<fieldset>
	<legend>viewAttendance</legend>
	<div class="cont-rgt-data">
	<table id="hor-minimalist-b" summary="Employee Pay Sheet">
			<?php foreach($this->meeting as $meeting) ?>
 			<tr>
				<TD><label>Meeting Name</label></TD>
				<TD><?php echo $meeting['meeting_name'];?></TD><td></td><td></td>
	 		</TR>
                        <tr>
				<td class="txt_rgt">Office Name</td>
				<td><?php echo $meeting['office_name'];?></td>
				<td></td><td></td>
			</tr>
                        <tr>
              		<Th colspan="4">address</Th>
			</tr> 
		        <tr>
				<TD><label>Group Name</label></TD>
				<TD><?php echo $meeting['groupname'];?></td>
				<TD><label>Meeting Name</label></TD>
				<TD><?php echo $meeting['meeting_name'];?></td>
			</tr>			
                        <tr>
				<TD><label>Meeting Place</label></TD>
				<TD><?php echo $meeting['meeting_place'];?></td>
				<TD><label>Time</label></TD>
				<TD><?php echo $meeting['timeg']?><?php foreach($this->meridam as $meeting) ?> <?php echo $meeting['hourclock']?></td>
			</tr>
                        <tr>
				<TD><label>Group Head</label></TD>
				<TD><?php foreach($this->meridam as $meeting) ?><?php echo $meeting['group_head'];?></td><td></td><td></td>
				
			</tr>
                        <tr>
				<TD colspan="4"><input name="submit" type="submit" onclick="history.go(-1)" 
					class="officebutton" value="back"></TD>
			</tr>
		</table>
	</div>
</fieldset>
