<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->
<form action="<?php echo $this->baseUrl();?>/reports/personalsavings/pdfgeneration" method="POST">   
<fieldset>
    <legend>Personal Savings Members</legend>
        <div class="cont-rgt-data">
            <table id="hor-minimalist-b" summary="Employee Pay Sheet" width="50%">
                <TR>
                    <TH>Account Number</TH> 
                    <TH>Account Name</TH> 
                    <TH>Member Code</TH> 
                    <TH>Member Name</TH> 
                    <TH>Created Date</TH>
                    <TH>Balance</TH>
                    <TH>Created By</TH> 
                </TR>
                 <?php foreach($this->paginator as $savings){?>
                    <TR>
                   
                        <TD><?php echo $savings['account_number']; ?></TD>   
                        <TD><?php echo $savings['offerproductname']; ?></TD> 
                        <TD><?php echo $savings['membercode']; ?></TD> 
                        <TD><?php echo $savings['name']; ?></TD> 
                        <TD><?php echo $savings['accountcreated_date']; ?></TD> 
                        <TD><?php echo $savings['balance']; ?></TD> 
                        <TD><?php echo $savings['login_name']; ?></TD>  
                    
                    </TR>
                <?php } ?>
                <tr>
			<td colspan="8"><div style="float:right;"><?= $this->paginationControl($this->paginator, 'Sliding', '/partials/my_pagination_control.phtml'); ?></div></td>
		</tr>
                
            </table>
            <input type="submit" value="PDF" id="submit">
	   <?php echo $this->Error;?>
        </div>
</fieldset>
</form>

