<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->



<div class="register">
	<div class="profile_tab"> 
<fieldset>
<legend>Interest Rates</legend>
	<form action="<?php echo $this->baseUrl();?>/interestrates/index/interestratesadd/creditline_id/<?php echo $this->creditline_id;?>" method="POST">
		<table style="float:left">

			<tr>
				<td colspan="5" class="td_border">Interest Rates</td>
			</tr>
			<TR >
				<TD class="label" align="right" width="40%">Interest Name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->InterestratesForm->interestname;?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Start Range<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->InterestratesForm->start_range;?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			
				<TD class="label" align="right" width="40%">End Range<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->InterestratesForm->end_range;?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			</TR>
			<TR >
				<TD class="label" align="right" width="40%">Interest<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->InterestratesForm->interest;?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			
				<TD class="label" align="right" width="40%">CreditLine Name<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->InterestratesForm->creditlinename;?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			</TR> 
			<TR >
				<TD class="label" align="right" width="40%">Status<span class="reqMark">*</span></TD>
				<TD ><?php echo $this->InterestratesForm->status;?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			</TR> 
			
			<TR >
				<TD class="label" align="right" width="40%"></TD>
				<TD ><?php echo $this->InterestratesForm->Submit;?><SPAN style="color:red"></SPAN></TD></SPAN></TD>
			</TR>
		</table>
	</form>
</fieldset>
