<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<script type="text/javascript">
    function fn(path,memberid)
    { 
        var id=document.getElementById('number').value;
        if(id) {
            targeturl=path+"/familydetails/index/getfamilymembers?id="+id+"&memberid="+memberid; 
            $.ajax({ url: targeturl, success: function(data){ $("#familymember").html(data) }});
        }
    }
</script>
<table id="hor-minimalist-b"><TR><TD><?php echo $this->translate("Enter number of family member"); ?></TD><TD><input type="text" name="number" id="number"     onkeyup="fn('<?php echo $this->baseUrl();?>',<?php echo $this->id; ?>)"></TD></TR></table>

<form action="<?php echo $this->baseUrl();?>/familydetails/index/add/id/<?php echo $this->id; ?>" method="POST"> 
    <div id="familymember"></div>
</form>
