<SCRIPT LANGUAGE="JavaScript">


function Check(chk)
{

if(document.myform.mainModule.checked==true)
{
for (i = 1; i < chk.length; i++)
chk[i].checked=true;
}

else{

for (i = 0; i < chk.length; i++)
chk[i].checked = false ;
}
}



function Subcheck(submodid, submodlen,actlen)
{
	var i,su;
	for(su=1;su<=submodlen;su++)
	{
 		var submo=eval("document.myform.subModule"+su);
		var str=eval("document.myform.activity"+su);

		if((submodid==su) && (submo.checked==true))
		{
			for (i = 0; i < actlen; i++)
			{
				str[i].checked=true;
			}
		}
		if((submodid==su) && (submo.checked==false))
		{
			for (i = 0; i < actlen; i++)
			{
				str[i].checked=false;
			}
		}

	}

}





</script>

<fieldset>
<legend>New Roles</legend>
    <div class="register">
        <div class="profile_tab">
            <form action="<?php echo $this->baseUrl();?>/roles/index/rolesadd" method="POST" name="myform" class="cmxform"  id="signupForm">
                <table id="hor-minimalist-b">
                    <tr> 
                        <th width = "20%">Role Name     <span class="reqMark">*</span></td>
                        <th width = "40%"><?php echo $this->form->grantname;?><?php echo $this->errorgrantname;?></SPAN></th>
                        <th width = "80%"></th>
                    </tr>
                </table>
                <table id="hor-minimalist-b" >
            	   <tr>
                        <?php $i =0; foreach($this->module as $module) {?>
                        <?php $i++; ?>
                        <?php if ($i == 1) {?>
                        <td width="30%"><input type="checkbox" onClick="Check(document.myform)" name="mainModule" value="<?php echo $module['module_id'] ?>"><?php echo $module['module_description']?></td>
                        
                        <?php } ?> 
                        <?php } ?>
                        <?php $sub=count($this->checkbox); $subchk=count($this->subcheckbox); foreach($this->checkbox as $checkbox) { 
				?>
                                <tr>
                                   <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" onClick="Subcheck(<?php echo $checkbox['submodule_id'] ?>,<?php echo $sub; ?>,<?php echo $subchk; ?>)" name="subModule" id="subModule<?php echo $checkbox['submodule_id'] ?>" value="<?php echo $checkbox['submodule_id'] ?>"><?php echo $checkbox['submodule_description']?></td>
                               <!-- </tr>
                                <tr>-->
                                    <?php foreach($this->subcheckbox as $subcheckbox) {?>
                                    <?php if ($checkbox['submodule_id'] == $subcheckbox['submodule_id']) {?>
                                   
                                    <td width="12%"><input type="checkbox" name="activity[]" id="activity<?php echo $subcheckbox['submodule_id'] ?>" value="<?php echo $subcheckbox['submodule_id'] ?> - <?php echo $subcheckbox['activity_id'] ?> "> <?php echo $subcheckbox['activity_name'];?></td>
                                    <?php } ?> 
                            
                                
                        
                        <?php } ?>
                        <?php } ?>
                        
                        <td ><?php echo $this->form->subactivity_id; ?></td>
                        </tr>
                        <tr>
                              <td colspan="2" class="txt_rgt" style="font-weight:bold; padding-left:225px;padding-top:25px;padding-bottom:10px;">
                              <div style="float:left"><?php echo $this->form->Submit;?></div></td>
                              <td><div style="float:left"><a href="<?php echo $this->baseUrl();?>/roles/index">
                              <input name="submit" type="submit" class="officebutton" value="Back"></a></div> </td>
                        </tr>
                   </table>
              </form>
         </div>
    </div>
</fieldset>