<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!--> 
<!-- external link for roles add javascript -->
<script type="text/javascript" src="<?php  echo $this->baseUrl();?>/js/rolesadd.js"></script>

<div id = "searchDiv">
<div class="searchDiv">
 <fieldset>
<form action="<?php echo $this->baseUrl();?>/roles/index/rolesedit" method="POST" name="myform" class="cmxform"  id="signupForm">
        <table id="hor-minimalist-b">
        <tr>
            <th><label for="fld1" class="mand">Grant name</label>   </th>
            <th><?php echo $this->form->grantname;?></th>
            <th></th><th></th><th><a href="<?php echo $this->baseUrl();?>/roles/index/rolesdelete/id/<?php echo $this->grantid;?>">
                <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></th>
        </tr>
       </table>
<input type="hidden" name="id" value="<?php echo $this->grantid; ?>">
    <table id="hor-minimalist-b">
         <tr bgcolor="Gray">
            <td>Modules</td>
            <td>Sub Module</td>
            <td>Add</td>
            <td>Edit</td>
            <td>View</td>
            <td>Delete</td>
        </tr>	
    <?php $dbobj = new Roles_Model_Roles();
$availModule = array();
foreach ($this->availmodule as $availmodules){
    $availModule[] = $availmodules['module_id']; // set all avail modules list 
    
}
        if($this->module) { 
            $modules = $this->module;
            // set checked checkboxes for selected modules and unchecked rest modules
            foreach($modules as $moduleslist){
                if($moduleslist['parent']=="0") { $moduleid = $moduleslist['module_id'];?>		
                    <tr>
                        <td colspan="6">
                             <?php if(in_array($moduleslist['module_id'],$availModule)){ ?>
                            <input type="checkbox" id="module_<?php echo $moduleslist['module_id']; ?>"   name="mainModule_<?php echo $moduleslist['module_id']; ?>" checked="true" class="mainmoduleClass" value="<?php echo $moduleslist['module_id']; ?>"><?php echo $moduleslist['module_description']; ?>
                             <?php } else { ?>
                                <input type="checkbox" id="module_<?php echo $moduleslist['module_id']; ?>"   name="mainModule_<?php echo $moduleslist['module_id']; ?>" class="mainmoduleClass" value="<?php echo $moduleslist['module_id']; ?>"><?php echo $moduleslist['module_description']; ?>
                                <?php } ?>                
                        </td>
                    </tr>
                        <?php $Submodule = $dbobj->getSubmodule($moduleid);    
                                foreach($Submodule as $Submodulelist){ 
                     ?>
                    <tr>
                    <td></td>
                    <td>
                        <?php if(in_array($Submodulelist['module_id'],$availModule)){ ?>
                        <input type="checkbox" id="submodule_<?php echo $Submodulelist['module_id']; ?>" checked="true"  name="submodule_<?php echo $moduleid?>" class="submoduleClass" value="<?php echo $Submodulelist['module_id']; ?>"><?php echo $Submodulelist['module_description']; ?>
                       <?php } else { ?>
                       <input type="checkbox" id="submodule_<?php echo $Submodulelist['module_id']; ?>"   name="submodule_<?php echo $moduleid?>" class="submoduleClass" value="<?php echo $Submodulelist['module_id']; ?>"><?php echo $Submodulelist['module_description']; ?>
                       <?php } ?>
                        
                       

                    </td>
                   

                    <?php if(in_array($Submodulelist['module_id'],$availModule)){
                      $activity = $dbobj->getActivity($Submodulelist['module_id'],$this->grantid);
                      foreach($activity as $activity1){
                     ?>
                    <td>    
                        <input type="checkbox" id="add_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" class="activityClass"  name="add_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" <?php if($activity1['add'] == 1){ ?> checked ="true" value="1" <?php } ?> >
                    </td> 
                    <td>
                        <input type="checkbox" id="edit_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" class="activityClass"  name="edit_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" <?php if($activity1['edit'] == 1){ ?> checked ="true" value="1" <?php } ?> >
                    </td>
                        <td>
                        <input type="checkbox" id="view_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" class="activityClass"  name="view_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>"  <?php if($activity1['view'] == 1){ ?> checked ="true" value="1" <?php } ?> >
                    </td>
                        <td>
                        <input type="checkbox" id="delete_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" class="activityClass"  name="delete_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>"  <?php if($activity1['delete'] == 1){ ?> checked ="true" value="1" <?php } ?> >
                    </td>
                    <?php } } else {?>
                     <td>    
                        <input type="checkbox" id="add_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" class="activityClass" value="1" name="add_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>"  >
                    </td> 
                    <td>
                        <input type="checkbox" id="edit_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>"  class="activityClass" value="1" name="edit_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>"  >
                    </td>
                        <td>
                        <input type="checkbox" id="view_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" class="activityClass" value="1" name="view_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" >
                    </td>
                        <td>
                        <input type="checkbox" id="delete_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>" class="activityClass" value="1" name="delete_<?php echo $moduleid; ?>_<?php echo $Submodulelist['module_id']; ?>"  >
                    </td>
                    <?php } ?>


                </tr>
          <?php }  } }  }  ?>
    </table>
 <div class="btnhouse">
            <div class="ltbtns">
               <input type="submit" name="Submit" value="Update"/>
            </div>
            <div class="rtbtns">
               <a href="<?php echo $this->baseUrl();?>/roles/index">
               <input type="button" name="back" value="Back"/></a>
            </div>
        </div>
    </form>
 </fieldset>
</div>
