<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<?php if($this->members) { ?>
    <table BORDER WIDTH=50% class="fieldsets">
        <tr><th bgcolor="Silver" align="center" ><b>Group members</b></th><th bgcolor="Silver" align="center"><b>Group head</b></th></tr>
        <?php foreach($this->members as $members) { ?>
        <TR>
            <td width="25%">
                <input type="checkbox" name="member_id[]" id="selector" value="<?php echo $members["id"];?>"><?php echo $members["name"];?>
            </td>
            <td width="25%">
                <input type="radio" name="memberhead"   id="memberhead" value="<?php echo $members["id"];?>">
            </td>
        </TR>
        <?php } ?>
    </table>
<?php } else {
        echo "<font color='RED'>No Members in the branch you seleted</font>";
 } ?>