<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<form action="<?php echo $this->baseUrl();?>/user/index/delete/id/<?php echo $this->user_id; ?>/modId/<?php echo $this->mod_id; ?>/subId/<?php echo $this->sub_id; ?>" method="POST">
<div class="register">
	<div class="profile_tab"> 
<fieldset>
<legend>User Details</legend>
		<table id="hor-minimalist-b">
                        <?php foreach($this->user as $funder_view){?>
                          <tr><th>User Information</th><th></th><th></th><th></th></tr>
                          
                        <tr><td>user Name:</td><td><?php echo $funder_view['firstname']; ?></td><td></td><td></td></tr>
                  
                                                <?php } ?>

			<tr><td><font color="red">Do you want to delete</font><?php echo $this->delete; ?></td><td></td><td></td></tr> 
			<tr><td></td><td><a href="<?php echo $this->baseUrl();?>/user/index/edituserdetail/id/<?php echo $this->funderid ?>"><input type="button" name="no" value="No"></a></tr>
			
		</table>
</fieldset>
</div>
</div>
</form>