<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->


<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/penalty/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">CreditLine name:</td>
                                    <td ><?php echo $this->form->field1;?></td>
                                    <td class="label">Penalty name:</td>
                                    <td ><?php echo $this->form->field2;?></td>
                                </tr>

                                <tr>
                                    <td class="label">Penalty From:</td>
                                    <td ><?php echo $this->form->field3;?></td>
                                    <td class="label">Penalty To:</td>
                                    <td ><?php echo $this->form->field4;?></td>
                                </tr>
                                <tr>
                                    <td colspan="4" align="center"><?php echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 



<fieldset>
	<legend>Penalty</legend>
	<table id="hor-minimalist-b" summary="">
    	<tr class="tdbrownheading">
        <th>Penalty Name</th>
        
        <th>Penalty / Month</th>
        
       <th>Penalty / Day</th>
       <th>Creditline Name</th>
        <th>Edit</td>
        <th>Delete</th>
    </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $penalty ): ?>
    <tr>
     
    <td><a href="<?php echo $this->baseUrl()."/penalty/index/penaltyview/penalty_id/".$penalty['penalty_id']; ?>"><?php echo $this->escape($penalty['penalty_name']);?></a></td>
     <td><?php echo $this->escape($penalty['penalty_per_month'])." ".$penalty['unitPenalty_per_month']; ?></td>
    
    <td><?php echo $this->escape($penalty['penalty_per_day'])." ".$penalty['unitPenalty_per_day'];?></td>
    <td><?php echo $this->escape($penalty['creditlinename']);?></div></td>

    <td><a href="<?php echo $this->baseUrl()."/penalty/index/penaltyedit/penalty_id/".$penalty['penalty_id']; ?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></td>
    <td><a href="<?php echo $this->baseUrl()."/penalty/index/penaltydelete/penalty_id/".$penalty['penalty_id']; ?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
        <?php endforeach; ?>
        <?php endif; ?>

    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                    '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>
</tr>
</table>
<br>
    <table>
        <TR>        
                   <td colspan="8"><a href="<?php  echo $this->baseUrl();?>/penalty/index/penaltyadd">
        <input name="submit" type="submit" class="NormalBtn" value="New Penalty"></a></td>
        </TR>
    </table>
</fieldset>