<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->




<div id = "searchDiv">
<fieldset>
<legend>Add penalty</legend>
	<form action="<?php echo $this->baseUrl();?>/penalty/index/penaltyadd/creditline_id/<?php echo $this->creditline_id;?>" method="POST">
		<table class="fieldsets">
			
			<TR >
				<TD ><label for="fld1" class="mand">Penalty name</TD>
				<TD ><?php echo $this->penaltyform->penaltyname;?></TD>
			</TR>
			<TR >
				<TD ><label for="fld1" class="mand">Penalty for delay (%)</TD>
				<TD ><?php echo $this->penaltyform->penalty_per_delay;?></TD>
			</TR>
			<TR >
				<TD ><label for="fld1" class="mand">Interest of delay / day (%)</TD>
				<TD ><?php echo $this->penaltyform->interest_of_delay;?></TD>
			</TR> 
			<TR >
				<TD ><label for="fld1" class="mand">Creditline name</TD>
				<TD ><?php echo $this->penaltyform->creditlinename;?></TD>
			</TR> 
			<TR >
				<TD ><label for="fld1" class="mand">Active</TD>
				<TD ><?php echo $this->penaltyform->status;?></TD>
			</TR> 
		</table>
		<div class="btnhouse">
			<div class="ltbtns">
			<input type="Submit" name="Submit" name="Submit" value="Submit">
			</div>
			<div class="rtbtns">
			<a href="<?php echo $this->baseUrl();?>/penaltyindex"><input type="button" value="Back"></a>
			</div>
		</div>
	</form>
</fieldset>
</div>
