<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                <form action="<?php echo $this->baseUrl();?>/group/index/" method="POST">
                    <table class="fieldsets"> 
                        <?php echo $this->form;?>
                    </table>
                    <div class="btnhouse">
                        <div class="ltbtns">
                            <input type = "Submit" name = "Search" id="Search" value = "Search"/>
                        </div>
                    </div>
                </form>	
            </div>
       </fieldset>
 </div>  
<?php  if((count($this->paginator) ==0) && ($this->search == true))  {
echo "<font color='RED'>Records Not Found Try Again...</font>";
}
if(count($this->paginator)!=0) { ?>
    <table id="hor-minimalist-b">
        <tr class="tdbrownheading">
            <th>Group code</th>
            <th>Group name</td>
        </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $group): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl()."/groupcommonview/index/commonview/id/"?><?php echo $group['groupid']; ?>">
                        <?php echo $this->escape($group['groupcode']); ?></a></td>
        <td><?php echo $this->escape($group['group_name']);?></td>
            <?php endforeach; ?>
            <?php endif; ?>
        </tr>
        <tr>
            <td colspan="8" align="right">
                <div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                '/partials/my_pagination_control.phtml'); ?>
                </div>
            </td>
        </tr>
    </table>
<?php } ?>

