<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div>
<div style="width:470px;float:left">
<fieldset>
    <legend>Funders Edit</legend>
        <div class="cont-rgt-data">
            <form action="<?php echo $this->baseUrl();?>/management/funders/fundersedit" method="POST">
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <tr>
                        <TD>Funders Name :</TD>
                        <TD><?php echo $this->form->fundername;echo $this->form->funderaddress_id;?><?php   $this->updateerror; ?></TD>
                    </TR>
                    <TR>
                        <TD>Short Name :</TD>
                        <TD><?php echo $this->form->fundershortname;?><?php echo $this->form->funder_id;?></TD>
                    </TR>
                    <tr>
                        <th colspan="4">Address<th>
                    </tr>
                    <tr> 
                        <td>Line 1 :</td>
                        <td><?php echo $this->form->funderaddress1;?></td>
                    </tr>
                    <tr> 
                        <td>Line 2 :</td>
                        <td><? echo $this->form->funderaddress2;?></td>
                    </tr>
                    <tr> 
                        <td>line 3 :</td>
                        <td><? echo $this->form->funderaddress3;?></td>
                    </tr>
                    <tr> 
                        <td>City :</td>
                        <td><? echo $this->form->fundercity;?></td>
                    </tr>
                    <tr> 
                        <td>State :</td>
                        <td><? echo $this->form->funderstate;?></td>
                    </tr>
                    <tr> 
                        <td>Country :</td>
                        <td><? echo $this->form->fundercountry;?></td>
                    </tr>
                    <tr> 
                        <td>Pincode :</td>
                        <td><? echo $this->form->funderpincode;?></td>
                    </tr>
                    <tr> 
                        <td>E-mail :</td>
                        <td><? echo $this->form->emailaddress;?></td>
                    </tr>
                    <tr> 
                        <td>Telephonenumber :</td>
                        <td><? echo $this->form->funderphone;?></td>
                    </tr>
                </table>
            </div>
            <table width="100%">
                <TR>
                 <td><a href="<?php echo $this->baseUrl(); ?>/management/funders"><input name="submit" type="submit" class="NormalBtn" 
                                    value="back"></a></td>
                    <td align="right"><?echo $this->form->Submit;?></td>
                </TR>
            </table>
                <b style="color:red;"><?php echo $this->updatEerror; ?></b>
        </form>
</fieldset>
</div>
<div style="width:320px;float:left;">
    <fieldset>
        <legend>Alreadyexisting Funders</legend>
            <div class="cont-rgt-data">
                <table id="hor-minimalist-b" summary="Employee Pay Sheet">
                    <TR class="tdbrownheading">
                        <th>Funders Name</th>
                        <th>Short Name</th>
                    </TR>
                    <?php foreach($this->funders as $funders) : ?>
                    <tr>
                        <td><?php echo $this->escape($funders->fundername);?></td>
                        <td> <?php echo $this->escape($funders->fundershortname );?></td>
                    </tr>
                    <?php endforeach;?>
                </table>
            </div>
</fieldset>
</div>
</div>