<!--
############################################################################
#  This file is part of OurBank.
############################################################################
#  OurBank is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
############################################################################
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
############################################################################
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
############################################################################
!-->

<div id="searchDiv">
    <fieldset>
        <legend>Search</legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/management/funders/index" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label">Funders Name:</td>
                                    <td ><?php echo $this->form->field1;?></td>
                                    <td class="label">Country:</td>
                                    <td ><?php echo $this->form->field2;?></td>
                                </tr>

                                <tr>
                                    <td class="label">Telephone Number:</td>
                                    <td ><?php echo $this->form->field3;?></td>
                                    <td class="label">Email:</td>
                                    <td ><?php echo $this->form->field4;?></td>
                                </tr>
                                <tr>
                                    <td colspan="4" align="center"><?php echo $this->form->Search;?></td>
                                </tr>
                        </table>
                    </form>	
            </div>
    </fieldset> 
</div> 
  <fieldset>
        <legend>Funders</legend>
<table id="hor-minimalist-b">
    <tr>
        <th>Funders Name</th>
        <th>Country</td>
        <th>Telephone Number</td>
        <th>Email</th>
        <th>Edit</td>
        <th>Delete</th>
    </tr>
        <?php if (count($this->paginator)){?>
        <?php foreach ($this->paginator as $funders ): ?>
    <tr>
        <td><a href="<?php echo $this->baseUrl()."/management/funders/fundersview/id/".$funders['funderaddress_id']; ?>">
                     <?php echo $this->escape($funders['fundername']); ?></a></td>
    <td><?php echo $this->escape($funders['fundercountry']);?></td>
    <td><?php echo $this->escape($funders['funderphone']);?></td>
    <td><?php echo $this->escape($funders['emailaddress']);?></div></td>
    <td><a href="<?php echo $this->baseUrl();?>/management/funders/fundersedit/id/<?php echo $funders['funderaddress_id'];?>">
                 <img src="<?php echo $this->baseUrl(); ?>/images/edit.gif" border=0 width="16" height="16"></a></td>
    <td><a href="<?php echo $this->baseUrl();?>/management/funders/fundersdelete/id/<?php echo $funders['funderaddress_id'];?>">
                <img src="<?php echo $this->baseUrl(); ?>/images/delete.gif" border=0 width="16" height="16"></a></td>
                <?php endforeach; ?>
   
    <tr>
        <td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->paginator,'Sliding',
                                    '/partials/my_pagination_control.phtml'); ?></div></td>
    </tr>


<table>
    <tr>
        <td colspan="8"><a href="<?php  echo $this->baseUrl();?>/management/funders/fundersadd">
        <input name="submit" type="submit" class="NormalBtn" value="New Funder"></a></td>


    </tr>
</table>
 <?php }
else{ ?>


<table>
    <tr>
        <td colspan="8"><a href="<?php  echo $this->baseUrl();?>/management/funders/fundersadd">
        <input name="submit" type="submit" class="NormalBtn" value="New Funder"></a>
 <?php echo "<font color=red family=arial size=2> No Records found</font>";  ?>
</td>


    </tr>

</table>
<?php
} ?>


</table>
<br>


</fieldset>

